// Code generated by ent, DO NOT EDIT.

package settings

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the settings type in the database.
	Label = "settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGuildID holds the string denoting the guildid field in the database.
	FieldGuildID = "guild_id"
	// FieldBotUpdatesChannelID holds the string denoting the botupdateschannelid field in the database.
	FieldBotUpdatesChannelID = "bot_updates_channel_id"
	// FieldTreshold holds the string denoting the treshold field in the database.
	FieldTreshold = "treshold"
	// FieldSelf holds the string denoting the self field in the database.
	FieldSelf = "self"
	// FieldIgnoredChannelIds holds the string denoting the ignoredchannelids field in the database.
	FieldIgnoredChannelIds = "ignored_channel_ids"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the settings in the database.
	Table = "settings"
)

// Columns holds all SQL columns for settings fields.
var Columns = []string{
	FieldID,
	FieldGuildID,
	FieldBotUpdatesChannelID,
	FieldTreshold,
	FieldSelf,
	FieldIgnoredChannelIds,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTreshold holds the default value on creation for the "treshold" field.
	DefaultTreshold int
	// DefaultSelf holds the default value on creation for the "self" field.
	DefaultSelf bool
	// DefaultIgnoredChannelIds holds the default value on creation for the "ignoredChannelIds" field.
	DefaultIgnoredChannelIds []string
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Settings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGuildID orders the results by the guildID field.
func ByGuildID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGuildID, opts...).ToFunc()
}

// ByBotUpdatesChannelID orders the results by the botUpdatesChannelID field.
func ByBotUpdatesChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBotUpdatesChannelID, opts...).ToFunc()
}

// ByTreshold orders the results by the treshold field.
func ByTreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTreshold, opts...).ToFunc()
}

// BySelf orders the results by the self field.
func BySelf(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelf, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
