// Code generated by ent, DO NOT EDIT.

package settings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lib/pq"
	"jurien.dev/yugen/hoshi/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldID, id))
}

// GuildID applies equality check predicate on the "guildID" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldGuildID, v))
}

// BotUpdatesChannelID applies equality check predicate on the "botUpdatesChannelID" field. It's identical to BotUpdatesChannelIDEQ.
func BotUpdatesChannelID(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldBotUpdatesChannelID, v))
}

// Treshold applies equality check predicate on the "treshold" field. It's identical to TresholdEQ.
func Treshold(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldTreshold, v))
}

// Self applies equality check predicate on the "self" field. It's identical to SelfEQ.
func Self(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldSelf, v))
}

// IgnoredChannelIds applies equality check predicate on the "ignoredChannelIds" field. It's identical to IgnoredChannelIdsEQ.
func IgnoredChannelIds(v pq.StringArray) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldIgnoredChannelIds, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUpdatedAt, v))
}

// GuildIDEQ applies the EQ predicate on the "guildID" field.
func GuildIDEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guildID" field.
func GuildIDNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guildID" field.
func GuildIDIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guildID" field.
func GuildIDNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guildID" field.
func GuildIDGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guildID" field.
func GuildIDGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guildID" field.
func GuildIDLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guildID" field.
func GuildIDLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guildID" field.
func GuildIDContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guildID" field.
func GuildIDHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guildID" field.
func GuildIDHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guildID" field.
func GuildIDEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guildID" field.
func GuildIDContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldGuildID, v))
}

// BotUpdatesChannelIDEQ applies the EQ predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDNEQ applies the NEQ predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDIn applies the In predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldBotUpdatesChannelID, vs...))
}

// BotUpdatesChannelIDNotIn applies the NotIn predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldBotUpdatesChannelID, vs...))
}

// BotUpdatesChannelIDGT applies the GT predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDGTE applies the GTE predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDLT applies the LT predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDLTE applies the LTE predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDContains applies the Contains predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDHasPrefix applies the HasPrefix predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDHasSuffix applies the HasSuffix predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDIsNil applies the IsNil predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDIsNil() predicate.Settings {
	return predicate.Settings(sql.FieldIsNull(FieldBotUpdatesChannelID))
}

// BotUpdatesChannelIDNotNil applies the NotNil predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDNotNil() predicate.Settings {
	return predicate.Settings(sql.FieldNotNull(FieldBotUpdatesChannelID))
}

// BotUpdatesChannelIDEqualFold applies the EqualFold predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldBotUpdatesChannelID, v))
}

// BotUpdatesChannelIDContainsFold applies the ContainsFold predicate on the "botUpdatesChannelID" field.
func BotUpdatesChannelIDContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldBotUpdatesChannelID, v))
}

// TresholdEQ applies the EQ predicate on the "treshold" field.
func TresholdEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldTreshold, v))
}

// TresholdNEQ applies the NEQ predicate on the "treshold" field.
func TresholdNEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldTreshold, v))
}

// TresholdIn applies the In predicate on the "treshold" field.
func TresholdIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldTreshold, vs...))
}

// TresholdNotIn applies the NotIn predicate on the "treshold" field.
func TresholdNotIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldTreshold, vs...))
}

// TresholdGT applies the GT predicate on the "treshold" field.
func TresholdGT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldTreshold, v))
}

// TresholdGTE applies the GTE predicate on the "treshold" field.
func TresholdGTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldTreshold, v))
}

// TresholdLT applies the LT predicate on the "treshold" field.
func TresholdLT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldTreshold, v))
}

// TresholdLTE applies the LTE predicate on the "treshold" field.
func TresholdLTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldTreshold, v))
}

// SelfEQ applies the EQ predicate on the "self" field.
func SelfEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldSelf, v))
}

// SelfNEQ applies the NEQ predicate on the "self" field.
func SelfNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldSelf, v))
}

// IgnoredChannelIdsEQ applies the EQ predicate on the "ignoredChannelIds" field.
func IgnoredChannelIdsEQ(v pq.StringArray) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldIgnoredChannelIds, v))
}

// IgnoredChannelIdsNEQ applies the NEQ predicate on the "ignoredChannelIds" field.
func IgnoredChannelIdsNEQ(v pq.StringArray) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldIgnoredChannelIds, v))
}

// IgnoredChannelIdsIn applies the In predicate on the "ignoredChannelIds" field.
func IgnoredChannelIdsIn(vs ...pq.StringArray) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldIgnoredChannelIds, vs...))
}

// IgnoredChannelIdsNotIn applies the NotIn predicate on the "ignoredChannelIds" field.
func IgnoredChannelIdsNotIn(vs ...pq.StringArray) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldIgnoredChannelIds, vs...))
}

// IgnoredChannelIdsGT applies the GT predicate on the "ignoredChannelIds" field.
func IgnoredChannelIdsGT(v pq.StringArray) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldIgnoredChannelIds, v))
}

// IgnoredChannelIdsGTE applies the GTE predicate on the "ignoredChannelIds" field.
func IgnoredChannelIdsGTE(v pq.StringArray) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldIgnoredChannelIds, v))
}

// IgnoredChannelIdsLT applies the LT predicate on the "ignoredChannelIds" field.
func IgnoredChannelIdsLT(v pq.StringArray) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldIgnoredChannelIds, v))
}

// IgnoredChannelIdsLTE applies the LTE predicate on the "ignoredChannelIds" field.
func IgnoredChannelIdsLTE(v pq.StringArray) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldIgnoredChannelIds, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.NotPredicates(p))
}
