services:
  kazu:
    build: .
    user: "1000:1000"
    command: "kazu"
    env_file:
      - .env
      - ./apps/kazu/.env
    volumes:
      - .:/opt/app
    ports:
      - "$KAZU_API_LISTEN_PORT:$API_LISTEN_PORT"
    depends_on:
      db:
        condition: service_healthy
  kusari:
    build: .
    user: "1000:1000"
    command: "kusari"
    env_file:
      - .env
      - ./apps/kusari/.env
    volumes:
      - .:/opt/app
    ports:
      - "$KUSARI_API_LISTEN_PORT:$API_LISTEN_PORT"
    depends_on:
      valkey:
        condition: service_started
      db:
        condition: service_healthy
  iro:
    build: .
    user: "1000:1000"
    command: "iro"
    env_file:
      - .env
      - ./apps/iro/.env
    volumes:
      - .:/opt/app
    ports:
      - "$IRO_API_LISTEN_PORT:$API_LISTEN_PORT"
  hoshi:
    build: .
    user: "1000:1000"
    command: "hoshi"
    env_file:
      - .env
      - ./apps/hoshi/.env
    volumes:
      - .:/opt/app
    ports:
      - "$HOSHI_API_LISTEN_PORT:$API_LISTEN_PORT"
    depends_on:
      db:
        condition: service_healthy
  koto:
    build: .
    user: "1000:1000"
    command: "koto"
    env_file:
      - .env
      - ./apps/koto/.env
    volumes:
      - .:/opt/app
    ports:
      - "$KOTO_API_LISTEN_PORT:$API_LISTEN_PORT"
    depends_on:
      db:
        condition: service_healthy

  valkey:
    image: valkey/valkey:alpine
  db:
    image: postgres:12.2-alpine
    volumes:
      - ./pg-init-script:/docker-entrypoint-initdb.d/pg-init-scripts.sh
    environment:
      - "POSTGRES_USER=$DATABASE_USER"
      - "POSTGRES_PASSWORD=$DATABASE_PASSWORD"
      - "POSTGRES_MULTIPLE_DATABASES=$DATABASE_NAME"
    ports:
      - "$DATABASE_PORT:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DATABASE_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
