services:
  kazu:
    build: .
    user: "1000:1000"
    command: "make kazu"
    env_file:
      - .env
      - ./apps/kazu/.env
    volumes:
      - .:/opt/app
    ports:
      - "$KAZU_API_LISTEN_PORT:$API_LISTEN_PORT"
  kusari:
    build: .
    user: "1000:1000"
    command: "make kusari"
    env_file:
      - .env
      - ./apps/kusari/.env
    volumes:
      - .:/opt/app
    ports:
      - "$KUSARI_API_LISTEN_PORT:$API_LISTEN_PORT"
  iro:
    build: .
    user: "1000:1000"
    command: "make iro"
    env_file:
      - .env
      - ./apps/iro/.env
    volumes:
      - .:/opt/app
    ports:
      - "$IRO_API_LISTEN_PORT:$API_LISTEN_PORT"
  hoshi:
    build: .
    user: "1000:1000"
    command: "make hoshi"
    env_file:
      - .env
      - ./apps/hoshi/.env
    volumes:
      - .:/opt/app
    ports:
      - "$HOSHI_API_LISTEN_PORT:$API_LISTEN_PORT"
  koto:
    build: .
    user: "1000:1000"
    command: "make koto"
    env_file:
      - .env
      - ./apps/koto/.env
    volumes:
      - .:/opt/app
    ports:
      - "$KOTO_API_LISTEN_PORT:$API_LISTEN_PORT"
  db:
    image: postgres:12.2-alpine
    volumes:
      - ./pg-init-script:/docker-entrypoint-initdb.d/pg-init-scripts.sh
    environment:
      - "POSTGRES_USER=$DATABASE_USER"
      - "POSTGRES_PASSWORD=$DATABASE_PASSWORD"
      - "POSTGRES_MULTIPLE_DATABASES=$DATABASE_NAME"
    ports:
      - "$DATABASE_PORT:5432"
