// Code generated by ent, DO NOT EDIT.

package honeypot

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the honeypot type in the database.
	Label = "honeypot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGuildID holds the string denoting the guildid field in the database.
	FieldGuildID = "guild_id"
	// FieldChannelID holds the string denoting the channelid field in the database.
	FieldChannelID = "channel_id"
	// FieldIgnoredRoleIDs holds the string denoting the ignoredroleids field in the database.
	FieldIgnoredRoleIDs = "ignored_role_ids"
	// FieldDeleteMessageDays holds the string denoting the deletemessagedays field in the database.
	FieldDeleteMessageDays = "delete_message_days"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the honeypot in the database.
	Table = "honeypots"
)

// Columns holds all SQL columns for honeypot fields.
var Columns = []string{
	FieldID,
	FieldGuildID,
	FieldChannelID,
	FieldIgnoredRoleIDs,
	FieldDeleteMessageDays,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIgnoredRoleIDs holds the default value on creation for the "ignoredRoleIDs" field.
	DefaultIgnoredRoleIDs []string
	// DefaultDeleteMessageDays holds the default value on creation for the "deleteMessageDays" field.
	DefaultDeleteMessageDays int
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Honeypot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGuildID orders the results by the guildID field.
func ByGuildID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGuildID, opts...).ToFunc()
}

// ByChannelID orders the results by the channelID field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByDeleteMessageDays orders the results by the deleteMessageDays field.
func ByDeleteMessageDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteMessageDays, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
