// Code generated by ent, DO NOT EDIT.

package playerstats

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the playerstats type in the database.
	Label = "player_stats"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the userid field in the database.
	FieldUserID = "userId"
	// FieldGuildID holds the string denoting the guildid field in the database.
	FieldGuildID = "guildId"
	// FieldInGuild holds the string denoting the inguild field in the database.
	FieldInGuild = "inGuild"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldParticipated holds the string denoting the participated field in the database.
	FieldParticipated = "participated"
	// FieldWins holds the string denoting the wins field in the database.
	FieldWins = "wins"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updatedAt"
	// Table holds the table name of the playerstats in the database.
	Table = "PlayerStats"
)

// Columns holds all SQL columns for playerstats fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldGuildID,
	FieldInGuild,
	FieldPoints,
	FieldParticipated,
	FieldWins,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInGuild holds the default value on creation for the "inGuild" field.
	DefaultInGuild bool
	// DefaultPoints holds the default value on creation for the "points" field.
	DefaultPoints int
	// DefaultParticipated holds the default value on creation for the "participated" field.
	DefaultParticipated int
	// DefaultWins holds the default value on creation for the "wins" field.
	DefaultWins int
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PlayerStats queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the userID field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGuildID orders the results by the guildID field.
func ByGuildID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGuildID, opts...).ToFunc()
}

// ByInGuild orders the results by the inGuild field.
func ByInGuild(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInGuild, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByParticipated orders the results by the participated field.
func ByParticipated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParticipated, opts...).ToFunc()
}

// ByWins orders the results by the wins field.
func ByWins(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWins, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
