// Code generated by ent, DO NOT EDIT.

package playerstats

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"jurien.dev/yugen/koto/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "userID" field. It's identical to UserIDEQ.
func UserID(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldUserID, v))
}

// GuildID applies equality check predicate on the "guildID" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldGuildID, v))
}

// InGuild applies equality check predicate on the "inGuild" field. It's identical to InGuildEQ.
func InGuild(v bool) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldInGuild, v))
}

// Points applies equality check predicate on the "points" field. It's identical to PointsEQ.
func Points(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldPoints, v))
}

// Participated applies equality check predicate on the "participated" field. It's identical to ParticipatedEQ.
func Participated(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldParticipated, v))
}

// Wins applies equality check predicate on the "wins" field. It's identical to WinsEQ.
func Wins(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldWins, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "userID" field.
func UserIDEQ(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "userID" field.
func UserIDNEQ(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "userID" field.
func UserIDIn(vs ...string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "userID" field.
func UserIDNotIn(vs ...string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "userID" field.
func UserIDGT(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "userID" field.
func UserIDGTE(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "userID" field.
func UserIDLT(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "userID" field.
func UserIDLTE(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "userID" field.
func UserIDContains(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "userID" field.
func UserIDHasPrefix(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "userID" field.
func UserIDHasSuffix(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "userID" field.
func UserIDEqualFold(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "userID" field.
func UserIDContainsFold(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldContainsFold(FieldUserID, v))
}

// GuildIDEQ applies the EQ predicate on the "guildID" field.
func GuildIDEQ(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guildID" field.
func GuildIDNEQ(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guildID" field.
func GuildIDIn(vs ...string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guildID" field.
func GuildIDNotIn(vs ...string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guildID" field.
func GuildIDGT(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guildID" field.
func GuildIDGTE(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guildID" field.
func GuildIDLT(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guildID" field.
func GuildIDLTE(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guildID" field.
func GuildIDContains(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guildID" field.
func GuildIDHasPrefix(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guildID" field.
func GuildIDHasSuffix(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guildID" field.
func GuildIDEqualFold(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guildID" field.
func GuildIDContainsFold(v string) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldContainsFold(FieldGuildID, v))
}

// InGuildEQ applies the EQ predicate on the "inGuild" field.
func InGuildEQ(v bool) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldInGuild, v))
}

// InGuildNEQ applies the NEQ predicate on the "inGuild" field.
func InGuildNEQ(v bool) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNEQ(FieldInGuild, v))
}

// PointsEQ applies the EQ predicate on the "points" field.
func PointsEQ(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldPoints, v))
}

// PointsNEQ applies the NEQ predicate on the "points" field.
func PointsNEQ(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNEQ(FieldPoints, v))
}

// PointsIn applies the In predicate on the "points" field.
func PointsIn(vs ...int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldIn(FieldPoints, vs...))
}

// PointsNotIn applies the NotIn predicate on the "points" field.
func PointsNotIn(vs ...int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNotIn(FieldPoints, vs...))
}

// PointsGT applies the GT predicate on the "points" field.
func PointsGT(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGT(FieldPoints, v))
}

// PointsGTE applies the GTE predicate on the "points" field.
func PointsGTE(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGTE(FieldPoints, v))
}

// PointsLT applies the LT predicate on the "points" field.
func PointsLT(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLT(FieldPoints, v))
}

// PointsLTE applies the LTE predicate on the "points" field.
func PointsLTE(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLTE(FieldPoints, v))
}

// ParticipatedEQ applies the EQ predicate on the "participated" field.
func ParticipatedEQ(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldParticipated, v))
}

// ParticipatedNEQ applies the NEQ predicate on the "participated" field.
func ParticipatedNEQ(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNEQ(FieldParticipated, v))
}

// ParticipatedIn applies the In predicate on the "participated" field.
func ParticipatedIn(vs ...int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldIn(FieldParticipated, vs...))
}

// ParticipatedNotIn applies the NotIn predicate on the "participated" field.
func ParticipatedNotIn(vs ...int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNotIn(FieldParticipated, vs...))
}

// ParticipatedGT applies the GT predicate on the "participated" field.
func ParticipatedGT(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGT(FieldParticipated, v))
}

// ParticipatedGTE applies the GTE predicate on the "participated" field.
func ParticipatedGTE(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGTE(FieldParticipated, v))
}

// ParticipatedLT applies the LT predicate on the "participated" field.
func ParticipatedLT(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLT(FieldParticipated, v))
}

// ParticipatedLTE applies the LTE predicate on the "participated" field.
func ParticipatedLTE(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLTE(FieldParticipated, v))
}

// WinsEQ applies the EQ predicate on the "wins" field.
func WinsEQ(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldWins, v))
}

// WinsNEQ applies the NEQ predicate on the "wins" field.
func WinsNEQ(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNEQ(FieldWins, v))
}

// WinsIn applies the In predicate on the "wins" field.
func WinsIn(vs ...int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldIn(FieldWins, vs...))
}

// WinsNotIn applies the NotIn predicate on the "wins" field.
func WinsNotIn(vs ...int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNotIn(FieldWins, vs...))
}

// WinsGT applies the GT predicate on the "wins" field.
func WinsGT(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGT(FieldWins, v))
}

// WinsGTE applies the GTE predicate on the "wins" field.
func WinsGTE(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGTE(FieldWins, v))
}

// WinsLT applies the LT predicate on the "wins" field.
func WinsLT(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLT(FieldWins, v))
}

// WinsLTE applies the LTE predicate on the "wins" field.
func WinsLTE(v int) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLTE(FieldWins, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.PlayerStats {
	return predicate.PlayerStats(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlayerStats) predicate.PlayerStats {
	return predicate.PlayerStats(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlayerStats) predicate.PlayerStats {
	return predicate.PlayerStats(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlayerStats) predicate.PlayerStats {
	return predicate.PlayerStats(sql.NotPredicates(p))
}
