// Code generated by ent, DO NOT EDIT.

package settings

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the settings type in the database.
	Label = "settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGuildID holds the string denoting the guildid field in the database.
	FieldGuildID = "guild_id"
	// FieldBotUpdatesChannelID holds the string denoting the botupdateschannelid field in the database.
	FieldBotUpdatesChannelID = "bot_updates_channel_id"
	// FieldChannelID holds the string denoting the channelid field in the database.
	FieldChannelID = "channel_id"
	// FieldPingRoleID holds the string denoting the pingroleid field in the database.
	FieldPingRoleID = "ping_role_id"
	// FieldPingOnlyNew holds the string denoting the pingonlynew field in the database.
	FieldPingOnlyNew = "ping_only_new"
	// FieldMembersCanStart holds the string denoting the memberscanstart field in the database.
	FieldMembersCanStart = "members_can_start"
	// FieldCooldown holds the string denoting the cooldown field in the database.
	FieldCooldown = "cooldown"
	// FieldEnableBackToBackCooldown holds the string denoting the enablebacktobackcooldown field in the database.
	FieldEnableBackToBackCooldown = "enable_back_to_back_cooldown"
	// FieldBackToBackCooldown holds the string denoting the backtobackcooldown field in the database.
	FieldBackToBackCooldown = "back_to_back_cooldown"
	// FieldInformCooldownAfterGuess holds the string denoting the informcooldownafterguess field in the database.
	FieldInformCooldownAfterGuess = "inform_cooldown_after_guess"
	// FieldFrequency holds the string denoting the frequency field in the database.
	FieldFrequency = "frequency"
	// FieldTimeLimit holds the string denoting the timelimit field in the database.
	FieldTimeLimit = "time_limit"
	// FieldAutoStart holds the string denoting the autostart field in the database.
	FieldAutoStart = "auto_start"
	// FieldStartAfterFirstGuess holds the string denoting the startafterfirstguess field in the database.
	FieldStartAfterFirstGuess = "start_after_first_guess"
	// FieldHints holds the string denoting the hints field in the database.
	FieldHints = "hints"
	// FieldMaxHints holds the string denoting the maxhints field in the database.
	FieldMaxHints = "max_hints"
	// FieldHintsUsed holds the string denoting the hintsused field in the database.
	FieldHintsUsed = "hints_used"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the settings in the database.
	Table = "settings"
)

// Columns holds all SQL columns for settings fields.
var Columns = []string{
	FieldID,
	FieldGuildID,
	FieldBotUpdatesChannelID,
	FieldChannelID,
	FieldPingRoleID,
	FieldPingOnlyNew,
	FieldMembersCanStart,
	FieldCooldown,
	FieldEnableBackToBackCooldown,
	FieldBackToBackCooldown,
	FieldInformCooldownAfterGuess,
	FieldFrequency,
	FieldTimeLimit,
	FieldAutoStart,
	FieldStartAfterFirstGuess,
	FieldHints,
	FieldMaxHints,
	FieldHintsUsed,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPingOnlyNew holds the default value on creation for the "pingOnlyNew" field.
	DefaultPingOnlyNew bool
	// DefaultMembersCanStart holds the default value on creation for the "membersCanStart" field.
	DefaultMembersCanStart bool
	// DefaultCooldown holds the default value on creation for the "cooldown" field.
	DefaultCooldown int
	// DefaultEnableBackToBackCooldown holds the default value on creation for the "enableBackToBackCooldown" field.
	DefaultEnableBackToBackCooldown bool
	// DefaultBackToBackCooldown holds the default value on creation for the "backToBackCooldown" field.
	DefaultBackToBackCooldown int
	// DefaultInformCooldownAfterGuess holds the default value on creation for the "informCooldownAfterGuess" field.
	DefaultInformCooldownAfterGuess bool
	// DefaultFrequency holds the default value on creation for the "frequency" field.
	DefaultFrequency int
	// DefaultTimeLimit holds the default value on creation for the "timeLimit" field.
	DefaultTimeLimit int
	// DefaultAutoStart holds the default value on creation for the "autoStart" field.
	DefaultAutoStart bool
	// DefaultStartAfterFirstGuess holds the default value on creation for the "startAfterFirstGuess" field.
	DefaultStartAfterFirstGuess bool
	// DefaultHints holds the default value on creation for the "hints" field.
	DefaultHints float64
	// DefaultMaxHints holds the default value on creation for the "maxHints" field.
	DefaultMaxHints float64
	// DefaultHintsUsed holds the default value on creation for the "hintsUsed" field.
	DefaultHintsUsed float64
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Settings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGuildID orders the results by the guildID field.
func ByGuildID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGuildID, opts...).ToFunc()
}

// ByBotUpdatesChannelID orders the results by the botUpdatesChannelID field.
func ByBotUpdatesChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBotUpdatesChannelID, opts...).ToFunc()
}

// ByChannelID orders the results by the channelID field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByPingRoleID orders the results by the pingRoleID field.
func ByPingRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPingRoleID, opts...).ToFunc()
}

// ByPingOnlyNew orders the results by the pingOnlyNew field.
func ByPingOnlyNew(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPingOnlyNew, opts...).ToFunc()
}

// ByMembersCanStart orders the results by the membersCanStart field.
func ByMembersCanStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMembersCanStart, opts...).ToFunc()
}

// ByCooldown orders the results by the cooldown field.
func ByCooldown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldown, opts...).ToFunc()
}

// ByEnableBackToBackCooldown orders the results by the enableBackToBackCooldown field.
func ByEnableBackToBackCooldown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnableBackToBackCooldown, opts...).ToFunc()
}

// ByBackToBackCooldown orders the results by the backToBackCooldown field.
func ByBackToBackCooldown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackToBackCooldown, opts...).ToFunc()
}

// ByInformCooldownAfterGuess orders the results by the informCooldownAfterGuess field.
func ByInformCooldownAfterGuess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInformCooldownAfterGuess, opts...).ToFunc()
}

// ByFrequency orders the results by the frequency field.
func ByFrequency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrequency, opts...).ToFunc()
}

// ByTimeLimit orders the results by the timeLimit field.
func ByTimeLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeLimit, opts...).ToFunc()
}

// ByAutoStart orders the results by the autoStart field.
func ByAutoStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoStart, opts...).ToFunc()
}

// ByStartAfterFirstGuess orders the results by the startAfterFirstGuess field.
func ByStartAfterFirstGuess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartAfterFirstGuess, opts...).ToFunc()
}

// ByHints orders the results by the hints field.
func ByHints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHints, opts...).ToFunc()
}

// ByMaxHints orders the results by the maxHints field.
func ByMaxHints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxHints, opts...).ToFunc()
}

// ByHintsUsed orders the results by the hintsUsed field.
func ByHintsUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHintsUsed, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
