// Code generated by ent, DO NOT EDIT.

package settings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"jurien.dev/yugen/koto/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldID, id))
}

// GuildID applies equality check predicate on the "guildID" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldGuildID, v))
}

// ChannelID applies equality check predicate on the "channelID" field. It's identical to ChannelIDEQ.
func ChannelID(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldChannelID, v))
}

// PingRoleID applies equality check predicate on the "pingRoleID" field. It's identical to PingRoleIDEQ.
func PingRoleID(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldPingRoleID, v))
}

// PingOnlyNew applies equality check predicate on the "pingOnlyNew" field. It's identical to PingOnlyNewEQ.
func PingOnlyNew(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldPingOnlyNew, v))
}

// MembersCanStart applies equality check predicate on the "membersCanStart" field. It's identical to MembersCanStartEQ.
func MembersCanStart(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldMembersCanStart, v))
}

// Cooldown applies equality check predicate on the "cooldown" field. It's identical to CooldownEQ.
func Cooldown(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCooldown, v))
}

// EnableBackToBackCooldown applies equality check predicate on the "enableBackToBackCooldown" field. It's identical to EnableBackToBackCooldownEQ.
func EnableBackToBackCooldown(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldEnableBackToBackCooldown, v))
}

// BackToBackCooldown applies equality check predicate on the "backToBackCooldown" field. It's identical to BackToBackCooldownEQ.
func BackToBackCooldown(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldBackToBackCooldown, v))
}

// InformCooldownAfterGuess applies equality check predicate on the "informCooldownAfterGuess" field. It's identical to InformCooldownAfterGuessEQ.
func InformCooldownAfterGuess(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldInformCooldownAfterGuess, v))
}

// Frequency applies equality check predicate on the "frequency" field. It's identical to FrequencyEQ.
func Frequency(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldFrequency, v))
}

// TimeLimit applies equality check predicate on the "timeLimit" field. It's identical to TimeLimitEQ.
func TimeLimit(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldTimeLimit, v))
}

// AutoStart applies equality check predicate on the "autoStart" field. It's identical to AutoStartEQ.
func AutoStart(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldAutoStart, v))
}

// StartAfterFirstGuess applies equality check predicate on the "startAfterFirstGuess" field. It's identical to StartAfterFirstGuessEQ.
func StartAfterFirstGuess(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldStartAfterFirstGuess, v))
}

// Hints applies equality check predicate on the "hints" field. It's identical to HintsEQ.
func Hints(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldHints, v))
}

// MaxHints applies equality check predicate on the "maxHints" field. It's identical to MaxHintsEQ.
func MaxHints(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldMaxHints, v))
}

// HintsUsed applies equality check predicate on the "hintsUsed" field. It's identical to HintsUsedEQ.
func HintsUsed(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldHintsUsed, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUpdatedAt, v))
}

// GuildIDEQ applies the EQ predicate on the "guildID" field.
func GuildIDEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guildID" field.
func GuildIDNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guildID" field.
func GuildIDIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guildID" field.
func GuildIDNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guildID" field.
func GuildIDGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guildID" field.
func GuildIDGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guildID" field.
func GuildIDLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guildID" field.
func GuildIDLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guildID" field.
func GuildIDContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guildID" field.
func GuildIDHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guildID" field.
func GuildIDHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guildID" field.
func GuildIDEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guildID" field.
func GuildIDContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldGuildID, v))
}

// ChannelIDEQ applies the EQ predicate on the "channelID" field.
func ChannelIDEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channelID" field.
func ChannelIDNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channelID" field.
func ChannelIDIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channelID" field.
func ChannelIDNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channelID" field.
func ChannelIDGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channelID" field.
func ChannelIDGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channelID" field.
func ChannelIDLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channelID" field.
func ChannelIDLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDContains applies the Contains predicate on the "channelID" field.
func ChannelIDContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldChannelID, v))
}

// ChannelIDHasPrefix applies the HasPrefix predicate on the "channelID" field.
func ChannelIDHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldChannelID, v))
}

// ChannelIDHasSuffix applies the HasSuffix predicate on the "channelID" field.
func ChannelIDHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldChannelID, v))
}

// ChannelIDIsNil applies the IsNil predicate on the "channelID" field.
func ChannelIDIsNil() predicate.Settings {
	return predicate.Settings(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channelID" field.
func ChannelIDNotNil() predicate.Settings {
	return predicate.Settings(sql.FieldNotNull(FieldChannelID))
}

// ChannelIDEqualFold applies the EqualFold predicate on the "channelID" field.
func ChannelIDEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldChannelID, v))
}

// ChannelIDContainsFold applies the ContainsFold predicate on the "channelID" field.
func ChannelIDContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldChannelID, v))
}

// PingRoleIDEQ applies the EQ predicate on the "pingRoleID" field.
func PingRoleIDEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldPingRoleID, v))
}

// PingRoleIDNEQ applies the NEQ predicate on the "pingRoleID" field.
func PingRoleIDNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldPingRoleID, v))
}

// PingRoleIDIn applies the In predicate on the "pingRoleID" field.
func PingRoleIDIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldPingRoleID, vs...))
}

// PingRoleIDNotIn applies the NotIn predicate on the "pingRoleID" field.
func PingRoleIDNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldPingRoleID, vs...))
}

// PingRoleIDGT applies the GT predicate on the "pingRoleID" field.
func PingRoleIDGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldPingRoleID, v))
}

// PingRoleIDGTE applies the GTE predicate on the "pingRoleID" field.
func PingRoleIDGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldPingRoleID, v))
}

// PingRoleIDLT applies the LT predicate on the "pingRoleID" field.
func PingRoleIDLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldPingRoleID, v))
}

// PingRoleIDLTE applies the LTE predicate on the "pingRoleID" field.
func PingRoleIDLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldPingRoleID, v))
}

// PingRoleIDContains applies the Contains predicate on the "pingRoleID" field.
func PingRoleIDContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldPingRoleID, v))
}

// PingRoleIDHasPrefix applies the HasPrefix predicate on the "pingRoleID" field.
func PingRoleIDHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldPingRoleID, v))
}

// PingRoleIDHasSuffix applies the HasSuffix predicate on the "pingRoleID" field.
func PingRoleIDHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldPingRoleID, v))
}

// PingRoleIDIsNil applies the IsNil predicate on the "pingRoleID" field.
func PingRoleIDIsNil() predicate.Settings {
	return predicate.Settings(sql.FieldIsNull(FieldPingRoleID))
}

// PingRoleIDNotNil applies the NotNil predicate on the "pingRoleID" field.
func PingRoleIDNotNil() predicate.Settings {
	return predicate.Settings(sql.FieldNotNull(FieldPingRoleID))
}

// PingRoleIDEqualFold applies the EqualFold predicate on the "pingRoleID" field.
func PingRoleIDEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldPingRoleID, v))
}

// PingRoleIDContainsFold applies the ContainsFold predicate on the "pingRoleID" field.
func PingRoleIDContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldPingRoleID, v))
}

// PingOnlyNewEQ applies the EQ predicate on the "pingOnlyNew" field.
func PingOnlyNewEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldPingOnlyNew, v))
}

// PingOnlyNewNEQ applies the NEQ predicate on the "pingOnlyNew" field.
func PingOnlyNewNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldPingOnlyNew, v))
}

// MembersCanStartEQ applies the EQ predicate on the "membersCanStart" field.
func MembersCanStartEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldMembersCanStart, v))
}

// MembersCanStartNEQ applies the NEQ predicate on the "membersCanStart" field.
func MembersCanStartNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldMembersCanStart, v))
}

// CooldownEQ applies the EQ predicate on the "cooldown" field.
func CooldownEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCooldown, v))
}

// CooldownNEQ applies the NEQ predicate on the "cooldown" field.
func CooldownNEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldCooldown, v))
}

// CooldownIn applies the In predicate on the "cooldown" field.
func CooldownIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldCooldown, vs...))
}

// CooldownNotIn applies the NotIn predicate on the "cooldown" field.
func CooldownNotIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldCooldown, vs...))
}

// CooldownGT applies the GT predicate on the "cooldown" field.
func CooldownGT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldCooldown, v))
}

// CooldownGTE applies the GTE predicate on the "cooldown" field.
func CooldownGTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldCooldown, v))
}

// CooldownLT applies the LT predicate on the "cooldown" field.
func CooldownLT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldCooldown, v))
}

// CooldownLTE applies the LTE predicate on the "cooldown" field.
func CooldownLTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldCooldown, v))
}

// EnableBackToBackCooldownEQ applies the EQ predicate on the "enableBackToBackCooldown" field.
func EnableBackToBackCooldownEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldEnableBackToBackCooldown, v))
}

// EnableBackToBackCooldownNEQ applies the NEQ predicate on the "enableBackToBackCooldown" field.
func EnableBackToBackCooldownNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldEnableBackToBackCooldown, v))
}

// BackToBackCooldownEQ applies the EQ predicate on the "backToBackCooldown" field.
func BackToBackCooldownEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldBackToBackCooldown, v))
}

// BackToBackCooldownNEQ applies the NEQ predicate on the "backToBackCooldown" field.
func BackToBackCooldownNEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldBackToBackCooldown, v))
}

// BackToBackCooldownIn applies the In predicate on the "backToBackCooldown" field.
func BackToBackCooldownIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldBackToBackCooldown, vs...))
}

// BackToBackCooldownNotIn applies the NotIn predicate on the "backToBackCooldown" field.
func BackToBackCooldownNotIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldBackToBackCooldown, vs...))
}

// BackToBackCooldownGT applies the GT predicate on the "backToBackCooldown" field.
func BackToBackCooldownGT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldBackToBackCooldown, v))
}

// BackToBackCooldownGTE applies the GTE predicate on the "backToBackCooldown" field.
func BackToBackCooldownGTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldBackToBackCooldown, v))
}

// BackToBackCooldownLT applies the LT predicate on the "backToBackCooldown" field.
func BackToBackCooldownLT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldBackToBackCooldown, v))
}

// BackToBackCooldownLTE applies the LTE predicate on the "backToBackCooldown" field.
func BackToBackCooldownLTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldBackToBackCooldown, v))
}

// InformCooldownAfterGuessEQ applies the EQ predicate on the "informCooldownAfterGuess" field.
func InformCooldownAfterGuessEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldInformCooldownAfterGuess, v))
}

// InformCooldownAfterGuessNEQ applies the NEQ predicate on the "informCooldownAfterGuess" field.
func InformCooldownAfterGuessNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldInformCooldownAfterGuess, v))
}

// FrequencyEQ applies the EQ predicate on the "frequency" field.
func FrequencyEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldFrequency, v))
}

// FrequencyNEQ applies the NEQ predicate on the "frequency" field.
func FrequencyNEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldFrequency, v))
}

// FrequencyIn applies the In predicate on the "frequency" field.
func FrequencyIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldFrequency, vs...))
}

// FrequencyNotIn applies the NotIn predicate on the "frequency" field.
func FrequencyNotIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldFrequency, vs...))
}

// FrequencyGT applies the GT predicate on the "frequency" field.
func FrequencyGT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldFrequency, v))
}

// FrequencyGTE applies the GTE predicate on the "frequency" field.
func FrequencyGTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldFrequency, v))
}

// FrequencyLT applies the LT predicate on the "frequency" field.
func FrequencyLT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldFrequency, v))
}

// FrequencyLTE applies the LTE predicate on the "frequency" field.
func FrequencyLTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldFrequency, v))
}

// TimeLimitEQ applies the EQ predicate on the "timeLimit" field.
func TimeLimitEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldTimeLimit, v))
}

// TimeLimitNEQ applies the NEQ predicate on the "timeLimit" field.
func TimeLimitNEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldTimeLimit, v))
}

// TimeLimitIn applies the In predicate on the "timeLimit" field.
func TimeLimitIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldTimeLimit, vs...))
}

// TimeLimitNotIn applies the NotIn predicate on the "timeLimit" field.
func TimeLimitNotIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldTimeLimit, vs...))
}

// TimeLimitGT applies the GT predicate on the "timeLimit" field.
func TimeLimitGT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldTimeLimit, v))
}

// TimeLimitGTE applies the GTE predicate on the "timeLimit" field.
func TimeLimitGTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldTimeLimit, v))
}

// TimeLimitLT applies the LT predicate on the "timeLimit" field.
func TimeLimitLT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldTimeLimit, v))
}

// TimeLimitLTE applies the LTE predicate on the "timeLimit" field.
func TimeLimitLTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldTimeLimit, v))
}

// AutoStartEQ applies the EQ predicate on the "autoStart" field.
func AutoStartEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldAutoStart, v))
}

// AutoStartNEQ applies the NEQ predicate on the "autoStart" field.
func AutoStartNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldAutoStart, v))
}

// StartAfterFirstGuessEQ applies the EQ predicate on the "startAfterFirstGuess" field.
func StartAfterFirstGuessEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldStartAfterFirstGuess, v))
}

// StartAfterFirstGuessNEQ applies the NEQ predicate on the "startAfterFirstGuess" field.
func StartAfterFirstGuessNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldStartAfterFirstGuess, v))
}

// HintsEQ applies the EQ predicate on the "hints" field.
func HintsEQ(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldHints, v))
}

// HintsNEQ applies the NEQ predicate on the "hints" field.
func HintsNEQ(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldHints, v))
}

// HintsIn applies the In predicate on the "hints" field.
func HintsIn(vs ...float64) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldHints, vs...))
}

// HintsNotIn applies the NotIn predicate on the "hints" field.
func HintsNotIn(vs ...float64) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldHints, vs...))
}

// HintsGT applies the GT predicate on the "hints" field.
func HintsGT(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldHints, v))
}

// HintsGTE applies the GTE predicate on the "hints" field.
func HintsGTE(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldHints, v))
}

// HintsLT applies the LT predicate on the "hints" field.
func HintsLT(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldHints, v))
}

// HintsLTE applies the LTE predicate on the "hints" field.
func HintsLTE(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldHints, v))
}

// MaxHintsEQ applies the EQ predicate on the "maxHints" field.
func MaxHintsEQ(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldMaxHints, v))
}

// MaxHintsNEQ applies the NEQ predicate on the "maxHints" field.
func MaxHintsNEQ(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldMaxHints, v))
}

// MaxHintsIn applies the In predicate on the "maxHints" field.
func MaxHintsIn(vs ...float64) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldMaxHints, vs...))
}

// MaxHintsNotIn applies the NotIn predicate on the "maxHints" field.
func MaxHintsNotIn(vs ...float64) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldMaxHints, vs...))
}

// MaxHintsGT applies the GT predicate on the "maxHints" field.
func MaxHintsGT(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldMaxHints, v))
}

// MaxHintsGTE applies the GTE predicate on the "maxHints" field.
func MaxHintsGTE(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldMaxHints, v))
}

// MaxHintsLT applies the LT predicate on the "maxHints" field.
func MaxHintsLT(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldMaxHints, v))
}

// MaxHintsLTE applies the LTE predicate on the "maxHints" field.
func MaxHintsLTE(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldMaxHints, v))
}

// HintsUsedEQ applies the EQ predicate on the "hintsUsed" field.
func HintsUsedEQ(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldHintsUsed, v))
}

// HintsUsedNEQ applies the NEQ predicate on the "hintsUsed" field.
func HintsUsedNEQ(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldHintsUsed, v))
}

// HintsUsedIn applies the In predicate on the "hintsUsed" field.
func HintsUsedIn(vs ...float64) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldHintsUsed, vs...))
}

// HintsUsedNotIn applies the NotIn predicate on the "hintsUsed" field.
func HintsUsedNotIn(vs ...float64) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldHintsUsed, vs...))
}

// HintsUsedGT applies the GT predicate on the "hintsUsed" field.
func HintsUsedGT(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldHintsUsed, v))
}

// HintsUsedGTE applies the GTE predicate on the "hintsUsed" field.
func HintsUsedGTE(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldHintsUsed, v))
}

// HintsUsedLT applies the LT predicate on the "hintsUsed" field.
func HintsUsedLT(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldHintsUsed, v))
}

// HintsUsedLTE applies the LTE predicate on the "hintsUsed" field.
func HintsUsedLTE(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldHintsUsed, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.NotPredicates(p))
}
