// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/kazu/internal/ent/playersaves"
)

// PlayerSavesCreate is the builder for creating a PlayerSaves entity.
type PlayerSavesCreate struct {
	config
	mutation *PlayerSavesMutation
	hooks    []Hook
}

// SetUserID sets the "userID" field.
func (psc *PlayerSavesCreate) SetUserID(s string) *PlayerSavesCreate {
	psc.mutation.SetUserID(s)
	return psc
}

// SetSaves sets the "saves" field.
func (psc *PlayerSavesCreate) SetSaves(f float64) *PlayerSavesCreate {
	psc.mutation.SetSaves(f)
	return psc
}

// SetNillableSaves sets the "saves" field if the given value is not nil.
func (psc *PlayerSavesCreate) SetNillableSaves(f *float64) *PlayerSavesCreate {
	if f != nil {
		psc.SetSaves(*f)
	}
	return psc
}

// SetMaxSaves sets the "maxSaves" field.
func (psc *PlayerSavesCreate) SetMaxSaves(f float64) *PlayerSavesCreate {
	psc.mutation.SetMaxSaves(f)
	return psc
}

// SetNillableMaxSaves sets the "maxSaves" field if the given value is not nil.
func (psc *PlayerSavesCreate) SetNillableMaxSaves(f *float64) *PlayerSavesCreate {
	if f != nil {
		psc.SetMaxSaves(*f)
	}
	return psc
}

// SetLastVoteTime sets the "lastVoteTime" field.
func (psc *PlayerSavesCreate) SetLastVoteTime(t time.Time) *PlayerSavesCreate {
	psc.mutation.SetLastVoteTime(t)
	return psc
}

// SetNillableLastVoteTime sets the "lastVoteTime" field if the given value is not nil.
func (psc *PlayerSavesCreate) SetNillableLastVoteTime(t *time.Time) *PlayerSavesCreate {
	if t != nil {
		psc.SetLastVoteTime(*t)
	}
	return psc
}

// SetCreatedAt sets the "createdAt" field.
func (psc *PlayerSavesCreate) SetCreatedAt(t time.Time) *PlayerSavesCreate {
	psc.mutation.SetCreatedAt(t)
	return psc
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (psc *PlayerSavesCreate) SetNillableCreatedAt(t *time.Time) *PlayerSavesCreate {
	if t != nil {
		psc.SetCreatedAt(*t)
	}
	return psc
}

// SetUpdatedAt sets the "updatedAt" field.
func (psc *PlayerSavesCreate) SetUpdatedAt(t time.Time) *PlayerSavesCreate {
	psc.mutation.SetUpdatedAt(t)
	return psc
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (psc *PlayerSavesCreate) SetNillableUpdatedAt(t *time.Time) *PlayerSavesCreate {
	if t != nil {
		psc.SetUpdatedAt(*t)
	}
	return psc
}

// Mutation returns the PlayerSavesMutation object of the builder.
func (psc *PlayerSavesCreate) Mutation() *PlayerSavesMutation {
	return psc.mutation
}

// Save creates the PlayerSaves in the database.
func (psc *PlayerSavesCreate) Save(ctx context.Context) (*PlayerSaves, error) {
	psc.defaults()
	return withHooks(ctx, psc.sqlSave, psc.mutation, psc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (psc *PlayerSavesCreate) SaveX(ctx context.Context) *PlayerSaves {
	v, err := psc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (psc *PlayerSavesCreate) Exec(ctx context.Context) error {
	_, err := psc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psc *PlayerSavesCreate) ExecX(ctx context.Context) {
	if err := psc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psc *PlayerSavesCreate) defaults() {
	if _, ok := psc.mutation.Saves(); !ok {
		v := playersaves.DefaultSaves
		psc.mutation.SetSaves(v)
	}
	if _, ok := psc.mutation.MaxSaves(); !ok {
		v := playersaves.DefaultMaxSaves
		psc.mutation.SetMaxSaves(v)
	}
	if _, ok := psc.mutation.CreatedAt(); !ok {
		v := playersaves.DefaultCreatedAt()
		psc.mutation.SetCreatedAt(v)
	}
	if _, ok := psc.mutation.UpdatedAt(); !ok {
		v := playersaves.DefaultUpdatedAt()
		psc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psc *PlayerSavesCreate) check() error {
	if _, ok := psc.mutation.UserID(); !ok {
		return &ValidationError{Name: "userID", err: errors.New(`ent: missing required field "PlayerSaves.userID"`)}
	}
	if _, ok := psc.mutation.Saves(); !ok {
		return &ValidationError{Name: "saves", err: errors.New(`ent: missing required field "PlayerSaves.saves"`)}
	}
	if _, ok := psc.mutation.MaxSaves(); !ok {
		return &ValidationError{Name: "maxSaves", err: errors.New(`ent: missing required field "PlayerSaves.maxSaves"`)}
	}
	if _, ok := psc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "PlayerSaves.createdAt"`)}
	}
	if _, ok := psc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "PlayerSaves.updatedAt"`)}
	}
	return nil
}

func (psc *PlayerSavesCreate) sqlSave(ctx context.Context) (*PlayerSaves, error) {
	if err := psc.check(); err != nil {
		return nil, err
	}
	_node, _spec := psc.createSpec()
	if err := sqlgraph.CreateNode(ctx, psc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	psc.mutation.id = &_node.ID
	psc.mutation.done = true
	return _node, nil
}

func (psc *PlayerSavesCreate) createSpec() (*PlayerSaves, *sqlgraph.CreateSpec) {
	var (
		_node = &PlayerSaves{config: psc.config}
		_spec = sqlgraph.NewCreateSpec(playersaves.Table, sqlgraph.NewFieldSpec(playersaves.FieldID, field.TypeInt))
	)
	if value, ok := psc.mutation.UserID(); ok {
		_spec.SetField(playersaves.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := psc.mutation.Saves(); ok {
		_spec.SetField(playersaves.FieldSaves, field.TypeFloat64, value)
		_node.Saves = value
	}
	if value, ok := psc.mutation.MaxSaves(); ok {
		_spec.SetField(playersaves.FieldMaxSaves, field.TypeFloat64, value)
		_node.MaxSaves = value
	}
	if value, ok := psc.mutation.LastVoteTime(); ok {
		_spec.SetField(playersaves.FieldLastVoteTime, field.TypeTime, value)
		_node.LastVoteTime = &value
	}
	if value, ok := psc.mutation.CreatedAt(); ok {
		_spec.SetField(playersaves.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := psc.mutation.UpdatedAt(); ok {
		_spec.SetField(playersaves.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PlayerSavesCreateBulk is the builder for creating many PlayerSaves entities in bulk.
type PlayerSavesCreateBulk struct {
	config
	err      error
	builders []*PlayerSavesCreate
}

// Save creates the PlayerSaves entities in the database.
func (pscb *PlayerSavesCreateBulk) Save(ctx context.Context) ([]*PlayerSaves, error) {
	if pscb.err != nil {
		return nil, pscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pscb.builders))
	nodes := make([]*PlayerSaves, len(pscb.builders))
	mutators := make([]Mutator, len(pscb.builders))
	for i := range pscb.builders {
		func(i int, root context.Context) {
			builder := pscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayerSavesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pscb *PlayerSavesCreateBulk) SaveX(ctx context.Context) []*PlayerSaves {
	v, err := pscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pscb *PlayerSavesCreateBulk) Exec(ctx context.Context) error {
	_, err := pscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pscb *PlayerSavesCreateBulk) ExecX(ctx context.Context) {
	if err := pscb.Exec(ctx); err != nil {
		panic(err)
	}
}
