// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/kazu/internal/ent/playerstats"
)

// PlayerStatsCreate is the builder for creating a PlayerStats entity.
type PlayerStatsCreate struct {
	config
	mutation *PlayerStatsMutation
	hooks    []Hook
}

// SetUserID sets the "userID" field.
func (psc *PlayerStatsCreate) SetUserID(s string) *PlayerStatsCreate {
	psc.mutation.SetUserID(s)
	return psc
}

// SetGuildID sets the "guildID" field.
func (psc *PlayerStatsCreate) SetGuildID(s string) *PlayerStatsCreate {
	psc.mutation.SetGuildID(s)
	return psc
}

// SetInGuild sets the "inGuild" field.
func (psc *PlayerStatsCreate) SetInGuild(b bool) *PlayerStatsCreate {
	psc.mutation.SetInGuild(b)
	return psc
}

// SetNillableInGuild sets the "inGuild" field if the given value is not nil.
func (psc *PlayerStatsCreate) SetNillableInGuild(b *bool) *PlayerStatsCreate {
	if b != nil {
		psc.SetInGuild(*b)
	}
	return psc
}

// SetPoints sets the "points" field.
func (psc *PlayerStatsCreate) SetPoints(i int) *PlayerStatsCreate {
	psc.mutation.SetPoints(i)
	return psc
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (psc *PlayerStatsCreate) SetNillablePoints(i *int) *PlayerStatsCreate {
	if i != nil {
		psc.SetPoints(*i)
	}
	return psc
}

// SetCreatedAt sets the "createdAt" field.
func (psc *PlayerStatsCreate) SetCreatedAt(t time.Time) *PlayerStatsCreate {
	psc.mutation.SetCreatedAt(t)
	return psc
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (psc *PlayerStatsCreate) SetNillableCreatedAt(t *time.Time) *PlayerStatsCreate {
	if t != nil {
		psc.SetCreatedAt(*t)
	}
	return psc
}

// SetUpdatedAt sets the "updatedAt" field.
func (psc *PlayerStatsCreate) SetUpdatedAt(t time.Time) *PlayerStatsCreate {
	psc.mutation.SetUpdatedAt(t)
	return psc
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (psc *PlayerStatsCreate) SetNillableUpdatedAt(t *time.Time) *PlayerStatsCreate {
	if t != nil {
		psc.SetUpdatedAt(*t)
	}
	return psc
}

// Mutation returns the PlayerStatsMutation object of the builder.
func (psc *PlayerStatsCreate) Mutation() *PlayerStatsMutation {
	return psc.mutation
}

// Save creates the PlayerStats in the database.
func (psc *PlayerStatsCreate) Save(ctx context.Context) (*PlayerStats, error) {
	psc.defaults()
	return withHooks(ctx, psc.sqlSave, psc.mutation, psc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (psc *PlayerStatsCreate) SaveX(ctx context.Context) *PlayerStats {
	v, err := psc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (psc *PlayerStatsCreate) Exec(ctx context.Context) error {
	_, err := psc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psc *PlayerStatsCreate) ExecX(ctx context.Context) {
	if err := psc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psc *PlayerStatsCreate) defaults() {
	if _, ok := psc.mutation.InGuild(); !ok {
		v := playerstats.DefaultInGuild
		psc.mutation.SetInGuild(v)
	}
	if _, ok := psc.mutation.Points(); !ok {
		v := playerstats.DefaultPoints
		psc.mutation.SetPoints(v)
	}
	if _, ok := psc.mutation.CreatedAt(); !ok {
		v := playerstats.DefaultCreatedAt()
		psc.mutation.SetCreatedAt(v)
	}
	if _, ok := psc.mutation.UpdatedAt(); !ok {
		v := playerstats.DefaultUpdatedAt()
		psc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psc *PlayerStatsCreate) check() error {
	if _, ok := psc.mutation.UserID(); !ok {
		return &ValidationError{Name: "userID", err: errors.New(`ent: missing required field "PlayerStats.userID"`)}
	}
	if _, ok := psc.mutation.GuildID(); !ok {
		return &ValidationError{Name: "guildID", err: errors.New(`ent: missing required field "PlayerStats.guildID"`)}
	}
	if _, ok := psc.mutation.InGuild(); !ok {
		return &ValidationError{Name: "inGuild", err: errors.New(`ent: missing required field "PlayerStats.inGuild"`)}
	}
	if _, ok := psc.mutation.Points(); !ok {
		return &ValidationError{Name: "points", err: errors.New(`ent: missing required field "PlayerStats.points"`)}
	}
	if _, ok := psc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "PlayerStats.createdAt"`)}
	}
	if _, ok := psc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "PlayerStats.updatedAt"`)}
	}
	return nil
}

func (psc *PlayerStatsCreate) sqlSave(ctx context.Context) (*PlayerStats, error) {
	if err := psc.check(); err != nil {
		return nil, err
	}
	_node, _spec := psc.createSpec()
	if err := sqlgraph.CreateNode(ctx, psc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	psc.mutation.id = &_node.ID
	psc.mutation.done = true
	return _node, nil
}

func (psc *PlayerStatsCreate) createSpec() (*PlayerStats, *sqlgraph.CreateSpec) {
	var (
		_node = &PlayerStats{config: psc.config}
		_spec = sqlgraph.NewCreateSpec(playerstats.Table, sqlgraph.NewFieldSpec(playerstats.FieldID, field.TypeInt))
	)
	if value, ok := psc.mutation.UserID(); ok {
		_spec.SetField(playerstats.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := psc.mutation.GuildID(); ok {
		_spec.SetField(playerstats.FieldGuildID, field.TypeString, value)
		_node.GuildID = value
	}
	if value, ok := psc.mutation.InGuild(); ok {
		_spec.SetField(playerstats.FieldInGuild, field.TypeBool, value)
		_node.InGuild = value
	}
	if value, ok := psc.mutation.Points(); ok {
		_spec.SetField(playerstats.FieldPoints, field.TypeInt, value)
		_node.Points = value
	}
	if value, ok := psc.mutation.CreatedAt(); ok {
		_spec.SetField(playerstats.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := psc.mutation.UpdatedAt(); ok {
		_spec.SetField(playerstats.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PlayerStatsCreateBulk is the builder for creating many PlayerStats entities in bulk.
type PlayerStatsCreateBulk struct {
	config
	err      error
	builders []*PlayerStatsCreate
}

// Save creates the PlayerStats entities in the database.
func (pscb *PlayerStatsCreateBulk) Save(ctx context.Context) ([]*PlayerStats, error) {
	if pscb.err != nil {
		return nil, pscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pscb.builders))
	nodes := make([]*PlayerStats, len(pscb.builders))
	mutators := make([]Mutator, len(pscb.builders))
	for i := range pscb.builders {
		func(i int, root context.Context) {
			builder := pscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayerStatsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pscb *PlayerStatsCreateBulk) SaveX(ctx context.Context) []*PlayerStats {
	v, err := pscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pscb *PlayerStatsCreateBulk) Exec(ctx context.Context) error {
	_, err := pscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pscb *PlayerStatsCreateBulk) ExecX(ctx context.Context) {
	if err := pscb.Exec(ctx); err != nil {
		panic(err)
	}
}
