// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/kazu/internal/ent/predicate"
	"jurien.dev/yugen/kazu/internal/ent/settings"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (su *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetGuildID sets the "guildID" field.
func (su *SettingsUpdate) SetGuildID(s string) *SettingsUpdate {
	su.mutation.SetGuildID(s)
	return su
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableGuildID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetGuildID(*s)
	}
	return su
}

// SetChannelID sets the "channelID" field.
func (su *SettingsUpdate) SetChannelID(s string) *SettingsUpdate {
	su.mutation.SetChannelID(s)
	return su
}

// SetNillableChannelID sets the "channelID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableChannelID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetChannelID(*s)
	}
	return su
}

// ClearChannelID clears the value of the "channelID" field.
func (su *SettingsUpdate) ClearChannelID() *SettingsUpdate {
	su.mutation.ClearChannelID()
	return su
}

// SetCooldown sets the "cooldown" field.
func (su *SettingsUpdate) SetCooldown(i int) *SettingsUpdate {
	su.mutation.ResetCooldown()
	su.mutation.SetCooldown(i)
	return su
}

// SetNillableCooldown sets the "cooldown" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableCooldown(i *int) *SettingsUpdate {
	if i != nil {
		su.SetCooldown(*i)
	}
	return su
}

// AddCooldown adds i to the "cooldown" field.
func (su *SettingsUpdate) AddCooldown(i int) *SettingsUpdate {
	su.mutation.AddCooldown(i)
	return su
}

// SetMath sets the "math" field.
func (su *SettingsUpdate) SetMath(b bool) *SettingsUpdate {
	su.mutation.SetMath(b)
	return su
}

// SetNillableMath sets the "math" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableMath(b *bool) *SettingsUpdate {
	if b != nil {
		su.SetMath(*b)
	}
	return su
}

// SetShameRoleID sets the "shameRoleID" field.
func (su *SettingsUpdate) SetShameRoleID(s string) *SettingsUpdate {
	su.mutation.SetShameRoleID(s)
	return su
}

// SetNillableShameRoleID sets the "shameRoleID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableShameRoleID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetShameRoleID(*s)
	}
	return su
}

// ClearShameRoleID clears the value of the "shameRoleID" field.
func (su *SettingsUpdate) ClearShameRoleID() *SettingsUpdate {
	su.mutation.ClearShameRoleID()
	return su
}

// SetRemoveShameRoleAfterHighscore sets the "removeShameRoleAfterHighscore" field.
func (su *SettingsUpdate) SetRemoveShameRoleAfterHighscore(b bool) *SettingsUpdate {
	su.mutation.SetRemoveShameRoleAfterHighscore(b)
	return su
}

// SetNillableRemoveShameRoleAfterHighscore sets the "removeShameRoleAfterHighscore" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableRemoveShameRoleAfterHighscore(b *bool) *SettingsUpdate {
	if b != nil {
		su.SetRemoveShameRoleAfterHighscore(*b)
	}
	return su
}

// SetLastShameUserID sets the "lastShameUserID" field.
func (su *SettingsUpdate) SetLastShameUserID(s string) *SettingsUpdate {
	su.mutation.SetLastShameUserID(s)
	return su
}

// SetNillableLastShameUserID sets the "lastShameUserID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableLastShameUserID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetLastShameUserID(*s)
	}
	return su
}

// ClearLastShameUserID clears the value of the "lastShameUserID" field.
func (su *SettingsUpdate) ClearLastShameUserID() *SettingsUpdate {
	su.mutation.ClearLastShameUserID()
	return su
}

// SetHighscore sets the "highscore" field.
func (su *SettingsUpdate) SetHighscore(i int) *SettingsUpdate {
	su.mutation.ResetHighscore()
	su.mutation.SetHighscore(i)
	return su
}

// SetNillableHighscore sets the "highscore" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableHighscore(i *int) *SettingsUpdate {
	if i != nil {
		su.SetHighscore(*i)
	}
	return su
}

// AddHighscore adds i to the "highscore" field.
func (su *SettingsUpdate) AddHighscore(i int) *SettingsUpdate {
	su.mutation.AddHighscore(i)
	return su
}

// SetHighscoreDate sets the "highscoreDate" field.
func (su *SettingsUpdate) SetHighscoreDate(t time.Time) *SettingsUpdate {
	su.mutation.SetHighscoreDate(t)
	return su
}

// SetNillableHighscoreDate sets the "highscoreDate" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableHighscoreDate(t *time.Time) *SettingsUpdate {
	if t != nil {
		su.SetHighscoreDate(*t)
	}
	return su
}

// ClearHighscoreDate clears the value of the "highscoreDate" field.
func (su *SettingsUpdate) ClearHighscoreDate() *SettingsUpdate {
	su.mutation.ClearHighscoreDate()
	return su
}

// SetSaves sets the "saves" field.
func (su *SettingsUpdate) SetSaves(f float64) *SettingsUpdate {
	su.mutation.ResetSaves()
	su.mutation.SetSaves(f)
	return su
}

// SetNillableSaves sets the "saves" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableSaves(f *float64) *SettingsUpdate {
	if f != nil {
		su.SetSaves(*f)
	}
	return su
}

// AddSaves adds f to the "saves" field.
func (su *SettingsUpdate) AddSaves(f float64) *SettingsUpdate {
	su.mutation.AddSaves(f)
	return su
}

// SetMaxSaves sets the "maxSaves" field.
func (su *SettingsUpdate) SetMaxSaves(f float64) *SettingsUpdate {
	su.mutation.ResetMaxSaves()
	su.mutation.SetMaxSaves(f)
	return su
}

// SetNillableMaxSaves sets the "maxSaves" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableMaxSaves(f *float64) *SettingsUpdate {
	if f != nil {
		su.SetMaxSaves(*f)
	}
	return su
}

// AddMaxSaves adds f to the "maxSaves" field.
func (su *SettingsUpdate) AddMaxSaves(f float64) *SettingsUpdate {
	su.mutation.AddMaxSaves(f)
	return su
}

// SetSavesUsed sets the "savesUsed" field.
func (su *SettingsUpdate) SetSavesUsed(f float64) *SettingsUpdate {
	su.mutation.ResetSavesUsed()
	su.mutation.SetSavesUsed(f)
	return su
}

// SetNillableSavesUsed sets the "savesUsed" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableSavesUsed(f *float64) *SettingsUpdate {
	if f != nil {
		su.SetSavesUsed(*f)
	}
	return su
}

// AddSavesUsed adds f to the "savesUsed" field.
func (su *SettingsUpdate) AddSavesUsed(f float64) *SettingsUpdate {
	su.mutation.AddSavesUsed(f)
	return su
}

// SetUpdatedAt sets the "updatedAt" field.
func (su *SettingsUpdate) SetUpdatedAt(t time.Time) *SettingsUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// Mutation returns the SettingsMutation object of the builder.
func (su *SettingsUpdate) Mutation() *SettingsMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SettingsUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SettingsUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SettingsUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

func (su *SettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.GuildID(); ok {
		_spec.SetField(settings.FieldGuildID, field.TypeString, value)
	}
	if value, ok := su.mutation.ChannelID(); ok {
		_spec.SetField(settings.FieldChannelID, field.TypeString, value)
	}
	if su.mutation.ChannelIDCleared() {
		_spec.ClearField(settings.FieldChannelID, field.TypeString)
	}
	if value, ok := su.mutation.Cooldown(); ok {
		_spec.SetField(settings.FieldCooldown, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedCooldown(); ok {
		_spec.AddField(settings.FieldCooldown, field.TypeInt, value)
	}
	if value, ok := su.mutation.Math(); ok {
		_spec.SetField(settings.FieldMath, field.TypeBool, value)
	}
	if value, ok := su.mutation.ShameRoleID(); ok {
		_spec.SetField(settings.FieldShameRoleID, field.TypeString, value)
	}
	if su.mutation.ShameRoleIDCleared() {
		_spec.ClearField(settings.FieldShameRoleID, field.TypeString)
	}
	if value, ok := su.mutation.RemoveShameRoleAfterHighscore(); ok {
		_spec.SetField(settings.FieldRemoveShameRoleAfterHighscore, field.TypeBool, value)
	}
	if value, ok := su.mutation.LastShameUserID(); ok {
		_spec.SetField(settings.FieldLastShameUserID, field.TypeString, value)
	}
	if su.mutation.LastShameUserIDCleared() {
		_spec.ClearField(settings.FieldLastShameUserID, field.TypeString)
	}
	if value, ok := su.mutation.Highscore(); ok {
		_spec.SetField(settings.FieldHighscore, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedHighscore(); ok {
		_spec.AddField(settings.FieldHighscore, field.TypeInt, value)
	}
	if value, ok := su.mutation.HighscoreDate(); ok {
		_spec.SetField(settings.FieldHighscoreDate, field.TypeTime, value)
	}
	if su.mutation.HighscoreDateCleared() {
		_spec.ClearField(settings.FieldHighscoreDate, field.TypeTime)
	}
	if value, ok := su.mutation.Saves(); ok {
		_spec.SetField(settings.FieldSaves, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedSaves(); ok {
		_spec.AddField(settings.FieldSaves, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.MaxSaves(); ok {
		_spec.SetField(settings.FieldMaxSaves, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedMaxSaves(); ok {
		_spec.AddField(settings.FieldMaxSaves, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.SavesUsed(); ok {
		_spec.SetField(settings.FieldSavesUsed, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedSavesUsed(); ok {
		_spec.AddField(settings.FieldSavesUsed, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetGuildID sets the "guildID" field.
func (suo *SettingsUpdateOne) SetGuildID(s string) *SettingsUpdateOne {
	suo.mutation.SetGuildID(s)
	return suo
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableGuildID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetGuildID(*s)
	}
	return suo
}

// SetChannelID sets the "channelID" field.
func (suo *SettingsUpdateOne) SetChannelID(s string) *SettingsUpdateOne {
	suo.mutation.SetChannelID(s)
	return suo
}

// SetNillableChannelID sets the "channelID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableChannelID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetChannelID(*s)
	}
	return suo
}

// ClearChannelID clears the value of the "channelID" field.
func (suo *SettingsUpdateOne) ClearChannelID() *SettingsUpdateOne {
	suo.mutation.ClearChannelID()
	return suo
}

// SetCooldown sets the "cooldown" field.
func (suo *SettingsUpdateOne) SetCooldown(i int) *SettingsUpdateOne {
	suo.mutation.ResetCooldown()
	suo.mutation.SetCooldown(i)
	return suo
}

// SetNillableCooldown sets the "cooldown" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableCooldown(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetCooldown(*i)
	}
	return suo
}

// AddCooldown adds i to the "cooldown" field.
func (suo *SettingsUpdateOne) AddCooldown(i int) *SettingsUpdateOne {
	suo.mutation.AddCooldown(i)
	return suo
}

// SetMath sets the "math" field.
func (suo *SettingsUpdateOne) SetMath(b bool) *SettingsUpdateOne {
	suo.mutation.SetMath(b)
	return suo
}

// SetNillableMath sets the "math" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableMath(b *bool) *SettingsUpdateOne {
	if b != nil {
		suo.SetMath(*b)
	}
	return suo
}

// SetShameRoleID sets the "shameRoleID" field.
func (suo *SettingsUpdateOne) SetShameRoleID(s string) *SettingsUpdateOne {
	suo.mutation.SetShameRoleID(s)
	return suo
}

// SetNillableShameRoleID sets the "shameRoleID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableShameRoleID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetShameRoleID(*s)
	}
	return suo
}

// ClearShameRoleID clears the value of the "shameRoleID" field.
func (suo *SettingsUpdateOne) ClearShameRoleID() *SettingsUpdateOne {
	suo.mutation.ClearShameRoleID()
	return suo
}

// SetRemoveShameRoleAfterHighscore sets the "removeShameRoleAfterHighscore" field.
func (suo *SettingsUpdateOne) SetRemoveShameRoleAfterHighscore(b bool) *SettingsUpdateOne {
	suo.mutation.SetRemoveShameRoleAfterHighscore(b)
	return suo
}

// SetNillableRemoveShameRoleAfterHighscore sets the "removeShameRoleAfterHighscore" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableRemoveShameRoleAfterHighscore(b *bool) *SettingsUpdateOne {
	if b != nil {
		suo.SetRemoveShameRoleAfterHighscore(*b)
	}
	return suo
}

// SetLastShameUserID sets the "lastShameUserID" field.
func (suo *SettingsUpdateOne) SetLastShameUserID(s string) *SettingsUpdateOne {
	suo.mutation.SetLastShameUserID(s)
	return suo
}

// SetNillableLastShameUserID sets the "lastShameUserID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableLastShameUserID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetLastShameUserID(*s)
	}
	return suo
}

// ClearLastShameUserID clears the value of the "lastShameUserID" field.
func (suo *SettingsUpdateOne) ClearLastShameUserID() *SettingsUpdateOne {
	suo.mutation.ClearLastShameUserID()
	return suo
}

// SetHighscore sets the "highscore" field.
func (suo *SettingsUpdateOne) SetHighscore(i int) *SettingsUpdateOne {
	suo.mutation.ResetHighscore()
	suo.mutation.SetHighscore(i)
	return suo
}

// SetNillableHighscore sets the "highscore" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableHighscore(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetHighscore(*i)
	}
	return suo
}

// AddHighscore adds i to the "highscore" field.
func (suo *SettingsUpdateOne) AddHighscore(i int) *SettingsUpdateOne {
	suo.mutation.AddHighscore(i)
	return suo
}

// SetHighscoreDate sets the "highscoreDate" field.
func (suo *SettingsUpdateOne) SetHighscoreDate(t time.Time) *SettingsUpdateOne {
	suo.mutation.SetHighscoreDate(t)
	return suo
}

// SetNillableHighscoreDate sets the "highscoreDate" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableHighscoreDate(t *time.Time) *SettingsUpdateOne {
	if t != nil {
		suo.SetHighscoreDate(*t)
	}
	return suo
}

// ClearHighscoreDate clears the value of the "highscoreDate" field.
func (suo *SettingsUpdateOne) ClearHighscoreDate() *SettingsUpdateOne {
	suo.mutation.ClearHighscoreDate()
	return suo
}

// SetSaves sets the "saves" field.
func (suo *SettingsUpdateOne) SetSaves(f float64) *SettingsUpdateOne {
	suo.mutation.ResetSaves()
	suo.mutation.SetSaves(f)
	return suo
}

// SetNillableSaves sets the "saves" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableSaves(f *float64) *SettingsUpdateOne {
	if f != nil {
		suo.SetSaves(*f)
	}
	return suo
}

// AddSaves adds f to the "saves" field.
func (suo *SettingsUpdateOne) AddSaves(f float64) *SettingsUpdateOne {
	suo.mutation.AddSaves(f)
	return suo
}

// SetMaxSaves sets the "maxSaves" field.
func (suo *SettingsUpdateOne) SetMaxSaves(f float64) *SettingsUpdateOne {
	suo.mutation.ResetMaxSaves()
	suo.mutation.SetMaxSaves(f)
	return suo
}

// SetNillableMaxSaves sets the "maxSaves" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableMaxSaves(f *float64) *SettingsUpdateOne {
	if f != nil {
		suo.SetMaxSaves(*f)
	}
	return suo
}

// AddMaxSaves adds f to the "maxSaves" field.
func (suo *SettingsUpdateOne) AddMaxSaves(f float64) *SettingsUpdateOne {
	suo.mutation.AddMaxSaves(f)
	return suo
}

// SetSavesUsed sets the "savesUsed" field.
func (suo *SettingsUpdateOne) SetSavesUsed(f float64) *SettingsUpdateOne {
	suo.mutation.ResetSavesUsed()
	suo.mutation.SetSavesUsed(f)
	return suo
}

// SetNillableSavesUsed sets the "savesUsed" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableSavesUsed(f *float64) *SettingsUpdateOne {
	if f != nil {
		suo.SetSavesUsed(*f)
	}
	return suo
}

// AddSavesUsed adds f to the "savesUsed" field.
func (suo *SettingsUpdateOne) AddSavesUsed(f float64) *SettingsUpdateOne {
	suo.mutation.AddSavesUsed(f)
	return suo
}

// SetUpdatedAt sets the "updatedAt" field.
func (suo *SettingsUpdateOne) SetUpdatedAt(t time.Time) *SettingsUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// Mutation returns the SettingsMutation object of the builder.
func (suo *SettingsUpdateOne) Mutation() *SettingsMutation {
	return suo.mutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (suo *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Settings entity.
func (suo *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SettingsUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

func (suo *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.GuildID(); ok {
		_spec.SetField(settings.FieldGuildID, field.TypeString, value)
	}
	if value, ok := suo.mutation.ChannelID(); ok {
		_spec.SetField(settings.FieldChannelID, field.TypeString, value)
	}
	if suo.mutation.ChannelIDCleared() {
		_spec.ClearField(settings.FieldChannelID, field.TypeString)
	}
	if value, ok := suo.mutation.Cooldown(); ok {
		_spec.SetField(settings.FieldCooldown, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedCooldown(); ok {
		_spec.AddField(settings.FieldCooldown, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Math(); ok {
		_spec.SetField(settings.FieldMath, field.TypeBool, value)
	}
	if value, ok := suo.mutation.ShameRoleID(); ok {
		_spec.SetField(settings.FieldShameRoleID, field.TypeString, value)
	}
	if suo.mutation.ShameRoleIDCleared() {
		_spec.ClearField(settings.FieldShameRoleID, field.TypeString)
	}
	if value, ok := suo.mutation.RemoveShameRoleAfterHighscore(); ok {
		_spec.SetField(settings.FieldRemoveShameRoleAfterHighscore, field.TypeBool, value)
	}
	if value, ok := suo.mutation.LastShameUserID(); ok {
		_spec.SetField(settings.FieldLastShameUserID, field.TypeString, value)
	}
	if suo.mutation.LastShameUserIDCleared() {
		_spec.ClearField(settings.FieldLastShameUserID, field.TypeString)
	}
	if value, ok := suo.mutation.Highscore(); ok {
		_spec.SetField(settings.FieldHighscore, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedHighscore(); ok {
		_spec.AddField(settings.FieldHighscore, field.TypeInt, value)
	}
	if value, ok := suo.mutation.HighscoreDate(); ok {
		_spec.SetField(settings.FieldHighscoreDate, field.TypeTime, value)
	}
	if suo.mutation.HighscoreDateCleared() {
		_spec.ClearField(settings.FieldHighscoreDate, field.TypeTime)
	}
	if value, ok := suo.mutation.Saves(); ok {
		_spec.SetField(settings.FieldSaves, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedSaves(); ok {
		_spec.AddField(settings.FieldSaves, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.MaxSaves(); ok {
		_spec.SetField(settings.FieldMaxSaves, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedMaxSaves(); ok {
		_spec.AddField(settings.FieldMaxSaves, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.SavesUsed(); ok {
		_spec.SetField(settings.FieldSavesUsed, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedSavesUsed(); ok {
		_spec.AddField(settings.FieldSavesUsed, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Settings{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
