// Code generated by ent, DO NOT EDIT.

package playersaves

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"jurien.dev/yugen/kusari/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "userID" field. It's identical to UserIDEQ.
func UserID(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldUserID, v))
}

// Saves applies equality check predicate on the "saves" field. It's identical to SavesEQ.
func Saves(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldSaves, v))
}

// MaxSaves applies equality check predicate on the "maxSaves" field. It's identical to MaxSavesEQ.
func MaxSaves(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldMaxSaves, v))
}

// LastVoteTime applies equality check predicate on the "lastVoteTime" field. It's identical to LastVoteTimeEQ.
func LastVoteTime(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldLastVoteTime, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "userID" field.
func UserIDEQ(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "userID" field.
func UserIDNEQ(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "userID" field.
func UserIDIn(vs ...string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "userID" field.
func UserIDNotIn(vs ...string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "userID" field.
func UserIDGT(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "userID" field.
func UserIDGTE(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "userID" field.
func UserIDLT(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "userID" field.
func UserIDLTE(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "userID" field.
func UserIDContains(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "userID" field.
func UserIDHasPrefix(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "userID" field.
func UserIDHasSuffix(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "userID" field.
func UserIDEqualFold(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "userID" field.
func UserIDContainsFold(v string) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldContainsFold(FieldUserID, v))
}

// SavesEQ applies the EQ predicate on the "saves" field.
func SavesEQ(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldSaves, v))
}

// SavesNEQ applies the NEQ predicate on the "saves" field.
func SavesNEQ(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNEQ(FieldSaves, v))
}

// SavesIn applies the In predicate on the "saves" field.
func SavesIn(vs ...float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldIn(FieldSaves, vs...))
}

// SavesNotIn applies the NotIn predicate on the "saves" field.
func SavesNotIn(vs ...float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNotIn(FieldSaves, vs...))
}

// SavesGT applies the GT predicate on the "saves" field.
func SavesGT(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGT(FieldSaves, v))
}

// SavesGTE applies the GTE predicate on the "saves" field.
func SavesGTE(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGTE(FieldSaves, v))
}

// SavesLT applies the LT predicate on the "saves" field.
func SavesLT(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLT(FieldSaves, v))
}

// SavesLTE applies the LTE predicate on the "saves" field.
func SavesLTE(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLTE(FieldSaves, v))
}

// MaxSavesEQ applies the EQ predicate on the "maxSaves" field.
func MaxSavesEQ(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldMaxSaves, v))
}

// MaxSavesNEQ applies the NEQ predicate on the "maxSaves" field.
func MaxSavesNEQ(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNEQ(FieldMaxSaves, v))
}

// MaxSavesIn applies the In predicate on the "maxSaves" field.
func MaxSavesIn(vs ...float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldIn(FieldMaxSaves, vs...))
}

// MaxSavesNotIn applies the NotIn predicate on the "maxSaves" field.
func MaxSavesNotIn(vs ...float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNotIn(FieldMaxSaves, vs...))
}

// MaxSavesGT applies the GT predicate on the "maxSaves" field.
func MaxSavesGT(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGT(FieldMaxSaves, v))
}

// MaxSavesGTE applies the GTE predicate on the "maxSaves" field.
func MaxSavesGTE(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGTE(FieldMaxSaves, v))
}

// MaxSavesLT applies the LT predicate on the "maxSaves" field.
func MaxSavesLT(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLT(FieldMaxSaves, v))
}

// MaxSavesLTE applies the LTE predicate on the "maxSaves" field.
func MaxSavesLTE(v float64) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLTE(FieldMaxSaves, v))
}

// LastVoteTimeEQ applies the EQ predicate on the "lastVoteTime" field.
func LastVoteTimeEQ(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldLastVoteTime, v))
}

// LastVoteTimeNEQ applies the NEQ predicate on the "lastVoteTime" field.
func LastVoteTimeNEQ(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNEQ(FieldLastVoteTime, v))
}

// LastVoteTimeIn applies the In predicate on the "lastVoteTime" field.
func LastVoteTimeIn(vs ...time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldIn(FieldLastVoteTime, vs...))
}

// LastVoteTimeNotIn applies the NotIn predicate on the "lastVoteTime" field.
func LastVoteTimeNotIn(vs ...time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNotIn(FieldLastVoteTime, vs...))
}

// LastVoteTimeGT applies the GT predicate on the "lastVoteTime" field.
func LastVoteTimeGT(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGT(FieldLastVoteTime, v))
}

// LastVoteTimeGTE applies the GTE predicate on the "lastVoteTime" field.
func LastVoteTimeGTE(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGTE(FieldLastVoteTime, v))
}

// LastVoteTimeLT applies the LT predicate on the "lastVoteTime" field.
func LastVoteTimeLT(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLT(FieldLastVoteTime, v))
}

// LastVoteTimeLTE applies the LTE predicate on the "lastVoteTime" field.
func LastVoteTimeLTE(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLTE(FieldLastVoteTime, v))
}

// LastVoteTimeIsNil applies the IsNil predicate on the "lastVoteTime" field.
func LastVoteTimeIsNil() predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldIsNull(FieldLastVoteTime))
}

// LastVoteTimeNotNil applies the NotNil predicate on the "lastVoteTime" field.
func LastVoteTimeNotNil() predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNotNull(FieldLastVoteTime))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlayerSaves) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlayerSaves) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlayerSaves) predicate.PlayerSaves {
	return predicate.PlayerSaves(sql.NotPredicates(p))
}
