// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"jurien.dev/yugen/hoshi/internal/ent/schema"
	"jurien.dev/yugen/hoshi/internal/ent/settings"
	"jurien.dev/yugen/hoshi/internal/ent/starboardlog"
	"jurien.dev/yugen/hoshi/internal/ent/starboards"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	settingsFields := schema.Settings{}.Fields()
	_ = settingsFields
	// settingsDescTreshold is the schema descriptor for treshold field.
	settingsDescTreshold := settingsFields[1].Descriptor()
	// settings.DefaultTreshold holds the default value on creation for the treshold field.
	settings.DefaultTreshold = settingsDescTreshold.Default.(int)
	// settingsDescSelf is the schema descriptor for self field.
	settingsDescSelf := settingsFields[2].Descriptor()
	// settings.DefaultSelf holds the default value on creation for the self field.
	settings.DefaultSelf = settingsDescSelf.Default.(bool)
	// settingsDescIgnoredChannelIds is the schema descriptor for ignoredChannelIds field.
	settingsDescIgnoredChannelIds := settingsFields[3].Descriptor()
	// settings.DefaultIgnoredChannelIds holds the default value on creation for the ignoredChannelIds field.
	settings.DefaultIgnoredChannelIds = settingsDescIgnoredChannelIds.Default.([]string)
	// settingsDescCreatedAt is the schema descriptor for createdAt field.
	settingsDescCreatedAt := settingsFields[4].Descriptor()
	// settings.DefaultCreatedAt holds the default value on creation for the createdAt field.
	settings.DefaultCreatedAt = settingsDescCreatedAt.Default.(func() time.Time)
	// settingsDescUpdatedAt is the schema descriptor for updatedAt field.
	settingsDescUpdatedAt := settingsFields[5].Descriptor()
	// settings.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	settings.DefaultUpdatedAt = settingsDescUpdatedAt.Default.(func() time.Time)
	// settings.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	settings.UpdateDefaultUpdatedAt = settingsDescUpdatedAt.UpdateDefault.(func() time.Time)
	starboardlogFields := schema.StarboardLog{}.Fields()
	_ = starboardlogFields
	// starboardlogDescCreatedAt is the schema descriptor for createdAt field.
	starboardlogDescCreatedAt := starboardlogFields[4].Descriptor()
	// starboardlog.DefaultCreatedAt holds the default value on creation for the createdAt field.
	starboardlog.DefaultCreatedAt = starboardlogDescCreatedAt.Default.(func() time.Time)
	// starboardlogDescUpdatedAt is the schema descriptor for updatedAt field.
	starboardlogDescUpdatedAt := starboardlogFields[5].Descriptor()
	// starboardlog.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	starboardlog.DefaultUpdatedAt = starboardlogDescUpdatedAt.Default.(func() time.Time)
	// starboardlog.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	starboardlog.UpdateDefaultUpdatedAt = starboardlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	starboardsFields := schema.Starboards{}.Fields()
	_ = starboardsFields
	// starboardsDescSourceEmoji is the schema descriptor for sourceEmoji field.
	starboardsDescSourceEmoji := starboardsFields[1].Descriptor()
	// starboards.DefaultSourceEmoji holds the default value on creation for the sourceEmoji field.
	starboards.DefaultSourceEmoji = starboardsDescSourceEmoji.Default.(string)
	// starboardsDescCreatedAt is the schema descriptor for createdAt field.
	starboardsDescCreatedAt := starboardsFields[4].Descriptor()
	// starboards.DefaultCreatedAt holds the default value on creation for the createdAt field.
	starboards.DefaultCreatedAt = starboardsDescCreatedAt.Default.(func() time.Time)
	// starboardsDescUpdatedAt is the schema descriptor for updatedAt field.
	starboardsDescUpdatedAt := starboardsFields[5].Descriptor()
	// starboards.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	starboards.DefaultUpdatedAt = starboardsDescUpdatedAt.Default.(func() time.Time)
	// starboards.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	starboards.UpdateDefaultUpdatedAt = starboardsDescUpdatedAt.UpdateDefault.(func() time.Time)
}
