// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lib/pq"
	"jurien.dev/yugen/hoshi/internal/ent/settings"
)

// Settings is the model entity for the Settings schema.
type Settings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GuildID holds the value of the "guildID" field.
	GuildID string `json:"guildID,omitempty"`
	// BotUpdatesChannelID holds the value of the "botUpdatesChannelID" field.
	BotUpdatesChannelID *string `json:"botUpdatesChannelID,omitempty"`
	// Treshold holds the value of the "treshold" field.
	Treshold int `json:"treshold,omitempty"`
	// Self holds the value of the "self" field.
	Self bool `json:"self,omitempty"`
	// IgnoredChannelIds holds the value of the "ignoredChannelIds" field.
	IgnoredChannelIds pq.StringArray `json:"ignoredChannelIds,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt    time.Time `json:"updatedAt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Settings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case settings.FieldIgnoredChannelIds:
			values[i] = new(pq.StringArray)
		case settings.FieldSelf:
			values[i] = new(sql.NullBool)
		case settings.FieldID, settings.FieldTreshold:
			values[i] = new(sql.NullInt64)
		case settings.FieldGuildID, settings.FieldBotUpdatesChannelID:
			values[i] = new(sql.NullString)
		case settings.FieldCreatedAt, settings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Settings fields.
func (s *Settings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case settings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case settings.FieldGuildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guildID", values[i])
			} else if value.Valid {
				s.GuildID = value.String
			}
		case settings.FieldBotUpdatesChannelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field botUpdatesChannelID", values[i])
			} else if value.Valid {
				s.BotUpdatesChannelID = new(string)
				*s.BotUpdatesChannelID = value.String
			}
		case settings.FieldTreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field treshold", values[i])
			} else if value.Valid {
				s.Treshold = int(value.Int64)
			}
		case settings.FieldSelf:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field self", values[i])
			} else if value.Valid {
				s.Self = value.Bool
			}
		case settings.FieldIgnoredChannelIds:
			if value, ok := values[i].(*pq.StringArray); !ok {
				return fmt.Errorf("unexpected type %T for field ignoredChannelIds", values[i])
			} else if value != nil {
				s.IgnoredChannelIds = *value
			}
		case settings.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case settings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Settings.
// This includes values selected through modifiers, order, etc.
func (s *Settings) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Settings.
// Note that you need to call Settings.Unwrap() before calling this method if this Settings
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Settings) Update() *SettingsUpdateOne {
	return NewSettingsClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Settings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Settings) Unwrap() *Settings {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Settings is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Settings) String() string {
	var builder strings.Builder
	builder.WriteString("Settings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("guildID=")
	builder.WriteString(s.GuildID)
	builder.WriteString(", ")
	if v := s.BotUpdatesChannelID; v != nil {
		builder.WriteString("botUpdatesChannelID=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("treshold=")
	builder.WriteString(fmt.Sprintf("%v", s.Treshold))
	builder.WriteString(", ")
	builder.WriteString("self=")
	builder.WriteString(fmt.Sprintf("%v", s.Self))
	builder.WriteString(", ")
	builder.WriteString("ignoredChannelIds=")
	builder.WriteString(fmt.Sprintf("%v", s.IgnoredChannelIds))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SettingsSlice is a parsable slice of Settings.
type SettingsSlice []*Settings
