// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/hoshi/internal/ent/predicate"
	"jurien.dev/yugen/hoshi/internal/ent/starboardlog"
)

// StarboardLogDelete is the builder for deleting a StarboardLog entity.
type StarboardLogDelete struct {
	config
	hooks    []Hook
	mutation *StarboardLogMutation
}

// Where appends a list predicates to the StarboardLogDelete builder.
func (sld *StarboardLogDelete) Where(ps ...predicate.StarboardLog) *StarboardLogDelete {
	sld.mutation.Where(ps...)
	return sld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sld *StarboardLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sld.sqlExec, sld.mutation, sld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sld *StarboardLogDelete) ExecX(ctx context.Context) int {
	n, err := sld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sld *StarboardLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(starboardlog.Table, sqlgraph.NewFieldSpec(starboardlog.FieldID, field.TypeInt))
	if ps := sld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sld.mutation.done = true
	return affected, err
}

// StarboardLogDeleteOne is the builder for deleting a single StarboardLog entity.
type StarboardLogDeleteOne struct {
	sld *StarboardLogDelete
}

// Where appends a list predicates to the StarboardLogDelete builder.
func (sldo *StarboardLogDeleteOne) Where(ps ...predicate.StarboardLog) *StarboardLogDeleteOne {
	sldo.sld.mutation.Where(ps...)
	return sldo
}

// Exec executes the deletion query.
func (sldo *StarboardLogDeleteOne) Exec(ctx context.Context) error {
	n, err := sldo.sld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{starboardlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sldo *StarboardLogDeleteOne) ExecX(ctx context.Context) {
	if err := sldo.Exec(ctx); err != nil {
		panic(err)
	}
}
