// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// Guess is the predicate function for guess builders.
type Guess func(*sql.Selector)

// PlayerHints is the predicate function for playerhints builders.
type PlayerHints func(*sql.Selector)

// PlayerStats is the predicate function for playerstats builders.
type PlayerStats func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)
