-- Create "honeypots" table
CREATE TABLE "public"."honeypots" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" character varying NOT NULL,
  "channel_id" character varying NOT NULL,
  "ignored_role_ids" jsonb NOT NULL,
  "delete_message_days" bigint NOT NULL DEFAULT 7,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "honeypot_guild_id" to table: "honeypots"
CREATE INDEX "honeypot_guild_id" ON "public"."honeypots" ("guild_id");
-- Create index "honeypot_guild_id_channel_id" to table: "honeypots"
CREATE UNIQUE INDEX "honeypot_guild_id_channel_id" ON "public"."honeypots" ("guild_id", "channel_id");
-- Create "settings" table
CREATE TABLE "public"."settings" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" character varying NOT NULL,
  "log_channel_id" character varying NULL,
  "log_ping_role_id" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "settings_guild_id" to table: "settings"
CREATE UNIQUE INDEX "settings_guild_id" ON "public"."settings" ("guild_id");
