// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// History is the predicate function for history builders.
type History func(*sql.Selector)

// PlayerSaves is the predicate function for playersaves builders.
type PlayerSaves func(*sql.Selector)

// PlayerStats is the predicate function for playerstats builders.
type PlayerStats func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)
