// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/kusari/internal/ent/playersaves"
	"jurien.dev/yugen/kusari/internal/ent/predicate"
)

// PlayerSavesUpdate is the builder for updating PlayerSaves entities.
type PlayerSavesUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerSavesMutation
}

// Where appends a list predicates to the PlayerSavesUpdate builder.
func (psu *PlayerSavesUpdate) Where(ps ...predicate.PlayerSaves) *PlayerSavesUpdate {
	psu.mutation.Where(ps...)
	return psu
}

// SetUserID sets the "userID" field.
func (psu *PlayerSavesUpdate) SetUserID(s string) *PlayerSavesUpdate {
	psu.mutation.SetUserID(s)
	return psu
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (psu *PlayerSavesUpdate) SetNillableUserID(s *string) *PlayerSavesUpdate {
	if s != nil {
		psu.SetUserID(*s)
	}
	return psu
}

// SetSaves sets the "saves" field.
func (psu *PlayerSavesUpdate) SetSaves(f float64) *PlayerSavesUpdate {
	psu.mutation.ResetSaves()
	psu.mutation.SetSaves(f)
	return psu
}

// SetNillableSaves sets the "saves" field if the given value is not nil.
func (psu *PlayerSavesUpdate) SetNillableSaves(f *float64) *PlayerSavesUpdate {
	if f != nil {
		psu.SetSaves(*f)
	}
	return psu
}

// AddSaves adds f to the "saves" field.
func (psu *PlayerSavesUpdate) AddSaves(f float64) *PlayerSavesUpdate {
	psu.mutation.AddSaves(f)
	return psu
}

// SetMaxSaves sets the "maxSaves" field.
func (psu *PlayerSavesUpdate) SetMaxSaves(f float64) *PlayerSavesUpdate {
	psu.mutation.ResetMaxSaves()
	psu.mutation.SetMaxSaves(f)
	return psu
}

// SetNillableMaxSaves sets the "maxSaves" field if the given value is not nil.
func (psu *PlayerSavesUpdate) SetNillableMaxSaves(f *float64) *PlayerSavesUpdate {
	if f != nil {
		psu.SetMaxSaves(*f)
	}
	return psu
}

// AddMaxSaves adds f to the "maxSaves" field.
func (psu *PlayerSavesUpdate) AddMaxSaves(f float64) *PlayerSavesUpdate {
	psu.mutation.AddMaxSaves(f)
	return psu
}

// SetLastVoteTime sets the "lastVoteTime" field.
func (psu *PlayerSavesUpdate) SetLastVoteTime(t time.Time) *PlayerSavesUpdate {
	psu.mutation.SetLastVoteTime(t)
	return psu
}

// SetNillableLastVoteTime sets the "lastVoteTime" field if the given value is not nil.
func (psu *PlayerSavesUpdate) SetNillableLastVoteTime(t *time.Time) *PlayerSavesUpdate {
	if t != nil {
		psu.SetLastVoteTime(*t)
	}
	return psu
}

// ClearLastVoteTime clears the value of the "lastVoteTime" field.
func (psu *PlayerSavesUpdate) ClearLastVoteTime() *PlayerSavesUpdate {
	psu.mutation.ClearLastVoteTime()
	return psu
}

// SetUpdatedAt sets the "updatedAt" field.
func (psu *PlayerSavesUpdate) SetUpdatedAt(t time.Time) *PlayerSavesUpdate {
	psu.mutation.SetUpdatedAt(t)
	return psu
}

// Mutation returns the PlayerSavesMutation object of the builder.
func (psu *PlayerSavesUpdate) Mutation() *PlayerSavesMutation {
	return psu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (psu *PlayerSavesUpdate) Save(ctx context.Context) (int, error) {
	psu.defaults()
	return withHooks(ctx, psu.sqlSave, psu.mutation, psu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psu *PlayerSavesUpdate) SaveX(ctx context.Context) int {
	affected, err := psu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (psu *PlayerSavesUpdate) Exec(ctx context.Context) error {
	_, err := psu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psu *PlayerSavesUpdate) ExecX(ctx context.Context) {
	if err := psu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psu *PlayerSavesUpdate) defaults() {
	if _, ok := psu.mutation.UpdatedAt(); !ok {
		v := playersaves.UpdateDefaultUpdatedAt()
		psu.mutation.SetUpdatedAt(v)
	}
}

func (psu *PlayerSavesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(playersaves.Table, playersaves.Columns, sqlgraph.NewFieldSpec(playersaves.FieldID, field.TypeInt))
	if ps := psu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psu.mutation.UserID(); ok {
		_spec.SetField(playersaves.FieldUserID, field.TypeString, value)
	}
	if value, ok := psu.mutation.Saves(); ok {
		_spec.SetField(playersaves.FieldSaves, field.TypeFloat64, value)
	}
	if value, ok := psu.mutation.AddedSaves(); ok {
		_spec.AddField(playersaves.FieldSaves, field.TypeFloat64, value)
	}
	if value, ok := psu.mutation.MaxSaves(); ok {
		_spec.SetField(playersaves.FieldMaxSaves, field.TypeFloat64, value)
	}
	if value, ok := psu.mutation.AddedMaxSaves(); ok {
		_spec.AddField(playersaves.FieldMaxSaves, field.TypeFloat64, value)
	}
	if value, ok := psu.mutation.LastVoteTime(); ok {
		_spec.SetField(playersaves.FieldLastVoteTime, field.TypeTime, value)
	}
	if psu.mutation.LastVoteTimeCleared() {
		_spec.ClearField(playersaves.FieldLastVoteTime, field.TypeTime)
	}
	if value, ok := psu.mutation.UpdatedAt(); ok {
		_spec.SetField(playersaves.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, psu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playersaves.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	psu.mutation.done = true
	return n, nil
}

// PlayerSavesUpdateOne is the builder for updating a single PlayerSaves entity.
type PlayerSavesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerSavesMutation
}

// SetUserID sets the "userID" field.
func (psuo *PlayerSavesUpdateOne) SetUserID(s string) *PlayerSavesUpdateOne {
	psuo.mutation.SetUserID(s)
	return psuo
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (psuo *PlayerSavesUpdateOne) SetNillableUserID(s *string) *PlayerSavesUpdateOne {
	if s != nil {
		psuo.SetUserID(*s)
	}
	return psuo
}

// SetSaves sets the "saves" field.
func (psuo *PlayerSavesUpdateOne) SetSaves(f float64) *PlayerSavesUpdateOne {
	psuo.mutation.ResetSaves()
	psuo.mutation.SetSaves(f)
	return psuo
}

// SetNillableSaves sets the "saves" field if the given value is not nil.
func (psuo *PlayerSavesUpdateOne) SetNillableSaves(f *float64) *PlayerSavesUpdateOne {
	if f != nil {
		psuo.SetSaves(*f)
	}
	return psuo
}

// AddSaves adds f to the "saves" field.
func (psuo *PlayerSavesUpdateOne) AddSaves(f float64) *PlayerSavesUpdateOne {
	psuo.mutation.AddSaves(f)
	return psuo
}

// SetMaxSaves sets the "maxSaves" field.
func (psuo *PlayerSavesUpdateOne) SetMaxSaves(f float64) *PlayerSavesUpdateOne {
	psuo.mutation.ResetMaxSaves()
	psuo.mutation.SetMaxSaves(f)
	return psuo
}

// SetNillableMaxSaves sets the "maxSaves" field if the given value is not nil.
func (psuo *PlayerSavesUpdateOne) SetNillableMaxSaves(f *float64) *PlayerSavesUpdateOne {
	if f != nil {
		psuo.SetMaxSaves(*f)
	}
	return psuo
}

// AddMaxSaves adds f to the "maxSaves" field.
func (psuo *PlayerSavesUpdateOne) AddMaxSaves(f float64) *PlayerSavesUpdateOne {
	psuo.mutation.AddMaxSaves(f)
	return psuo
}

// SetLastVoteTime sets the "lastVoteTime" field.
func (psuo *PlayerSavesUpdateOne) SetLastVoteTime(t time.Time) *PlayerSavesUpdateOne {
	psuo.mutation.SetLastVoteTime(t)
	return psuo
}

// SetNillableLastVoteTime sets the "lastVoteTime" field if the given value is not nil.
func (psuo *PlayerSavesUpdateOne) SetNillableLastVoteTime(t *time.Time) *PlayerSavesUpdateOne {
	if t != nil {
		psuo.SetLastVoteTime(*t)
	}
	return psuo
}

// ClearLastVoteTime clears the value of the "lastVoteTime" field.
func (psuo *PlayerSavesUpdateOne) ClearLastVoteTime() *PlayerSavesUpdateOne {
	psuo.mutation.ClearLastVoteTime()
	return psuo
}

// SetUpdatedAt sets the "updatedAt" field.
func (psuo *PlayerSavesUpdateOne) SetUpdatedAt(t time.Time) *PlayerSavesUpdateOne {
	psuo.mutation.SetUpdatedAt(t)
	return psuo
}

// Mutation returns the PlayerSavesMutation object of the builder.
func (psuo *PlayerSavesUpdateOne) Mutation() *PlayerSavesMutation {
	return psuo.mutation
}

// Where appends a list predicates to the PlayerSavesUpdate builder.
func (psuo *PlayerSavesUpdateOne) Where(ps ...predicate.PlayerSaves) *PlayerSavesUpdateOne {
	psuo.mutation.Where(ps...)
	return psuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (psuo *PlayerSavesUpdateOne) Select(field string, fields ...string) *PlayerSavesUpdateOne {
	psuo.fields = append([]string{field}, fields...)
	return psuo
}

// Save executes the query and returns the updated PlayerSaves entity.
func (psuo *PlayerSavesUpdateOne) Save(ctx context.Context) (*PlayerSaves, error) {
	psuo.defaults()
	return withHooks(ctx, psuo.sqlSave, psuo.mutation, psuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psuo *PlayerSavesUpdateOne) SaveX(ctx context.Context) *PlayerSaves {
	node, err := psuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (psuo *PlayerSavesUpdateOne) Exec(ctx context.Context) error {
	_, err := psuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psuo *PlayerSavesUpdateOne) ExecX(ctx context.Context) {
	if err := psuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psuo *PlayerSavesUpdateOne) defaults() {
	if _, ok := psuo.mutation.UpdatedAt(); !ok {
		v := playersaves.UpdateDefaultUpdatedAt()
		psuo.mutation.SetUpdatedAt(v)
	}
}

func (psuo *PlayerSavesUpdateOne) sqlSave(ctx context.Context) (_node *PlayerSaves, err error) {
	_spec := sqlgraph.NewUpdateSpec(playersaves.Table, playersaves.Columns, sqlgraph.NewFieldSpec(playersaves.FieldID, field.TypeInt))
	id, ok := psuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlayerSaves.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := psuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playersaves.FieldID)
		for _, f := range fields {
			if !playersaves.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playersaves.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := psuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psuo.mutation.UserID(); ok {
		_spec.SetField(playersaves.FieldUserID, field.TypeString, value)
	}
	if value, ok := psuo.mutation.Saves(); ok {
		_spec.SetField(playersaves.FieldSaves, field.TypeFloat64, value)
	}
	if value, ok := psuo.mutation.AddedSaves(); ok {
		_spec.AddField(playersaves.FieldSaves, field.TypeFloat64, value)
	}
	if value, ok := psuo.mutation.MaxSaves(); ok {
		_spec.SetField(playersaves.FieldMaxSaves, field.TypeFloat64, value)
	}
	if value, ok := psuo.mutation.AddedMaxSaves(); ok {
		_spec.AddField(playersaves.FieldMaxSaves, field.TypeFloat64, value)
	}
	if value, ok := psuo.mutation.LastVoteTime(); ok {
		_spec.SetField(playersaves.FieldLastVoteTime, field.TypeTime, value)
	}
	if psuo.mutation.LastVoteTimeCleared() {
		_spec.ClearField(playersaves.FieldLastVoteTime, field.TypeTime)
	}
	if value, ok := psuo.mutation.UpdatedAt(); ok {
		_spec.SetField(playersaves.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PlayerSaves{config: psuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, psuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playersaves.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	psuo.mutation.done = true
	return _node, nil
}
