// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "bot_updates_channel_id", Type: field.TypeString, Nullable: true},
		{Name: "treshold", Type: field.TypeInt, Default: 3},
		{Name: "self", Type: field.TypeBool, Default: false},
		{Name: "ignored_channel_ids", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "settings_guild_id",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[1]},
			},
		},
	}
	// StarboardLogsColumns holds the columns for the "starboard_logs" table.
	StarboardLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "channel_id", Type: field.TypeString},
		{Name: "message_id", Type: field.TypeString},
		{Name: "original_message_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// StarboardLogsTable holds the schema information for the "starboard_logs" table.
	StarboardLogsTable = &schema.Table{
		Name:       "starboard_logs",
		Columns:    StarboardLogsColumns,
		PrimaryKey: []*schema.Column{StarboardLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "starboardlog_message_id",
				Unique:  true,
				Columns: []*schema.Column{StarboardLogsColumns[3]},
			},
			{
				Name:    "starboardlog_original_message_id",
				Unique:  true,
				Columns: []*schema.Column{StarboardLogsColumns[4]},
			},
		},
	}
	// StarboardsColumns holds the columns for the "starboards" table.
	StarboardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "source_emoji", Type: field.TypeString, Default: "⭐"},
		{Name: "source_channel_id", Type: field.TypeString, Nullable: true},
		{Name: "target_channel_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// StarboardsTable holds the schema information for the "starboards" table.
	StarboardsTable = &schema.Table{
		Name:       "starboards",
		Columns:    StarboardsColumns,
		PrimaryKey: []*schema.Column{StarboardsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SettingsTable,
		StarboardLogsTable,
		StarboardsTable,
	}
)

func init() {
}
