// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SettingsColumns holds the columns for the "Settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guildId", Type: field.TypeString},
		{Name: "botUpdatesChannelId", Type: field.TypeString, Nullable: true},
		{Name: "treshold", Type: field.TypeInt, Default: 3},
		{Name: "self", Type: field.TypeBool, Default: false},
		{Name: "ignoredChannelIds", Type: field.TypeOther, SchemaType: map[string]string{"postgres": "text[]"}},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "Settings" table.
	SettingsTable = &schema.Table{
		Name:       "Settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "Settings_guildId_key",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[1]},
			},
		},
	}
	// LogColumns holds the columns for the "Log" table.
	LogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guildId", Type: field.TypeString},
		{Name: "channelId", Type: field.TypeString},
		{Name: "messageId", Type: field.TypeString},
		{Name: "originalMessageId", Type: field.TypeString},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// LogTable holds the schema information for the "Log" table.
	LogTable = &schema.Table{
		Name:       "Log",
		Columns:    LogColumns,
		PrimaryKey: []*schema.Column{LogColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "Log_messageId_key",
				Unique:  true,
				Columns: []*schema.Column{LogColumns[3]},
			},
			{
				Name:    "Log_originalMessageId_key",
				Unique:  true,
				Columns: []*schema.Column{LogColumns[4]},
			},
		},
	}
	// StarboardsColumns holds the columns for the "Starboards" table.
	StarboardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guildId", Type: field.TypeString},
		{Name: "sourceEmoji", Type: field.TypeString, Default: "⭐"},
		{Name: "sourceChannelId", Type: field.TypeString, Nullable: true},
		{Name: "targetChannelId", Type: field.TypeString},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// StarboardsTable holds the schema information for the "Starboards" table.
	StarboardsTable = &schema.Table{
		Name:       "Starboards",
		Columns:    StarboardsColumns,
		PrimaryKey: []*schema.Column{StarboardsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SettingsTable,
		LogTable,
		StarboardsTable,
	}
)

func init() {
	SettingsTable.Annotation = &entsql.Annotation{
		Table: "Settings",
	}
	LogTable.Annotation = &entsql.Annotation{
		Table: "Log",
	}
	StarboardsTable.Annotation = &entsql.Annotation{
		Table: "Starboards",
	}
}
