// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GamesColumns holds the columns for the "games" table.
	GamesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "last_message_id", Type: field.TypeString, Nullable: true},
		{Name: "word", Type: field.TypeString},
		{Name: "ending_at", Type: field.TypeTime},
		{Name: "number", Type: field.TypeInt, Default: 1},
		{Name: "schedule_started", Type: field.TypeBool, Default: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"IN_PROGRESS", "FAILED", "COMPLETED", "OUT_OF_TIME"}, Default: "IN_PROGRESS"},
		{Name: "meta", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GamesTable holds the schema information for the "games" table.
	GamesTable = &schema.Table{
		Name:       "games",
		Columns:    GamesColumns,
		PrimaryKey: []*schema.Column{GamesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "game_guild_id",
				Unique:  false,
				Columns: []*schema.Column{GamesColumns[1]},
			},
		},
	}
	// GuessesColumns holds the columns for the "guesses" table.
	GuessesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "word", Type: field.TypeString},
		{Name: "points", Type: field.TypeInt, Default: 0},
		{Name: "meta", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "game_id", Type: field.TypeInt},
	}
	// GuessesTable holds the schema information for the "guesses" table.
	GuessesTable = &schema.Table{
		Name:       "guesses",
		Columns:    GuessesColumns,
		PrimaryKey: []*schema.Column{GuessesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "guesses_games_guesses",
				Columns:    []*schema.Column{GuessesColumns[7]},
				RefColumns: []*schema.Column{GamesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "guess_game_id",
				Unique:  false,
				Columns: []*schema.Column{GuessesColumns[7]},
			},
		},
	}
	// PlayerHintsColumns holds the columns for the "player_hints" table.
	PlayerHintsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "hints", Type: field.TypeFloat64, Default: 0},
		{Name: "max_hints", Type: field.TypeFloat64, Default: 5},
		{Name: "last_vote_time", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PlayerHintsTable holds the schema information for the "player_hints" table.
	PlayerHintsTable = &schema.Table{
		Name:       "player_hints",
		Columns:    PlayerHintsColumns,
		PrimaryKey: []*schema.Column{PlayerHintsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "playerhints_user_id",
				Unique:  false,
				Columns: []*schema.Column{PlayerHintsColumns[1]},
			},
		},
	}
	// PlayerStatsColumns holds the columns for the "player_stats" table.
	PlayerStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "in_guild", Type: field.TypeBool, Default: true},
		{Name: "points", Type: field.TypeInt, Default: 0},
		{Name: "participated", Type: field.TypeInt, Default: 0},
		{Name: "wins", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PlayerStatsTable holds the schema information for the "player_stats" table.
	PlayerStatsTable = &schema.Table{
		Name:       "player_stats",
		Columns:    PlayerStatsColumns,
		PrimaryKey: []*schema.Column{PlayerStatsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "playerstats_user_id_guild_id",
				Unique:  false,
				Columns: []*schema.Column{PlayerStatsColumns[1], PlayerStatsColumns[2]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "bot_updates_channel_id", Type: field.TypeString, Nullable: true},
		{Name: "channel_id", Type: field.TypeString, Nullable: true},
		{Name: "ping_role_id", Type: field.TypeString, Nullable: true},
		{Name: "ping_only_new", Type: field.TypeBool, Default: true},
		{Name: "members_can_start", Type: field.TypeBool, Default: false},
		{Name: "cooldown", Type: field.TypeInt, Default: 600},
		{Name: "enable_back_to_back_cooldown", Type: field.TypeBool, Default: false},
		{Name: "back_to_back_cooldown", Type: field.TypeInt, Default: 600},
		{Name: "inform_cooldown_after_guess", Type: field.TypeBool, Default: false},
		{Name: "frequency", Type: field.TypeInt, Default: 60},
		{Name: "time_limit", Type: field.TypeInt, Default: 60},
		{Name: "auto_start", Type: field.TypeBool, Default: false},
		{Name: "start_after_first_guess", Type: field.TypeBool, Default: false},
		{Name: "hints", Type: field.TypeFloat64, Default: 0},
		{Name: "max_hints", Type: field.TypeFloat64, Default: 5},
		{Name: "hints_used", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "settings_guild_id",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[1]},
			},
			{
				Name:    "settings_guild_id_channel_id",
				Unique:  false,
				Columns: []*schema.Column{SettingsColumns[1], SettingsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GamesTable,
		GuessesTable,
		PlayerHintsTable,
		PlayerStatsTable,
		SettingsTable,
	}
)

func init() {
	GuessesTable.ForeignKeys[0].RefTable = GamesTable
}
