// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GamesColumns holds the columns for the "games" table.
	GamesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"IN_PROGRESS", "FAILED", "COMPLETED"}, Default: "IN_PROGRESS"},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"NORMAL"}, Default: "NORMAL"},
		{Name: "is_highscored", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GamesTable holds the schema information for the "games" table.
	GamesTable = &schema.Table{
		Name:       "games",
		Columns:    GamesColumns,
		PrimaryKey: []*schema.Column{GamesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "game_guild_id",
				Unique:  false,
				Columns: []*schema.Column{GamesColumns[1]},
			},
		},
	}
	// HistoriesColumns holds the columns for the "histories" table.
	HistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "message_id", Type: field.TypeString, Nullable: true},
		{Name: "word", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "game_id", Type: field.TypeInt},
	}
	// HistoriesTable holds the schema information for the "histories" table.
	HistoriesTable = &schema.Table{
		Name:       "histories",
		Columns:    HistoriesColumns,
		PrimaryKey: []*schema.Column{HistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "histories_games_history",
				Columns:    []*schema.Column{HistoriesColumns[6]},
				RefColumns: []*schema.Column{GamesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "history_user_id_game_id",
				Unique:  false,
				Columns: []*schema.Column{HistoriesColumns[1], HistoriesColumns[6]},
			},
		},
	}
	// PlayerSavesColumns holds the columns for the "player_saves" table.
	PlayerSavesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "saves", Type: field.TypeFloat64, Default: 0},
		{Name: "max_saves", Type: field.TypeFloat64, Default: 2},
		{Name: "last_vote_time", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PlayerSavesTable holds the schema information for the "player_saves" table.
	PlayerSavesTable = &schema.Table{
		Name:       "player_saves",
		Columns:    PlayerSavesColumns,
		PrimaryKey: []*schema.Column{PlayerSavesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "playersaves_user_id",
				Unique:  false,
				Columns: []*schema.Column{PlayerSavesColumns[1]},
			},
		},
	}
	// PlayerStatsColumns holds the columns for the "player_stats" table.
	PlayerStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "in_guild", Type: field.TypeBool, Default: true},
		{Name: "points", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PlayerStatsTable holds the schema information for the "player_stats" table.
	PlayerStatsTable = &schema.Table{
		Name:       "player_stats",
		Columns:    PlayerStatsColumns,
		PrimaryKey: []*schema.Column{PlayerStatsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "playerstats_user_id_guild_id",
				Unique:  false,
				Columns: []*schema.Column{PlayerStatsColumns[1], PlayerStatsColumns[2]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "channel_id", Type: field.TypeString, Nullable: true},
		{Name: "cooldown", Type: field.TypeInt, Default: 60},
		{Name: "highscore", Type: field.TypeInt, Default: 0},
		{Name: "highscore_date", Type: field.TypeTime, Nullable: true},
		{Name: "saves", Type: field.TypeFloat64, Default: 0},
		{Name: "max_saves", Type: field.TypeFloat64, Default: 2},
		{Name: "saves_used", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "settings_guild_id",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[1]},
			},
			{
				Name:    "settings_guild_id",
				Unique:  false,
				Columns: []*schema.Column{SettingsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GamesTable,
		HistoriesTable,
		PlayerSavesTable,
		PlayerStatsTable,
		SettingsTable,
	}
)

func init() {
	HistoriesTable.ForeignKeys[0].RefTable = GamesTable
}
