// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"jurien.dev/yugen/koto/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"jurien.dev/yugen/koto/internal/ent/game"
	"jurien.dev/yugen/koto/internal/ent/guess"
	"jurien.dev/yugen/koto/internal/ent/playerhints"
	"jurien.dev/yugen/koto/internal/ent/playerstats"
	"jurien.dev/yugen/koto/internal/ent/settings"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Game is the client for interacting with the Game builders.
	Game *GameClient
	// Guess is the client for interacting with the Guess builders.
	Guess *GuessClient
	// PlayerHints is the client for interacting with the PlayerHints builders.
	PlayerHints *PlayerHintsClient
	// PlayerStats is the client for interacting with the PlayerStats builders.
	PlayerStats *PlayerStatsClient
	// Settings is the client for interacting with the Settings builders.
	Settings *SettingsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Game = NewGameClient(c.config)
	c.Guess = NewGuessClient(c.config)
	c.PlayerHints = NewPlayerHintsClient(c.config)
	c.PlayerStats = NewPlayerStatsClient(c.config)
	c.Settings = NewSettingsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Game:        NewGameClient(cfg),
		Guess:       NewGuessClient(cfg),
		PlayerHints: NewPlayerHintsClient(cfg),
		PlayerStats: NewPlayerStatsClient(cfg),
		Settings:    NewSettingsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Game:        NewGameClient(cfg),
		Guess:       NewGuessClient(cfg),
		PlayerHints: NewPlayerHintsClient(cfg),
		PlayerStats: NewPlayerStatsClient(cfg),
		Settings:    NewSettingsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Game.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Game.Use(hooks...)
	c.Guess.Use(hooks...)
	c.PlayerHints.Use(hooks...)
	c.PlayerStats.Use(hooks...)
	c.Settings.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Game.Intercept(interceptors...)
	c.Guess.Intercept(interceptors...)
	c.PlayerHints.Intercept(interceptors...)
	c.PlayerStats.Intercept(interceptors...)
	c.Settings.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *GameMutation:
		return c.Game.mutate(ctx, m)
	case *GuessMutation:
		return c.Guess.mutate(ctx, m)
	case *PlayerHintsMutation:
		return c.PlayerHints.mutate(ctx, m)
	case *PlayerStatsMutation:
		return c.PlayerStats.mutate(ctx, m)
	case *SettingsMutation:
		return c.Settings.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// GameClient is a client for the Game schema.
type GameClient struct {
	config
}

// NewGameClient returns a client for the Game from the given config.
func NewGameClient(c config) *GameClient {
	return &GameClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `game.Hooks(f(g(h())))`.
func (c *GameClient) Use(hooks ...Hook) {
	c.hooks.Game = append(c.hooks.Game, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `game.Intercept(f(g(h())))`.
func (c *GameClient) Intercept(interceptors ...Interceptor) {
	c.inters.Game = append(c.inters.Game, interceptors...)
}

// Create returns a builder for creating a Game entity.
func (c *GameClient) Create() *GameCreate {
	mutation := newGameMutation(c.config, OpCreate)
	return &GameCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Game entities.
func (c *GameClient) CreateBulk(builders ...*GameCreate) *GameCreateBulk {
	return &GameCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GameClient) MapCreateBulk(slice any, setFunc func(*GameCreate, int)) *GameCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GameCreateBulk{err: fmt.Errorf("calling to GameClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GameCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GameCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Game.
func (c *GameClient) Update() *GameUpdate {
	mutation := newGameMutation(c.config, OpUpdate)
	return &GameUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GameClient) UpdateOne(ga *Game) *GameUpdateOne {
	mutation := newGameMutation(c.config, OpUpdateOne, withGame(ga))
	return &GameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GameClient) UpdateOneID(id int) *GameUpdateOne {
	mutation := newGameMutation(c.config, OpUpdateOne, withGameID(id))
	return &GameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Game.
func (c *GameClient) Delete() *GameDelete {
	mutation := newGameMutation(c.config, OpDelete)
	return &GameDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GameClient) DeleteOne(ga *Game) *GameDeleteOne {
	return c.DeleteOneID(ga.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GameClient) DeleteOneID(id int) *GameDeleteOne {
	builder := c.Delete().Where(game.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GameDeleteOne{builder}
}

// Query returns a query builder for Game.
func (c *GameClient) Query() *GameQuery {
	return &GameQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGame},
		inters: c.Interceptors(),
	}
}

// Get returns a Game entity by its id.
func (c *GameClient) Get(ctx context.Context, id int) (*Game, error) {
	return c.Query().Where(game.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GameClient) GetX(ctx context.Context, id int) *Game {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGuesses queries the guesses edge of a Game.
func (c *GameClient) QueryGuesses(ga *Game) *GuessQuery {
	query := (&GuessClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ga.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(game.Table, game.FieldID, id),
			sqlgraph.To(guess.Table, guess.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, game.GuessesTable, game.GuessesColumn),
		)
		fromV = sqlgraph.Neighbors(ga.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GameClient) Hooks() []Hook {
	return c.hooks.Game
}

// Interceptors returns the client interceptors.
func (c *GameClient) Interceptors() []Interceptor {
	return c.inters.Game
}

func (c *GameClient) mutate(ctx context.Context, m *GameMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GameCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GameUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GameDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Game mutation op: %q", m.Op())
	}
}

// GuessClient is a client for the Guess schema.
type GuessClient struct {
	config
}

// NewGuessClient returns a client for the Guess from the given config.
func NewGuessClient(c config) *GuessClient {
	return &GuessClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `guess.Hooks(f(g(h())))`.
func (c *GuessClient) Use(hooks ...Hook) {
	c.hooks.Guess = append(c.hooks.Guess, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `guess.Intercept(f(g(h())))`.
func (c *GuessClient) Intercept(interceptors ...Interceptor) {
	c.inters.Guess = append(c.inters.Guess, interceptors...)
}

// Create returns a builder for creating a Guess entity.
func (c *GuessClient) Create() *GuessCreate {
	mutation := newGuessMutation(c.config, OpCreate)
	return &GuessCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Guess entities.
func (c *GuessClient) CreateBulk(builders ...*GuessCreate) *GuessCreateBulk {
	return &GuessCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GuessClient) MapCreateBulk(slice any, setFunc func(*GuessCreate, int)) *GuessCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GuessCreateBulk{err: fmt.Errorf("calling to GuessClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GuessCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GuessCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Guess.
func (c *GuessClient) Update() *GuessUpdate {
	mutation := newGuessMutation(c.config, OpUpdate)
	return &GuessUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GuessClient) UpdateOne(gu *Guess) *GuessUpdateOne {
	mutation := newGuessMutation(c.config, OpUpdateOne, withGuess(gu))
	return &GuessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GuessClient) UpdateOneID(id int) *GuessUpdateOne {
	mutation := newGuessMutation(c.config, OpUpdateOne, withGuessID(id))
	return &GuessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Guess.
func (c *GuessClient) Delete() *GuessDelete {
	mutation := newGuessMutation(c.config, OpDelete)
	return &GuessDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GuessClient) DeleteOne(gu *Guess) *GuessDeleteOne {
	return c.DeleteOneID(gu.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GuessClient) DeleteOneID(id int) *GuessDeleteOne {
	builder := c.Delete().Where(guess.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GuessDeleteOne{builder}
}

// Query returns a query builder for Guess.
func (c *GuessClient) Query() *GuessQuery {
	return &GuessQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGuess},
		inters: c.Interceptors(),
	}
}

// Get returns a Guess entity by its id.
func (c *GuessClient) Get(ctx context.Context, id int) (*Guess, error) {
	return c.Query().Where(guess.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GuessClient) GetX(ctx context.Context, id int) *Guess {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGame queries the game edge of a Guess.
func (c *GuessClient) QueryGame(gu *Guess) *GameQuery {
	query := (&GameClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := gu.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(guess.Table, guess.FieldID, id),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, guess.GameTable, guess.GameColumn),
		)
		fromV = sqlgraph.Neighbors(gu.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GuessClient) Hooks() []Hook {
	return c.hooks.Guess
}

// Interceptors returns the client interceptors.
func (c *GuessClient) Interceptors() []Interceptor {
	return c.inters.Guess
}

func (c *GuessClient) mutate(ctx context.Context, m *GuessMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GuessCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GuessUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GuessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GuessDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Guess mutation op: %q", m.Op())
	}
}

// PlayerHintsClient is a client for the PlayerHints schema.
type PlayerHintsClient struct {
	config
}

// NewPlayerHintsClient returns a client for the PlayerHints from the given config.
func NewPlayerHintsClient(c config) *PlayerHintsClient {
	return &PlayerHintsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `playerhints.Hooks(f(g(h())))`.
func (c *PlayerHintsClient) Use(hooks ...Hook) {
	c.hooks.PlayerHints = append(c.hooks.PlayerHints, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `playerhints.Intercept(f(g(h())))`.
func (c *PlayerHintsClient) Intercept(interceptors ...Interceptor) {
	c.inters.PlayerHints = append(c.inters.PlayerHints, interceptors...)
}

// Create returns a builder for creating a PlayerHints entity.
func (c *PlayerHintsClient) Create() *PlayerHintsCreate {
	mutation := newPlayerHintsMutation(c.config, OpCreate)
	return &PlayerHintsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PlayerHints entities.
func (c *PlayerHintsClient) CreateBulk(builders ...*PlayerHintsCreate) *PlayerHintsCreateBulk {
	return &PlayerHintsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PlayerHintsClient) MapCreateBulk(slice any, setFunc func(*PlayerHintsCreate, int)) *PlayerHintsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PlayerHintsCreateBulk{err: fmt.Errorf("calling to PlayerHintsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PlayerHintsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PlayerHintsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PlayerHints.
func (c *PlayerHintsClient) Update() *PlayerHintsUpdate {
	mutation := newPlayerHintsMutation(c.config, OpUpdate)
	return &PlayerHintsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PlayerHintsClient) UpdateOne(ph *PlayerHints) *PlayerHintsUpdateOne {
	mutation := newPlayerHintsMutation(c.config, OpUpdateOne, withPlayerHints(ph))
	return &PlayerHintsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PlayerHintsClient) UpdateOneID(id int) *PlayerHintsUpdateOne {
	mutation := newPlayerHintsMutation(c.config, OpUpdateOne, withPlayerHintsID(id))
	return &PlayerHintsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PlayerHints.
func (c *PlayerHintsClient) Delete() *PlayerHintsDelete {
	mutation := newPlayerHintsMutation(c.config, OpDelete)
	return &PlayerHintsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PlayerHintsClient) DeleteOne(ph *PlayerHints) *PlayerHintsDeleteOne {
	return c.DeleteOneID(ph.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PlayerHintsClient) DeleteOneID(id int) *PlayerHintsDeleteOne {
	builder := c.Delete().Where(playerhints.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PlayerHintsDeleteOne{builder}
}

// Query returns a query builder for PlayerHints.
func (c *PlayerHintsClient) Query() *PlayerHintsQuery {
	return &PlayerHintsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePlayerHints},
		inters: c.Interceptors(),
	}
}

// Get returns a PlayerHints entity by its id.
func (c *PlayerHintsClient) Get(ctx context.Context, id int) (*PlayerHints, error) {
	return c.Query().Where(playerhints.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PlayerHintsClient) GetX(ctx context.Context, id int) *PlayerHints {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PlayerHintsClient) Hooks() []Hook {
	return c.hooks.PlayerHints
}

// Interceptors returns the client interceptors.
func (c *PlayerHintsClient) Interceptors() []Interceptor {
	return c.inters.PlayerHints
}

func (c *PlayerHintsClient) mutate(ctx context.Context, m *PlayerHintsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PlayerHintsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PlayerHintsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PlayerHintsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PlayerHintsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PlayerHints mutation op: %q", m.Op())
	}
}

// PlayerStatsClient is a client for the PlayerStats schema.
type PlayerStatsClient struct {
	config
}

// NewPlayerStatsClient returns a client for the PlayerStats from the given config.
func NewPlayerStatsClient(c config) *PlayerStatsClient {
	return &PlayerStatsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `playerstats.Hooks(f(g(h())))`.
func (c *PlayerStatsClient) Use(hooks ...Hook) {
	c.hooks.PlayerStats = append(c.hooks.PlayerStats, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `playerstats.Intercept(f(g(h())))`.
func (c *PlayerStatsClient) Intercept(interceptors ...Interceptor) {
	c.inters.PlayerStats = append(c.inters.PlayerStats, interceptors...)
}

// Create returns a builder for creating a PlayerStats entity.
func (c *PlayerStatsClient) Create() *PlayerStatsCreate {
	mutation := newPlayerStatsMutation(c.config, OpCreate)
	return &PlayerStatsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PlayerStats entities.
func (c *PlayerStatsClient) CreateBulk(builders ...*PlayerStatsCreate) *PlayerStatsCreateBulk {
	return &PlayerStatsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PlayerStatsClient) MapCreateBulk(slice any, setFunc func(*PlayerStatsCreate, int)) *PlayerStatsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PlayerStatsCreateBulk{err: fmt.Errorf("calling to PlayerStatsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PlayerStatsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PlayerStatsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PlayerStats.
func (c *PlayerStatsClient) Update() *PlayerStatsUpdate {
	mutation := newPlayerStatsMutation(c.config, OpUpdate)
	return &PlayerStatsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PlayerStatsClient) UpdateOne(ps *PlayerStats) *PlayerStatsUpdateOne {
	mutation := newPlayerStatsMutation(c.config, OpUpdateOne, withPlayerStats(ps))
	return &PlayerStatsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PlayerStatsClient) UpdateOneID(id int) *PlayerStatsUpdateOne {
	mutation := newPlayerStatsMutation(c.config, OpUpdateOne, withPlayerStatsID(id))
	return &PlayerStatsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PlayerStats.
func (c *PlayerStatsClient) Delete() *PlayerStatsDelete {
	mutation := newPlayerStatsMutation(c.config, OpDelete)
	return &PlayerStatsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PlayerStatsClient) DeleteOne(ps *PlayerStats) *PlayerStatsDeleteOne {
	return c.DeleteOneID(ps.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PlayerStatsClient) DeleteOneID(id int) *PlayerStatsDeleteOne {
	builder := c.Delete().Where(playerstats.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PlayerStatsDeleteOne{builder}
}

// Query returns a query builder for PlayerStats.
func (c *PlayerStatsClient) Query() *PlayerStatsQuery {
	return &PlayerStatsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePlayerStats},
		inters: c.Interceptors(),
	}
}

// Get returns a PlayerStats entity by its id.
func (c *PlayerStatsClient) Get(ctx context.Context, id int) (*PlayerStats, error) {
	return c.Query().Where(playerstats.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PlayerStatsClient) GetX(ctx context.Context, id int) *PlayerStats {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PlayerStatsClient) Hooks() []Hook {
	return c.hooks.PlayerStats
}

// Interceptors returns the client interceptors.
func (c *PlayerStatsClient) Interceptors() []Interceptor {
	return c.inters.PlayerStats
}

func (c *PlayerStatsClient) mutate(ctx context.Context, m *PlayerStatsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PlayerStatsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PlayerStatsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PlayerStatsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PlayerStatsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PlayerStats mutation op: %q", m.Op())
	}
}

// SettingsClient is a client for the Settings schema.
type SettingsClient struct {
	config
}

// NewSettingsClient returns a client for the Settings from the given config.
func NewSettingsClient(c config) *SettingsClient {
	return &SettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `settings.Hooks(f(g(h())))`.
func (c *SettingsClient) Use(hooks ...Hook) {
	c.hooks.Settings = append(c.hooks.Settings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `settings.Intercept(f(g(h())))`.
func (c *SettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Settings = append(c.inters.Settings, interceptors...)
}

// Create returns a builder for creating a Settings entity.
func (c *SettingsClient) Create() *SettingsCreate {
	mutation := newSettingsMutation(c.config, OpCreate)
	return &SettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Settings entities.
func (c *SettingsClient) CreateBulk(builders ...*SettingsCreate) *SettingsCreateBulk {
	return &SettingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SettingsClient) MapCreateBulk(slice any, setFunc func(*SettingsCreate, int)) *SettingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SettingsCreateBulk{err: fmt.Errorf("calling to SettingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SettingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Settings.
func (c *SettingsClient) Update() *SettingsUpdate {
	mutation := newSettingsMutation(c.config, OpUpdate)
	return &SettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SettingsClient) UpdateOne(s *Settings) *SettingsUpdateOne {
	mutation := newSettingsMutation(c.config, OpUpdateOne, withSettings(s))
	return &SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SettingsClient) UpdateOneID(id int) *SettingsUpdateOne {
	mutation := newSettingsMutation(c.config, OpUpdateOne, withSettingsID(id))
	return &SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Settings.
func (c *SettingsClient) Delete() *SettingsDelete {
	mutation := newSettingsMutation(c.config, OpDelete)
	return &SettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SettingsClient) DeleteOne(s *Settings) *SettingsDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SettingsClient) DeleteOneID(id int) *SettingsDeleteOne {
	builder := c.Delete().Where(settings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SettingsDeleteOne{builder}
}

// Query returns a query builder for Settings.
func (c *SettingsClient) Query() *SettingsQuery {
	return &SettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a Settings entity by its id.
func (c *SettingsClient) Get(ctx context.Context, id int) (*Settings, error) {
	return c.Query().Where(settings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SettingsClient) GetX(ctx context.Context, id int) *Settings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SettingsClient) Hooks() []Hook {
	return c.hooks.Settings
}

// Interceptors returns the client interceptors.
func (c *SettingsClient) Interceptors() []Interceptor {
	return c.inters.Settings
}

func (c *SettingsClient) mutate(ctx context.Context, m *SettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Settings mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Game, Guess, PlayerHints, PlayerStats, Settings []ent.Hook
	}
	inters struct {
		Game, Guess, PlayerHints, PlayerStats, Settings []ent.Interceptor
	}
)
