// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/koto/internal/ent/game"
	"jurien.dev/yugen/koto/internal/ent/guess"
)

// GameCreate is the builder for creating a Game entity.
type GameCreate struct {
	config
	mutation *GameMutation
	hooks    []Hook
}

// SetGuildID sets the "guildID" field.
func (gc *GameCreate) SetGuildID(s string) *GameCreate {
	gc.mutation.SetGuildID(s)
	return gc
}

// SetLastMessageID sets the "lastMessageID" field.
func (gc *GameCreate) SetLastMessageID(s string) *GameCreate {
	gc.mutation.SetLastMessageID(s)
	return gc
}

// SetNillableLastMessageID sets the "lastMessageID" field if the given value is not nil.
func (gc *GameCreate) SetNillableLastMessageID(s *string) *GameCreate {
	if s != nil {
		gc.SetLastMessageID(*s)
	}
	return gc
}

// SetWord sets the "word" field.
func (gc *GameCreate) SetWord(s string) *GameCreate {
	gc.mutation.SetWord(s)
	return gc
}

// SetEndingAt sets the "endingAt" field.
func (gc *GameCreate) SetEndingAt(t time.Time) *GameCreate {
	gc.mutation.SetEndingAt(t)
	return gc
}

// SetNumber sets the "number" field.
func (gc *GameCreate) SetNumber(i int) *GameCreate {
	gc.mutation.SetNumber(i)
	return gc
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (gc *GameCreate) SetNillableNumber(i *int) *GameCreate {
	if i != nil {
		gc.SetNumber(*i)
	}
	return gc
}

// SetScheduleStarted sets the "scheduleStarted" field.
func (gc *GameCreate) SetScheduleStarted(b bool) *GameCreate {
	gc.mutation.SetScheduleStarted(b)
	return gc
}

// SetNillableScheduleStarted sets the "scheduleStarted" field if the given value is not nil.
func (gc *GameCreate) SetNillableScheduleStarted(b *bool) *GameCreate {
	if b != nil {
		gc.SetScheduleStarted(*b)
	}
	return gc
}

// SetStatus sets the "status" field.
func (gc *GameCreate) SetStatus(ga game.Status) *GameCreate {
	gc.mutation.SetStatus(ga)
	return gc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (gc *GameCreate) SetNillableStatus(ga *game.Status) *GameCreate {
	if ga != nil {
		gc.SetStatus(*ga)
	}
	return gc
}

// SetMeta sets the "meta" field.
func (gc *GameCreate) SetMeta(jm json.RawMessage) *GameCreate {
	gc.mutation.SetMeta(jm)
	return gc
}

// SetCreatedAt sets the "createdAt" field.
func (gc *GameCreate) SetCreatedAt(t time.Time) *GameCreate {
	gc.mutation.SetCreatedAt(t)
	return gc
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (gc *GameCreate) SetNillableCreatedAt(t *time.Time) *GameCreate {
	if t != nil {
		gc.SetCreatedAt(*t)
	}
	return gc
}

// SetUpdatedAt sets the "updatedAt" field.
func (gc *GameCreate) SetUpdatedAt(t time.Time) *GameCreate {
	gc.mutation.SetUpdatedAt(t)
	return gc
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (gc *GameCreate) SetNillableUpdatedAt(t *time.Time) *GameCreate {
	if t != nil {
		gc.SetUpdatedAt(*t)
	}
	return gc
}

// AddGuessIDs adds the "guesses" edge to the Guess entity by IDs.
func (gc *GameCreate) AddGuessIDs(ids ...int) *GameCreate {
	gc.mutation.AddGuessIDs(ids...)
	return gc
}

// AddGuesses adds the "guesses" edges to the Guess entity.
func (gc *GameCreate) AddGuesses(g ...*Guess) *GameCreate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return gc.AddGuessIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (gc *GameCreate) Mutation() *GameMutation {
	return gc.mutation
}

// Save creates the Game in the database.
func (gc *GameCreate) Save(ctx context.Context) (*Game, error) {
	gc.defaults()
	return withHooks(ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GameCreate) SaveX(ctx context.Context) *Game {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GameCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GameCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gc *GameCreate) defaults() {
	if _, ok := gc.mutation.Number(); !ok {
		v := game.DefaultNumber
		gc.mutation.SetNumber(v)
	}
	if _, ok := gc.mutation.ScheduleStarted(); !ok {
		v := game.DefaultScheduleStarted
		gc.mutation.SetScheduleStarted(v)
	}
	if _, ok := gc.mutation.Status(); !ok {
		v := game.DefaultStatus
		gc.mutation.SetStatus(v)
	}
	if _, ok := gc.mutation.Meta(); !ok {
		v := game.DefaultMeta
		gc.mutation.SetMeta(v)
	}
	if _, ok := gc.mutation.CreatedAt(); !ok {
		v := game.DefaultCreatedAt()
		gc.mutation.SetCreatedAt(v)
	}
	if _, ok := gc.mutation.UpdatedAt(); !ok {
		v := game.DefaultUpdatedAt()
		gc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GameCreate) check() error {
	if _, ok := gc.mutation.GuildID(); !ok {
		return &ValidationError{Name: "guildID", err: errors.New(`ent: missing required field "Game.guildID"`)}
	}
	if _, ok := gc.mutation.Word(); !ok {
		return &ValidationError{Name: "word", err: errors.New(`ent: missing required field "Game.word"`)}
	}
	if _, ok := gc.mutation.EndingAt(); !ok {
		return &ValidationError{Name: "endingAt", err: errors.New(`ent: missing required field "Game.endingAt"`)}
	}
	if _, ok := gc.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Game.number"`)}
	}
	if _, ok := gc.mutation.ScheduleStarted(); !ok {
		return &ValidationError{Name: "scheduleStarted", err: errors.New(`ent: missing required field "Game.scheduleStarted"`)}
	}
	if _, ok := gc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Game.status"`)}
	}
	if v, ok := gc.mutation.Status(); ok {
		if err := game.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Game.status": %w`, err)}
		}
	}
	if _, ok := gc.mutation.Meta(); !ok {
		return &ValidationError{Name: "meta", err: errors.New(`ent: missing required field "Game.meta"`)}
	}
	if _, ok := gc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Game.createdAt"`)}
	}
	if _, ok := gc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Game.updatedAt"`)}
	}
	return nil
}

func (gc *GameCreate) sqlSave(ctx context.Context) (*Game, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GameCreate) createSpec() (*Game, *sqlgraph.CreateSpec) {
	var (
		_node = &Game{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(game.Table, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	)
	if value, ok := gc.mutation.GuildID(); ok {
		_spec.SetField(game.FieldGuildID, field.TypeString, value)
		_node.GuildID = value
	}
	if value, ok := gc.mutation.LastMessageID(); ok {
		_spec.SetField(game.FieldLastMessageID, field.TypeString, value)
		_node.LastMessageID = &value
	}
	if value, ok := gc.mutation.Word(); ok {
		_spec.SetField(game.FieldWord, field.TypeString, value)
		_node.Word = value
	}
	if value, ok := gc.mutation.EndingAt(); ok {
		_spec.SetField(game.FieldEndingAt, field.TypeTime, value)
		_node.EndingAt = value
	}
	if value, ok := gc.mutation.Number(); ok {
		_spec.SetField(game.FieldNumber, field.TypeInt, value)
		_node.Number = value
	}
	if value, ok := gc.mutation.ScheduleStarted(); ok {
		_spec.SetField(game.FieldScheduleStarted, field.TypeBool, value)
		_node.ScheduleStarted = value
	}
	if value, ok := gc.mutation.Status(); ok {
		_spec.SetField(game.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := gc.mutation.Meta(); ok {
		_spec.SetField(game.FieldMeta, field.TypeJSON, value)
		_node.Meta = value
	}
	if value, ok := gc.mutation.CreatedAt(); ok {
		_spec.SetField(game.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := gc.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := gc.mutation.GuessesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.GuessesTable,
			Columns: []string{game.GuessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guess.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GameCreateBulk is the builder for creating many Game entities in bulk.
type GameCreateBulk struct {
	config
	err      error
	builders []*GameCreate
}

// Save creates the Game entities in the database.
func (gcb *GameCreateBulk) Save(ctx context.Context) ([]*Game, error) {
	if gcb.err != nil {
		return nil, gcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Game, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GameMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GameCreateBulk) SaveX(ctx context.Context) []*Game {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GameCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GameCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
