// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"jurien.dev/yugen/koto/internal/ent/game"
)

// Game is the model entity for the Game schema.
type Game struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GuildID holds the value of the "guildID" field.
	GuildID string `json:"guildID,omitempty"`
	// LastMessageID holds the value of the "lastMessageID" field.
	LastMessageID *string `json:"lastMessageID,omitempty"`
	// Word holds the value of the "word" field.
	Word string `json:"word,omitempty"`
	// EndingAt holds the value of the "endingAt" field.
	EndingAt time.Time `json:"endingAt,omitempty"`
	// Number holds the value of the "number" field.
	Number int `json:"number,omitempty"`
	// ScheduleStarted holds the value of the "scheduleStarted" field.
	ScheduleStarted bool `json:"scheduleStarted,omitempty"`
	// Status holds the value of the "status" field.
	Status game.Status `json:"status,omitempty"`
	// Meta holds the value of the "meta" field.
	Meta json.RawMessage `json:"meta,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GameQuery when eager-loading is set.
	Edges        GameEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GameEdges holds the relations/edges for other nodes in the graph.
type GameEdges struct {
	// Guesses holds the value of the guesses edge.
	Guesses []*Guess `json:"guesses,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GuessesOrErr returns the Guesses value or an error if the edge
// was not loaded in eager-loading.
func (e GameEdges) GuessesOrErr() ([]*Guess, error) {
	if e.loadedTypes[0] {
		return e.Guesses, nil
	}
	return nil, &NotLoadedError{edge: "guesses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Game) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case game.FieldMeta:
			values[i] = new([]byte)
		case game.FieldScheduleStarted:
			values[i] = new(sql.NullBool)
		case game.FieldID, game.FieldNumber:
			values[i] = new(sql.NullInt64)
		case game.FieldGuildID, game.FieldLastMessageID, game.FieldWord, game.FieldStatus:
			values[i] = new(sql.NullString)
		case game.FieldEndingAt, game.FieldCreatedAt, game.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Game fields.
func (ga *Game) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case game.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ga.ID = int(value.Int64)
		case game.FieldGuildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guildID", values[i])
			} else if value.Valid {
				ga.GuildID = value.String
			}
		case game.FieldLastMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lastMessageID", values[i])
			} else if value.Valid {
				ga.LastMessageID = new(string)
				*ga.LastMessageID = value.String
			}
		case game.FieldWord:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field word", values[i])
			} else if value.Valid {
				ga.Word = value.String
			}
		case game.FieldEndingAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field endingAt", values[i])
			} else if value.Valid {
				ga.EndingAt = value.Time
			}
		case game.FieldNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				ga.Number = int(value.Int64)
			}
		case game.FieldScheduleStarted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field scheduleStarted", values[i])
			} else if value.Valid {
				ga.ScheduleStarted = value.Bool
			}
		case game.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ga.Status = game.Status(value.String)
			}
		case game.FieldMeta:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field meta", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ga.Meta); err != nil {
					return fmt.Errorf("unmarshal field meta: %w", err)
				}
			}
		case game.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				ga.CreatedAt = value.Time
			}
		case game.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				ga.UpdatedAt = value.Time
			}
		default:
			ga.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Game.
// This includes values selected through modifiers, order, etc.
func (ga *Game) Value(name string) (ent.Value, error) {
	return ga.selectValues.Get(name)
}

// QueryGuesses queries the "guesses" edge of the Game entity.
func (ga *Game) QueryGuesses() *GuessQuery {
	return NewGameClient(ga.config).QueryGuesses(ga)
}

// Update returns a builder for updating this Game.
// Note that you need to call Game.Unwrap() before calling this method if this Game
// was returned from a transaction, and the transaction was committed or rolled back.
func (ga *Game) Update() *GameUpdateOne {
	return NewGameClient(ga.config).UpdateOne(ga)
}

// Unwrap unwraps the Game entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ga *Game) Unwrap() *Game {
	_tx, ok := ga.config.driver.(*txDriver)
	if !ok {
		panic("ent: Game is not a transactional entity")
	}
	ga.config.driver = _tx.drv
	return ga
}

// String implements the fmt.Stringer.
func (ga *Game) String() string {
	var builder strings.Builder
	builder.WriteString("Game(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ga.ID))
	builder.WriteString("guildID=")
	builder.WriteString(ga.GuildID)
	builder.WriteString(", ")
	if v := ga.LastMessageID; v != nil {
		builder.WriteString("lastMessageID=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("word=")
	builder.WriteString(ga.Word)
	builder.WriteString(", ")
	builder.WriteString("endingAt=")
	builder.WriteString(ga.EndingAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("number=")
	builder.WriteString(fmt.Sprintf("%v", ga.Number))
	builder.WriteString(", ")
	builder.WriteString("scheduleStarted=")
	builder.WriteString(fmt.Sprintf("%v", ga.ScheduleStarted))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ga.Status))
	builder.WriteString(", ")
	builder.WriteString("meta=")
	builder.WriteString(fmt.Sprintf("%v", ga.Meta))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(ga.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(ga.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Games is a parsable slice of Game.
type Games []*Game
