// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/koto/internal/ent/playerstats"
	"jurien.dev/yugen/koto/internal/ent/predicate"
)

// PlayerStatsUpdate is the builder for updating PlayerStats entities.
type PlayerStatsUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerStatsMutation
}

// Where appends a list predicates to the PlayerStatsUpdate builder.
func (psu *PlayerStatsUpdate) Where(ps ...predicate.PlayerStats) *PlayerStatsUpdate {
	psu.mutation.Where(ps...)
	return psu
}

// SetUserID sets the "userID" field.
func (psu *PlayerStatsUpdate) SetUserID(s string) *PlayerStatsUpdate {
	psu.mutation.SetUserID(s)
	return psu
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (psu *PlayerStatsUpdate) SetNillableUserID(s *string) *PlayerStatsUpdate {
	if s != nil {
		psu.SetUserID(*s)
	}
	return psu
}

// SetGuildID sets the "guildID" field.
func (psu *PlayerStatsUpdate) SetGuildID(s string) *PlayerStatsUpdate {
	psu.mutation.SetGuildID(s)
	return psu
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (psu *PlayerStatsUpdate) SetNillableGuildID(s *string) *PlayerStatsUpdate {
	if s != nil {
		psu.SetGuildID(*s)
	}
	return psu
}

// SetInGuild sets the "inGuild" field.
func (psu *PlayerStatsUpdate) SetInGuild(b bool) *PlayerStatsUpdate {
	psu.mutation.SetInGuild(b)
	return psu
}

// SetNillableInGuild sets the "inGuild" field if the given value is not nil.
func (psu *PlayerStatsUpdate) SetNillableInGuild(b *bool) *PlayerStatsUpdate {
	if b != nil {
		psu.SetInGuild(*b)
	}
	return psu
}

// SetPoints sets the "points" field.
func (psu *PlayerStatsUpdate) SetPoints(i int) *PlayerStatsUpdate {
	psu.mutation.ResetPoints()
	psu.mutation.SetPoints(i)
	return psu
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (psu *PlayerStatsUpdate) SetNillablePoints(i *int) *PlayerStatsUpdate {
	if i != nil {
		psu.SetPoints(*i)
	}
	return psu
}

// AddPoints adds i to the "points" field.
func (psu *PlayerStatsUpdate) AddPoints(i int) *PlayerStatsUpdate {
	psu.mutation.AddPoints(i)
	return psu
}

// SetParticipated sets the "participated" field.
func (psu *PlayerStatsUpdate) SetParticipated(i int) *PlayerStatsUpdate {
	psu.mutation.ResetParticipated()
	psu.mutation.SetParticipated(i)
	return psu
}

// SetNillableParticipated sets the "participated" field if the given value is not nil.
func (psu *PlayerStatsUpdate) SetNillableParticipated(i *int) *PlayerStatsUpdate {
	if i != nil {
		psu.SetParticipated(*i)
	}
	return psu
}

// AddParticipated adds i to the "participated" field.
func (psu *PlayerStatsUpdate) AddParticipated(i int) *PlayerStatsUpdate {
	psu.mutation.AddParticipated(i)
	return psu
}

// SetWins sets the "wins" field.
func (psu *PlayerStatsUpdate) SetWins(i int) *PlayerStatsUpdate {
	psu.mutation.ResetWins()
	psu.mutation.SetWins(i)
	return psu
}

// SetNillableWins sets the "wins" field if the given value is not nil.
func (psu *PlayerStatsUpdate) SetNillableWins(i *int) *PlayerStatsUpdate {
	if i != nil {
		psu.SetWins(*i)
	}
	return psu
}

// AddWins adds i to the "wins" field.
func (psu *PlayerStatsUpdate) AddWins(i int) *PlayerStatsUpdate {
	psu.mutation.AddWins(i)
	return psu
}

// SetUpdatedAt sets the "updatedAt" field.
func (psu *PlayerStatsUpdate) SetUpdatedAt(t time.Time) *PlayerStatsUpdate {
	psu.mutation.SetUpdatedAt(t)
	return psu
}

// Mutation returns the PlayerStatsMutation object of the builder.
func (psu *PlayerStatsUpdate) Mutation() *PlayerStatsMutation {
	return psu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (psu *PlayerStatsUpdate) Save(ctx context.Context) (int, error) {
	psu.defaults()
	return withHooks(ctx, psu.sqlSave, psu.mutation, psu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psu *PlayerStatsUpdate) SaveX(ctx context.Context) int {
	affected, err := psu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (psu *PlayerStatsUpdate) Exec(ctx context.Context) error {
	_, err := psu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psu *PlayerStatsUpdate) ExecX(ctx context.Context) {
	if err := psu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psu *PlayerStatsUpdate) defaults() {
	if _, ok := psu.mutation.UpdatedAt(); !ok {
		v := playerstats.UpdateDefaultUpdatedAt()
		psu.mutation.SetUpdatedAt(v)
	}
}

func (psu *PlayerStatsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(playerstats.Table, playerstats.Columns, sqlgraph.NewFieldSpec(playerstats.FieldID, field.TypeInt))
	if ps := psu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psu.mutation.UserID(); ok {
		_spec.SetField(playerstats.FieldUserID, field.TypeString, value)
	}
	if value, ok := psu.mutation.GuildID(); ok {
		_spec.SetField(playerstats.FieldGuildID, field.TypeString, value)
	}
	if value, ok := psu.mutation.InGuild(); ok {
		_spec.SetField(playerstats.FieldInGuild, field.TypeBool, value)
	}
	if value, ok := psu.mutation.Points(); ok {
		_spec.SetField(playerstats.FieldPoints, field.TypeInt, value)
	}
	if value, ok := psu.mutation.AddedPoints(); ok {
		_spec.AddField(playerstats.FieldPoints, field.TypeInt, value)
	}
	if value, ok := psu.mutation.Participated(); ok {
		_spec.SetField(playerstats.FieldParticipated, field.TypeInt, value)
	}
	if value, ok := psu.mutation.AddedParticipated(); ok {
		_spec.AddField(playerstats.FieldParticipated, field.TypeInt, value)
	}
	if value, ok := psu.mutation.Wins(); ok {
		_spec.SetField(playerstats.FieldWins, field.TypeInt, value)
	}
	if value, ok := psu.mutation.AddedWins(); ok {
		_spec.AddField(playerstats.FieldWins, field.TypeInt, value)
	}
	if value, ok := psu.mutation.UpdatedAt(); ok {
		_spec.SetField(playerstats.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, psu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	psu.mutation.done = true
	return n, nil
}

// PlayerStatsUpdateOne is the builder for updating a single PlayerStats entity.
type PlayerStatsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerStatsMutation
}

// SetUserID sets the "userID" field.
func (psuo *PlayerStatsUpdateOne) SetUserID(s string) *PlayerStatsUpdateOne {
	psuo.mutation.SetUserID(s)
	return psuo
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (psuo *PlayerStatsUpdateOne) SetNillableUserID(s *string) *PlayerStatsUpdateOne {
	if s != nil {
		psuo.SetUserID(*s)
	}
	return psuo
}

// SetGuildID sets the "guildID" field.
func (psuo *PlayerStatsUpdateOne) SetGuildID(s string) *PlayerStatsUpdateOne {
	psuo.mutation.SetGuildID(s)
	return psuo
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (psuo *PlayerStatsUpdateOne) SetNillableGuildID(s *string) *PlayerStatsUpdateOne {
	if s != nil {
		psuo.SetGuildID(*s)
	}
	return psuo
}

// SetInGuild sets the "inGuild" field.
func (psuo *PlayerStatsUpdateOne) SetInGuild(b bool) *PlayerStatsUpdateOne {
	psuo.mutation.SetInGuild(b)
	return psuo
}

// SetNillableInGuild sets the "inGuild" field if the given value is not nil.
func (psuo *PlayerStatsUpdateOne) SetNillableInGuild(b *bool) *PlayerStatsUpdateOne {
	if b != nil {
		psuo.SetInGuild(*b)
	}
	return psuo
}

// SetPoints sets the "points" field.
func (psuo *PlayerStatsUpdateOne) SetPoints(i int) *PlayerStatsUpdateOne {
	psuo.mutation.ResetPoints()
	psuo.mutation.SetPoints(i)
	return psuo
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (psuo *PlayerStatsUpdateOne) SetNillablePoints(i *int) *PlayerStatsUpdateOne {
	if i != nil {
		psuo.SetPoints(*i)
	}
	return psuo
}

// AddPoints adds i to the "points" field.
func (psuo *PlayerStatsUpdateOne) AddPoints(i int) *PlayerStatsUpdateOne {
	psuo.mutation.AddPoints(i)
	return psuo
}

// SetParticipated sets the "participated" field.
func (psuo *PlayerStatsUpdateOne) SetParticipated(i int) *PlayerStatsUpdateOne {
	psuo.mutation.ResetParticipated()
	psuo.mutation.SetParticipated(i)
	return psuo
}

// SetNillableParticipated sets the "participated" field if the given value is not nil.
func (psuo *PlayerStatsUpdateOne) SetNillableParticipated(i *int) *PlayerStatsUpdateOne {
	if i != nil {
		psuo.SetParticipated(*i)
	}
	return psuo
}

// AddParticipated adds i to the "participated" field.
func (psuo *PlayerStatsUpdateOne) AddParticipated(i int) *PlayerStatsUpdateOne {
	psuo.mutation.AddParticipated(i)
	return psuo
}

// SetWins sets the "wins" field.
func (psuo *PlayerStatsUpdateOne) SetWins(i int) *PlayerStatsUpdateOne {
	psuo.mutation.ResetWins()
	psuo.mutation.SetWins(i)
	return psuo
}

// SetNillableWins sets the "wins" field if the given value is not nil.
func (psuo *PlayerStatsUpdateOne) SetNillableWins(i *int) *PlayerStatsUpdateOne {
	if i != nil {
		psuo.SetWins(*i)
	}
	return psuo
}

// AddWins adds i to the "wins" field.
func (psuo *PlayerStatsUpdateOne) AddWins(i int) *PlayerStatsUpdateOne {
	psuo.mutation.AddWins(i)
	return psuo
}

// SetUpdatedAt sets the "updatedAt" field.
func (psuo *PlayerStatsUpdateOne) SetUpdatedAt(t time.Time) *PlayerStatsUpdateOne {
	psuo.mutation.SetUpdatedAt(t)
	return psuo
}

// Mutation returns the PlayerStatsMutation object of the builder.
func (psuo *PlayerStatsUpdateOne) Mutation() *PlayerStatsMutation {
	return psuo.mutation
}

// Where appends a list predicates to the PlayerStatsUpdate builder.
func (psuo *PlayerStatsUpdateOne) Where(ps ...predicate.PlayerStats) *PlayerStatsUpdateOne {
	psuo.mutation.Where(ps...)
	return psuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (psuo *PlayerStatsUpdateOne) Select(field string, fields ...string) *PlayerStatsUpdateOne {
	psuo.fields = append([]string{field}, fields...)
	return psuo
}

// Save executes the query and returns the updated PlayerStats entity.
func (psuo *PlayerStatsUpdateOne) Save(ctx context.Context) (*PlayerStats, error) {
	psuo.defaults()
	return withHooks(ctx, psuo.sqlSave, psuo.mutation, psuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psuo *PlayerStatsUpdateOne) SaveX(ctx context.Context) *PlayerStats {
	node, err := psuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (psuo *PlayerStatsUpdateOne) Exec(ctx context.Context) error {
	_, err := psuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psuo *PlayerStatsUpdateOne) ExecX(ctx context.Context) {
	if err := psuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psuo *PlayerStatsUpdateOne) defaults() {
	if _, ok := psuo.mutation.UpdatedAt(); !ok {
		v := playerstats.UpdateDefaultUpdatedAt()
		psuo.mutation.SetUpdatedAt(v)
	}
}

func (psuo *PlayerStatsUpdateOne) sqlSave(ctx context.Context) (_node *PlayerStats, err error) {
	_spec := sqlgraph.NewUpdateSpec(playerstats.Table, playerstats.Columns, sqlgraph.NewFieldSpec(playerstats.FieldID, field.TypeInt))
	id, ok := psuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlayerStats.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := psuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playerstats.FieldID)
		for _, f := range fields {
			if !playerstats.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playerstats.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := psuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psuo.mutation.UserID(); ok {
		_spec.SetField(playerstats.FieldUserID, field.TypeString, value)
	}
	if value, ok := psuo.mutation.GuildID(); ok {
		_spec.SetField(playerstats.FieldGuildID, field.TypeString, value)
	}
	if value, ok := psuo.mutation.InGuild(); ok {
		_spec.SetField(playerstats.FieldInGuild, field.TypeBool, value)
	}
	if value, ok := psuo.mutation.Points(); ok {
		_spec.SetField(playerstats.FieldPoints, field.TypeInt, value)
	}
	if value, ok := psuo.mutation.AddedPoints(); ok {
		_spec.AddField(playerstats.FieldPoints, field.TypeInt, value)
	}
	if value, ok := psuo.mutation.Participated(); ok {
		_spec.SetField(playerstats.FieldParticipated, field.TypeInt, value)
	}
	if value, ok := psuo.mutation.AddedParticipated(); ok {
		_spec.AddField(playerstats.FieldParticipated, field.TypeInt, value)
	}
	if value, ok := psuo.mutation.Wins(); ok {
		_spec.SetField(playerstats.FieldWins, field.TypeInt, value)
	}
	if value, ok := psuo.mutation.AddedWins(); ok {
		_spec.AddField(playerstats.FieldWins, field.TypeInt, value)
	}
	if value, ok := psuo.mutation.UpdatedAt(); ok {
		_spec.SetField(playerstats.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PlayerStats{config: psuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, psuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	psuo.mutation.done = true
	return _node, nil
}
