// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"jurien.dev/yugen/koto/internal/ent/playerhints"
)

// PlayerHints is the model entity for the PlayerHints schema.
type PlayerHints struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "userID" field.
	UserID string `json:"userID,omitempty"`
	// Hints holds the value of the "hints" field.
	Hints float64 `json:"hints,omitempty"`
	// MaxHints holds the value of the "maxHints" field.
	MaxHints float64 `json:"maxHints,omitempty"`
	// LastVoteTime holds the value of the "lastVoteTime" field.
	LastVoteTime *time.Time `json:"lastVoteTime,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt    time.Time `json:"updatedAt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlayerHints) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playerhints.FieldHints, playerhints.FieldMaxHints:
			values[i] = new(sql.NullFloat64)
		case playerhints.FieldID:
			values[i] = new(sql.NullInt64)
		case playerhints.FieldUserID:
			values[i] = new(sql.NullString)
		case playerhints.FieldLastVoteTime, playerhints.FieldCreatedAt, playerhints.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlayerHints fields.
func (ph *PlayerHints) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playerhints.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ph.ID = int(value.Int64)
		case playerhints.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field userID", values[i])
			} else if value.Valid {
				ph.UserID = value.String
			}
		case playerhints.FieldHints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hints", values[i])
			} else if value.Valid {
				ph.Hints = value.Float64
			}
		case playerhints.FieldMaxHints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field maxHints", values[i])
			} else if value.Valid {
				ph.MaxHints = value.Float64
			}
		case playerhints.FieldLastVoteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lastVoteTime", values[i])
			} else if value.Valid {
				ph.LastVoteTime = new(time.Time)
				*ph.LastVoteTime = value.Time
			}
		case playerhints.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				ph.CreatedAt = value.Time
			}
		case playerhints.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				ph.UpdatedAt = value.Time
			}
		default:
			ph.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlayerHints.
// This includes values selected through modifiers, order, etc.
func (ph *PlayerHints) Value(name string) (ent.Value, error) {
	return ph.selectValues.Get(name)
}

// Update returns a builder for updating this PlayerHints.
// Note that you need to call PlayerHints.Unwrap() before calling this method if this PlayerHints
// was returned from a transaction, and the transaction was committed or rolled back.
func (ph *PlayerHints) Update() *PlayerHintsUpdateOne {
	return NewPlayerHintsClient(ph.config).UpdateOne(ph)
}

// Unwrap unwraps the PlayerHints entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ph *PlayerHints) Unwrap() *PlayerHints {
	_tx, ok := ph.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlayerHints is not a transactional entity")
	}
	ph.config.driver = _tx.drv
	return ph
}

// String implements the fmt.Stringer.
func (ph *PlayerHints) String() string {
	var builder strings.Builder
	builder.WriteString("PlayerHints(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ph.ID))
	builder.WriteString("userID=")
	builder.WriteString(ph.UserID)
	builder.WriteString(", ")
	builder.WriteString("hints=")
	builder.WriteString(fmt.Sprintf("%v", ph.Hints))
	builder.WriteString(", ")
	builder.WriteString("maxHints=")
	builder.WriteString(fmt.Sprintf("%v", ph.MaxHints))
	builder.WriteString(", ")
	if v := ph.LastVoteTime; v != nil {
		builder.WriteString("lastVoteTime=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(ph.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(ph.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlayerHintsSlice is a parsable slice of PlayerHints.
type PlayerHintsSlice []*PlayerHints
