// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/koto/internal/ent/playerhints"
	"jurien.dev/yugen/koto/internal/ent/predicate"
)

// PlayerHintsDelete is the builder for deleting a PlayerHints entity.
type PlayerHintsDelete struct {
	config
	hooks    []Hook
	mutation *PlayerHintsMutation
}

// Where appends a list predicates to the PlayerHintsDelete builder.
func (phd *PlayerHintsDelete) Where(ps ...predicate.PlayerHints) *PlayerHintsDelete {
	phd.mutation.Where(ps...)
	return phd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (phd *PlayerHintsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, phd.sqlExec, phd.mutation, phd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (phd *PlayerHintsDelete) ExecX(ctx context.Context) int {
	n, err := phd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (phd *PlayerHintsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(playerhints.Table, sqlgraph.NewFieldSpec(playerhints.FieldID, field.TypeInt))
	if ps := phd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, phd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	phd.mutation.done = true
	return affected, err
}

// PlayerHintsDeleteOne is the builder for deleting a single PlayerHints entity.
type PlayerHintsDeleteOne struct {
	phd *PlayerHintsDelete
}

// Where appends a list predicates to the PlayerHintsDelete builder.
func (phdo *PlayerHintsDeleteOne) Where(ps ...predicate.PlayerHints) *PlayerHintsDeleteOne {
	phdo.phd.mutation.Where(ps...)
	return phdo
}

// Exec executes the deletion query.
func (phdo *PlayerHintsDeleteOne) Exec(ctx context.Context) error {
	n, err := phdo.phd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{playerhints.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (phdo *PlayerHintsDeleteOne) ExecX(ctx context.Context) {
	if err := phdo.Exec(ctx); err != nil {
		panic(err)
	}
}
