// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/koto/internal/ent/predicate"
	"jurien.dev/yugen/koto/internal/ent/settings"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (su *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetGuildID sets the "guildID" field.
func (su *SettingsUpdate) SetGuildID(s string) *SettingsUpdate {
	su.mutation.SetGuildID(s)
	return su
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableGuildID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetGuildID(*s)
	}
	return su
}

// SetBotUpdatesChannelID sets the "botUpdatesChannelID" field.
func (su *SettingsUpdate) SetBotUpdatesChannelID(s string) *SettingsUpdate {
	su.mutation.SetBotUpdatesChannelID(s)
	return su
}

// SetNillableBotUpdatesChannelID sets the "botUpdatesChannelID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableBotUpdatesChannelID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetBotUpdatesChannelID(*s)
	}
	return su
}

// ClearBotUpdatesChannelID clears the value of the "botUpdatesChannelID" field.
func (su *SettingsUpdate) ClearBotUpdatesChannelID() *SettingsUpdate {
	su.mutation.ClearBotUpdatesChannelID()
	return su
}

// SetChannelID sets the "channelID" field.
func (su *SettingsUpdate) SetChannelID(s string) *SettingsUpdate {
	su.mutation.SetChannelID(s)
	return su
}

// SetNillableChannelID sets the "channelID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableChannelID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetChannelID(*s)
	}
	return su
}

// ClearChannelID clears the value of the "channelID" field.
func (su *SettingsUpdate) ClearChannelID() *SettingsUpdate {
	su.mutation.ClearChannelID()
	return su
}

// SetPingRoleID sets the "pingRoleID" field.
func (su *SettingsUpdate) SetPingRoleID(s string) *SettingsUpdate {
	su.mutation.SetPingRoleID(s)
	return su
}

// SetNillablePingRoleID sets the "pingRoleID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillablePingRoleID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetPingRoleID(*s)
	}
	return su
}

// ClearPingRoleID clears the value of the "pingRoleID" field.
func (su *SettingsUpdate) ClearPingRoleID() *SettingsUpdate {
	su.mutation.ClearPingRoleID()
	return su
}

// SetPingOnlyNew sets the "pingOnlyNew" field.
func (su *SettingsUpdate) SetPingOnlyNew(b bool) *SettingsUpdate {
	su.mutation.SetPingOnlyNew(b)
	return su
}

// SetNillablePingOnlyNew sets the "pingOnlyNew" field if the given value is not nil.
func (su *SettingsUpdate) SetNillablePingOnlyNew(b *bool) *SettingsUpdate {
	if b != nil {
		su.SetPingOnlyNew(*b)
	}
	return su
}

// SetMembersCanStart sets the "membersCanStart" field.
func (su *SettingsUpdate) SetMembersCanStart(b bool) *SettingsUpdate {
	su.mutation.SetMembersCanStart(b)
	return su
}

// SetNillableMembersCanStart sets the "membersCanStart" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableMembersCanStart(b *bool) *SettingsUpdate {
	if b != nil {
		su.SetMembersCanStart(*b)
	}
	return su
}

// SetCooldown sets the "cooldown" field.
func (su *SettingsUpdate) SetCooldown(i int) *SettingsUpdate {
	su.mutation.ResetCooldown()
	su.mutation.SetCooldown(i)
	return su
}

// SetNillableCooldown sets the "cooldown" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableCooldown(i *int) *SettingsUpdate {
	if i != nil {
		su.SetCooldown(*i)
	}
	return su
}

// AddCooldown adds i to the "cooldown" field.
func (su *SettingsUpdate) AddCooldown(i int) *SettingsUpdate {
	su.mutation.AddCooldown(i)
	return su
}

// SetEnableBackToBackCooldown sets the "enableBackToBackCooldown" field.
func (su *SettingsUpdate) SetEnableBackToBackCooldown(b bool) *SettingsUpdate {
	su.mutation.SetEnableBackToBackCooldown(b)
	return su
}

// SetNillableEnableBackToBackCooldown sets the "enableBackToBackCooldown" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableEnableBackToBackCooldown(b *bool) *SettingsUpdate {
	if b != nil {
		su.SetEnableBackToBackCooldown(*b)
	}
	return su
}

// SetBackToBackCooldown sets the "backToBackCooldown" field.
func (su *SettingsUpdate) SetBackToBackCooldown(i int) *SettingsUpdate {
	su.mutation.ResetBackToBackCooldown()
	su.mutation.SetBackToBackCooldown(i)
	return su
}

// SetNillableBackToBackCooldown sets the "backToBackCooldown" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableBackToBackCooldown(i *int) *SettingsUpdate {
	if i != nil {
		su.SetBackToBackCooldown(*i)
	}
	return su
}

// AddBackToBackCooldown adds i to the "backToBackCooldown" field.
func (su *SettingsUpdate) AddBackToBackCooldown(i int) *SettingsUpdate {
	su.mutation.AddBackToBackCooldown(i)
	return su
}

// SetInformCooldownAfterGuess sets the "informCooldownAfterGuess" field.
func (su *SettingsUpdate) SetInformCooldownAfterGuess(b bool) *SettingsUpdate {
	su.mutation.SetInformCooldownAfterGuess(b)
	return su
}

// SetNillableInformCooldownAfterGuess sets the "informCooldownAfterGuess" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableInformCooldownAfterGuess(b *bool) *SettingsUpdate {
	if b != nil {
		su.SetInformCooldownAfterGuess(*b)
	}
	return su
}

// SetFrequency sets the "frequency" field.
func (su *SettingsUpdate) SetFrequency(i int) *SettingsUpdate {
	su.mutation.ResetFrequency()
	su.mutation.SetFrequency(i)
	return su
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableFrequency(i *int) *SettingsUpdate {
	if i != nil {
		su.SetFrequency(*i)
	}
	return su
}

// AddFrequency adds i to the "frequency" field.
func (su *SettingsUpdate) AddFrequency(i int) *SettingsUpdate {
	su.mutation.AddFrequency(i)
	return su
}

// SetTimeLimit sets the "timeLimit" field.
func (su *SettingsUpdate) SetTimeLimit(i int) *SettingsUpdate {
	su.mutation.ResetTimeLimit()
	su.mutation.SetTimeLimit(i)
	return su
}

// SetNillableTimeLimit sets the "timeLimit" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableTimeLimit(i *int) *SettingsUpdate {
	if i != nil {
		su.SetTimeLimit(*i)
	}
	return su
}

// AddTimeLimit adds i to the "timeLimit" field.
func (su *SettingsUpdate) AddTimeLimit(i int) *SettingsUpdate {
	su.mutation.AddTimeLimit(i)
	return su
}

// SetAutoStart sets the "autoStart" field.
func (su *SettingsUpdate) SetAutoStart(b bool) *SettingsUpdate {
	su.mutation.SetAutoStart(b)
	return su
}

// SetNillableAutoStart sets the "autoStart" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableAutoStart(b *bool) *SettingsUpdate {
	if b != nil {
		su.SetAutoStart(*b)
	}
	return su
}

// SetStartAfterFirstGuess sets the "startAfterFirstGuess" field.
func (su *SettingsUpdate) SetStartAfterFirstGuess(b bool) *SettingsUpdate {
	su.mutation.SetStartAfterFirstGuess(b)
	return su
}

// SetNillableStartAfterFirstGuess sets the "startAfterFirstGuess" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableStartAfterFirstGuess(b *bool) *SettingsUpdate {
	if b != nil {
		su.SetStartAfterFirstGuess(*b)
	}
	return su
}

// SetHints sets the "hints" field.
func (su *SettingsUpdate) SetHints(f float64) *SettingsUpdate {
	su.mutation.ResetHints()
	su.mutation.SetHints(f)
	return su
}

// SetNillableHints sets the "hints" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableHints(f *float64) *SettingsUpdate {
	if f != nil {
		su.SetHints(*f)
	}
	return su
}

// AddHints adds f to the "hints" field.
func (su *SettingsUpdate) AddHints(f float64) *SettingsUpdate {
	su.mutation.AddHints(f)
	return su
}

// SetMaxHints sets the "maxHints" field.
func (su *SettingsUpdate) SetMaxHints(f float64) *SettingsUpdate {
	su.mutation.ResetMaxHints()
	su.mutation.SetMaxHints(f)
	return su
}

// SetNillableMaxHints sets the "maxHints" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableMaxHints(f *float64) *SettingsUpdate {
	if f != nil {
		su.SetMaxHints(*f)
	}
	return su
}

// AddMaxHints adds f to the "maxHints" field.
func (su *SettingsUpdate) AddMaxHints(f float64) *SettingsUpdate {
	su.mutation.AddMaxHints(f)
	return su
}

// SetHintsUsed sets the "hintsUsed" field.
func (su *SettingsUpdate) SetHintsUsed(f float64) *SettingsUpdate {
	su.mutation.ResetHintsUsed()
	su.mutation.SetHintsUsed(f)
	return su
}

// SetNillableHintsUsed sets the "hintsUsed" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableHintsUsed(f *float64) *SettingsUpdate {
	if f != nil {
		su.SetHintsUsed(*f)
	}
	return su
}

// AddHintsUsed adds f to the "hintsUsed" field.
func (su *SettingsUpdate) AddHintsUsed(f float64) *SettingsUpdate {
	su.mutation.AddHintsUsed(f)
	return su
}

// SetUpdatedAt sets the "updatedAt" field.
func (su *SettingsUpdate) SetUpdatedAt(t time.Time) *SettingsUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// Mutation returns the SettingsMutation object of the builder.
func (su *SettingsUpdate) Mutation() *SettingsMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SettingsUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SettingsUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SettingsUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

func (su *SettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.GuildID(); ok {
		_spec.SetField(settings.FieldGuildID, field.TypeString, value)
	}
	if value, ok := su.mutation.BotUpdatesChannelID(); ok {
		_spec.SetField(settings.FieldBotUpdatesChannelID, field.TypeString, value)
	}
	if su.mutation.BotUpdatesChannelIDCleared() {
		_spec.ClearField(settings.FieldBotUpdatesChannelID, field.TypeString)
	}
	if value, ok := su.mutation.ChannelID(); ok {
		_spec.SetField(settings.FieldChannelID, field.TypeString, value)
	}
	if su.mutation.ChannelIDCleared() {
		_spec.ClearField(settings.FieldChannelID, field.TypeString)
	}
	if value, ok := su.mutation.PingRoleID(); ok {
		_spec.SetField(settings.FieldPingRoleID, field.TypeString, value)
	}
	if su.mutation.PingRoleIDCleared() {
		_spec.ClearField(settings.FieldPingRoleID, field.TypeString)
	}
	if value, ok := su.mutation.PingOnlyNew(); ok {
		_spec.SetField(settings.FieldPingOnlyNew, field.TypeBool, value)
	}
	if value, ok := su.mutation.MembersCanStart(); ok {
		_spec.SetField(settings.FieldMembersCanStart, field.TypeBool, value)
	}
	if value, ok := su.mutation.Cooldown(); ok {
		_spec.SetField(settings.FieldCooldown, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedCooldown(); ok {
		_spec.AddField(settings.FieldCooldown, field.TypeInt, value)
	}
	if value, ok := su.mutation.EnableBackToBackCooldown(); ok {
		_spec.SetField(settings.FieldEnableBackToBackCooldown, field.TypeBool, value)
	}
	if value, ok := su.mutation.BackToBackCooldown(); ok {
		_spec.SetField(settings.FieldBackToBackCooldown, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedBackToBackCooldown(); ok {
		_spec.AddField(settings.FieldBackToBackCooldown, field.TypeInt, value)
	}
	if value, ok := su.mutation.InformCooldownAfterGuess(); ok {
		_spec.SetField(settings.FieldInformCooldownAfterGuess, field.TypeBool, value)
	}
	if value, ok := su.mutation.Frequency(); ok {
		_spec.SetField(settings.FieldFrequency, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedFrequency(); ok {
		_spec.AddField(settings.FieldFrequency, field.TypeInt, value)
	}
	if value, ok := su.mutation.TimeLimit(); ok {
		_spec.SetField(settings.FieldTimeLimit, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedTimeLimit(); ok {
		_spec.AddField(settings.FieldTimeLimit, field.TypeInt, value)
	}
	if value, ok := su.mutation.AutoStart(); ok {
		_spec.SetField(settings.FieldAutoStart, field.TypeBool, value)
	}
	if value, ok := su.mutation.StartAfterFirstGuess(); ok {
		_spec.SetField(settings.FieldStartAfterFirstGuess, field.TypeBool, value)
	}
	if value, ok := su.mutation.Hints(); ok {
		_spec.SetField(settings.FieldHints, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedHints(); ok {
		_spec.AddField(settings.FieldHints, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.MaxHints(); ok {
		_spec.SetField(settings.FieldMaxHints, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedMaxHints(); ok {
		_spec.AddField(settings.FieldMaxHints, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.HintsUsed(); ok {
		_spec.SetField(settings.FieldHintsUsed, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedHintsUsed(); ok {
		_spec.AddField(settings.FieldHintsUsed, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetGuildID sets the "guildID" field.
func (suo *SettingsUpdateOne) SetGuildID(s string) *SettingsUpdateOne {
	suo.mutation.SetGuildID(s)
	return suo
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableGuildID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetGuildID(*s)
	}
	return suo
}

// SetBotUpdatesChannelID sets the "botUpdatesChannelID" field.
func (suo *SettingsUpdateOne) SetBotUpdatesChannelID(s string) *SettingsUpdateOne {
	suo.mutation.SetBotUpdatesChannelID(s)
	return suo
}

// SetNillableBotUpdatesChannelID sets the "botUpdatesChannelID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableBotUpdatesChannelID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetBotUpdatesChannelID(*s)
	}
	return suo
}

// ClearBotUpdatesChannelID clears the value of the "botUpdatesChannelID" field.
func (suo *SettingsUpdateOne) ClearBotUpdatesChannelID() *SettingsUpdateOne {
	suo.mutation.ClearBotUpdatesChannelID()
	return suo
}

// SetChannelID sets the "channelID" field.
func (suo *SettingsUpdateOne) SetChannelID(s string) *SettingsUpdateOne {
	suo.mutation.SetChannelID(s)
	return suo
}

// SetNillableChannelID sets the "channelID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableChannelID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetChannelID(*s)
	}
	return suo
}

// ClearChannelID clears the value of the "channelID" field.
func (suo *SettingsUpdateOne) ClearChannelID() *SettingsUpdateOne {
	suo.mutation.ClearChannelID()
	return suo
}

// SetPingRoleID sets the "pingRoleID" field.
func (suo *SettingsUpdateOne) SetPingRoleID(s string) *SettingsUpdateOne {
	suo.mutation.SetPingRoleID(s)
	return suo
}

// SetNillablePingRoleID sets the "pingRoleID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillablePingRoleID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetPingRoleID(*s)
	}
	return suo
}

// ClearPingRoleID clears the value of the "pingRoleID" field.
func (suo *SettingsUpdateOne) ClearPingRoleID() *SettingsUpdateOne {
	suo.mutation.ClearPingRoleID()
	return suo
}

// SetPingOnlyNew sets the "pingOnlyNew" field.
func (suo *SettingsUpdateOne) SetPingOnlyNew(b bool) *SettingsUpdateOne {
	suo.mutation.SetPingOnlyNew(b)
	return suo
}

// SetNillablePingOnlyNew sets the "pingOnlyNew" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillablePingOnlyNew(b *bool) *SettingsUpdateOne {
	if b != nil {
		suo.SetPingOnlyNew(*b)
	}
	return suo
}

// SetMembersCanStart sets the "membersCanStart" field.
func (suo *SettingsUpdateOne) SetMembersCanStart(b bool) *SettingsUpdateOne {
	suo.mutation.SetMembersCanStart(b)
	return suo
}

// SetNillableMembersCanStart sets the "membersCanStart" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableMembersCanStart(b *bool) *SettingsUpdateOne {
	if b != nil {
		suo.SetMembersCanStart(*b)
	}
	return suo
}

// SetCooldown sets the "cooldown" field.
func (suo *SettingsUpdateOne) SetCooldown(i int) *SettingsUpdateOne {
	suo.mutation.ResetCooldown()
	suo.mutation.SetCooldown(i)
	return suo
}

// SetNillableCooldown sets the "cooldown" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableCooldown(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetCooldown(*i)
	}
	return suo
}

// AddCooldown adds i to the "cooldown" field.
func (suo *SettingsUpdateOne) AddCooldown(i int) *SettingsUpdateOne {
	suo.mutation.AddCooldown(i)
	return suo
}

// SetEnableBackToBackCooldown sets the "enableBackToBackCooldown" field.
func (suo *SettingsUpdateOne) SetEnableBackToBackCooldown(b bool) *SettingsUpdateOne {
	suo.mutation.SetEnableBackToBackCooldown(b)
	return suo
}

// SetNillableEnableBackToBackCooldown sets the "enableBackToBackCooldown" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableEnableBackToBackCooldown(b *bool) *SettingsUpdateOne {
	if b != nil {
		suo.SetEnableBackToBackCooldown(*b)
	}
	return suo
}

// SetBackToBackCooldown sets the "backToBackCooldown" field.
func (suo *SettingsUpdateOne) SetBackToBackCooldown(i int) *SettingsUpdateOne {
	suo.mutation.ResetBackToBackCooldown()
	suo.mutation.SetBackToBackCooldown(i)
	return suo
}

// SetNillableBackToBackCooldown sets the "backToBackCooldown" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableBackToBackCooldown(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetBackToBackCooldown(*i)
	}
	return suo
}

// AddBackToBackCooldown adds i to the "backToBackCooldown" field.
func (suo *SettingsUpdateOne) AddBackToBackCooldown(i int) *SettingsUpdateOne {
	suo.mutation.AddBackToBackCooldown(i)
	return suo
}

// SetInformCooldownAfterGuess sets the "informCooldownAfterGuess" field.
func (suo *SettingsUpdateOne) SetInformCooldownAfterGuess(b bool) *SettingsUpdateOne {
	suo.mutation.SetInformCooldownAfterGuess(b)
	return suo
}

// SetNillableInformCooldownAfterGuess sets the "informCooldownAfterGuess" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableInformCooldownAfterGuess(b *bool) *SettingsUpdateOne {
	if b != nil {
		suo.SetInformCooldownAfterGuess(*b)
	}
	return suo
}

// SetFrequency sets the "frequency" field.
func (suo *SettingsUpdateOne) SetFrequency(i int) *SettingsUpdateOne {
	suo.mutation.ResetFrequency()
	suo.mutation.SetFrequency(i)
	return suo
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableFrequency(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetFrequency(*i)
	}
	return suo
}

// AddFrequency adds i to the "frequency" field.
func (suo *SettingsUpdateOne) AddFrequency(i int) *SettingsUpdateOne {
	suo.mutation.AddFrequency(i)
	return suo
}

// SetTimeLimit sets the "timeLimit" field.
func (suo *SettingsUpdateOne) SetTimeLimit(i int) *SettingsUpdateOne {
	suo.mutation.ResetTimeLimit()
	suo.mutation.SetTimeLimit(i)
	return suo
}

// SetNillableTimeLimit sets the "timeLimit" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableTimeLimit(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetTimeLimit(*i)
	}
	return suo
}

// AddTimeLimit adds i to the "timeLimit" field.
func (suo *SettingsUpdateOne) AddTimeLimit(i int) *SettingsUpdateOne {
	suo.mutation.AddTimeLimit(i)
	return suo
}

// SetAutoStart sets the "autoStart" field.
func (suo *SettingsUpdateOne) SetAutoStart(b bool) *SettingsUpdateOne {
	suo.mutation.SetAutoStart(b)
	return suo
}

// SetNillableAutoStart sets the "autoStart" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableAutoStart(b *bool) *SettingsUpdateOne {
	if b != nil {
		suo.SetAutoStart(*b)
	}
	return suo
}

// SetStartAfterFirstGuess sets the "startAfterFirstGuess" field.
func (suo *SettingsUpdateOne) SetStartAfterFirstGuess(b bool) *SettingsUpdateOne {
	suo.mutation.SetStartAfterFirstGuess(b)
	return suo
}

// SetNillableStartAfterFirstGuess sets the "startAfterFirstGuess" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableStartAfterFirstGuess(b *bool) *SettingsUpdateOne {
	if b != nil {
		suo.SetStartAfterFirstGuess(*b)
	}
	return suo
}

// SetHints sets the "hints" field.
func (suo *SettingsUpdateOne) SetHints(f float64) *SettingsUpdateOne {
	suo.mutation.ResetHints()
	suo.mutation.SetHints(f)
	return suo
}

// SetNillableHints sets the "hints" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableHints(f *float64) *SettingsUpdateOne {
	if f != nil {
		suo.SetHints(*f)
	}
	return suo
}

// AddHints adds f to the "hints" field.
func (suo *SettingsUpdateOne) AddHints(f float64) *SettingsUpdateOne {
	suo.mutation.AddHints(f)
	return suo
}

// SetMaxHints sets the "maxHints" field.
func (suo *SettingsUpdateOne) SetMaxHints(f float64) *SettingsUpdateOne {
	suo.mutation.ResetMaxHints()
	suo.mutation.SetMaxHints(f)
	return suo
}

// SetNillableMaxHints sets the "maxHints" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableMaxHints(f *float64) *SettingsUpdateOne {
	if f != nil {
		suo.SetMaxHints(*f)
	}
	return suo
}

// AddMaxHints adds f to the "maxHints" field.
func (suo *SettingsUpdateOne) AddMaxHints(f float64) *SettingsUpdateOne {
	suo.mutation.AddMaxHints(f)
	return suo
}

// SetHintsUsed sets the "hintsUsed" field.
func (suo *SettingsUpdateOne) SetHintsUsed(f float64) *SettingsUpdateOne {
	suo.mutation.ResetHintsUsed()
	suo.mutation.SetHintsUsed(f)
	return suo
}

// SetNillableHintsUsed sets the "hintsUsed" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableHintsUsed(f *float64) *SettingsUpdateOne {
	if f != nil {
		suo.SetHintsUsed(*f)
	}
	return suo
}

// AddHintsUsed adds f to the "hintsUsed" field.
func (suo *SettingsUpdateOne) AddHintsUsed(f float64) *SettingsUpdateOne {
	suo.mutation.AddHintsUsed(f)
	return suo
}

// SetUpdatedAt sets the "updatedAt" field.
func (suo *SettingsUpdateOne) SetUpdatedAt(t time.Time) *SettingsUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// Mutation returns the SettingsMutation object of the builder.
func (suo *SettingsUpdateOne) Mutation() *SettingsMutation {
	return suo.mutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (suo *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Settings entity.
func (suo *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SettingsUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

func (suo *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.GuildID(); ok {
		_spec.SetField(settings.FieldGuildID, field.TypeString, value)
	}
	if value, ok := suo.mutation.BotUpdatesChannelID(); ok {
		_spec.SetField(settings.FieldBotUpdatesChannelID, field.TypeString, value)
	}
	if suo.mutation.BotUpdatesChannelIDCleared() {
		_spec.ClearField(settings.FieldBotUpdatesChannelID, field.TypeString)
	}
	if value, ok := suo.mutation.ChannelID(); ok {
		_spec.SetField(settings.FieldChannelID, field.TypeString, value)
	}
	if suo.mutation.ChannelIDCleared() {
		_spec.ClearField(settings.FieldChannelID, field.TypeString)
	}
	if value, ok := suo.mutation.PingRoleID(); ok {
		_spec.SetField(settings.FieldPingRoleID, field.TypeString, value)
	}
	if suo.mutation.PingRoleIDCleared() {
		_spec.ClearField(settings.FieldPingRoleID, field.TypeString)
	}
	if value, ok := suo.mutation.PingOnlyNew(); ok {
		_spec.SetField(settings.FieldPingOnlyNew, field.TypeBool, value)
	}
	if value, ok := suo.mutation.MembersCanStart(); ok {
		_spec.SetField(settings.FieldMembersCanStart, field.TypeBool, value)
	}
	if value, ok := suo.mutation.Cooldown(); ok {
		_spec.SetField(settings.FieldCooldown, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedCooldown(); ok {
		_spec.AddField(settings.FieldCooldown, field.TypeInt, value)
	}
	if value, ok := suo.mutation.EnableBackToBackCooldown(); ok {
		_spec.SetField(settings.FieldEnableBackToBackCooldown, field.TypeBool, value)
	}
	if value, ok := suo.mutation.BackToBackCooldown(); ok {
		_spec.SetField(settings.FieldBackToBackCooldown, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedBackToBackCooldown(); ok {
		_spec.AddField(settings.FieldBackToBackCooldown, field.TypeInt, value)
	}
	if value, ok := suo.mutation.InformCooldownAfterGuess(); ok {
		_spec.SetField(settings.FieldInformCooldownAfterGuess, field.TypeBool, value)
	}
	if value, ok := suo.mutation.Frequency(); ok {
		_spec.SetField(settings.FieldFrequency, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedFrequency(); ok {
		_spec.AddField(settings.FieldFrequency, field.TypeInt, value)
	}
	if value, ok := suo.mutation.TimeLimit(); ok {
		_spec.SetField(settings.FieldTimeLimit, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedTimeLimit(); ok {
		_spec.AddField(settings.FieldTimeLimit, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AutoStart(); ok {
		_spec.SetField(settings.FieldAutoStart, field.TypeBool, value)
	}
	if value, ok := suo.mutation.StartAfterFirstGuess(); ok {
		_spec.SetField(settings.FieldStartAfterFirstGuess, field.TypeBool, value)
	}
	if value, ok := suo.mutation.Hints(); ok {
		_spec.SetField(settings.FieldHints, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedHints(); ok {
		_spec.AddField(settings.FieldHints, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.MaxHints(); ok {
		_spec.SetField(settings.FieldMaxHints, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedMaxHints(); ok {
		_spec.AddField(settings.FieldMaxHints, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.HintsUsed(); ok {
		_spec.SetField(settings.FieldHintsUsed, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedHintsUsed(); ok {
		_spec.AddField(settings.FieldHintsUsed, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Settings{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
