// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"jurien.dev/yugen/koto/internal/ent/settings"
)

// Settings is the model entity for the Settings schema.
type Settings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GuildID holds the value of the "guildID" field.
	GuildID string `json:"guildID,omitempty"`
	// ChannelID holds the value of the "channelID" field.
	ChannelID *string `json:"channelID,omitempty"`
	// PingRoleID holds the value of the "pingRoleID" field.
	PingRoleID *string `json:"pingRoleID,omitempty"`
	// PingOnlyNew holds the value of the "pingOnlyNew" field.
	PingOnlyNew bool `json:"pingOnlyNew,omitempty"`
	// MembersCanStart holds the value of the "membersCanStart" field.
	MembersCanStart bool `json:"membersCanStart,omitempty"`
	// Cooldown holds the value of the "cooldown" field.
	Cooldown int `json:"cooldown,omitempty"`
	// EnableBackToBackCooldown holds the value of the "enableBackToBackCooldown" field.
	EnableBackToBackCooldown bool `json:"enableBackToBackCooldown,omitempty"`
	// BackToBackCooldown holds the value of the "backToBackCooldown" field.
	BackToBackCooldown int `json:"backToBackCooldown,omitempty"`
	// InformCooldownAfterGuess holds the value of the "informCooldownAfterGuess" field.
	InformCooldownAfterGuess bool `json:"informCooldownAfterGuess,omitempty"`
	// Frequency holds the value of the "frequency" field.
	Frequency int `json:"frequency,omitempty"`
	// TimeLimit holds the value of the "timeLimit" field.
	TimeLimit int `json:"timeLimit,omitempty"`
	// AutoStart holds the value of the "autoStart" field.
	AutoStart bool `json:"autoStart,omitempty"`
	// StartAfterFirstGuess holds the value of the "startAfterFirstGuess" field.
	StartAfterFirstGuess bool `json:"startAfterFirstGuess,omitempty"`
	// Hints holds the value of the "hints" field.
	Hints float64 `json:"hints,omitempty"`
	// MaxHints holds the value of the "maxHints" field.
	MaxHints float64 `json:"maxHints,omitempty"`
	// HintsUsed holds the value of the "hintsUsed" field.
	HintsUsed float64 `json:"hintsUsed,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt    time.Time `json:"updatedAt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Settings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case settings.FieldPingOnlyNew, settings.FieldMembersCanStart, settings.FieldEnableBackToBackCooldown, settings.FieldInformCooldownAfterGuess, settings.FieldAutoStart, settings.FieldStartAfterFirstGuess:
			values[i] = new(sql.NullBool)
		case settings.FieldHints, settings.FieldMaxHints, settings.FieldHintsUsed:
			values[i] = new(sql.NullFloat64)
		case settings.FieldID, settings.FieldCooldown, settings.FieldBackToBackCooldown, settings.FieldFrequency, settings.FieldTimeLimit:
			values[i] = new(sql.NullInt64)
		case settings.FieldGuildID, settings.FieldChannelID, settings.FieldPingRoleID:
			values[i] = new(sql.NullString)
		case settings.FieldCreatedAt, settings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Settings fields.
func (s *Settings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case settings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case settings.FieldGuildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guildID", values[i])
			} else if value.Valid {
				s.GuildID = value.String
			}
		case settings.FieldChannelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channelID", values[i])
			} else if value.Valid {
				s.ChannelID = new(string)
				*s.ChannelID = value.String
			}
		case settings.FieldPingRoleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pingRoleID", values[i])
			} else if value.Valid {
				s.PingRoleID = new(string)
				*s.PingRoleID = value.String
			}
		case settings.FieldPingOnlyNew:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field pingOnlyNew", values[i])
			} else if value.Valid {
				s.PingOnlyNew = value.Bool
			}
		case settings.FieldMembersCanStart:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field membersCanStart", values[i])
			} else if value.Valid {
				s.MembersCanStart = value.Bool
			}
		case settings.FieldCooldown:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown", values[i])
			} else if value.Valid {
				s.Cooldown = int(value.Int64)
			}
		case settings.FieldEnableBackToBackCooldown:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enableBackToBackCooldown", values[i])
			} else if value.Valid {
				s.EnableBackToBackCooldown = value.Bool
			}
		case settings.FieldBackToBackCooldown:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field backToBackCooldown", values[i])
			} else if value.Valid {
				s.BackToBackCooldown = int(value.Int64)
			}
		case settings.FieldInformCooldownAfterGuess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field informCooldownAfterGuess", values[i])
			} else if value.Valid {
				s.InformCooldownAfterGuess = value.Bool
			}
		case settings.FieldFrequency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field frequency", values[i])
			} else if value.Valid {
				s.Frequency = int(value.Int64)
			}
		case settings.FieldTimeLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeLimit", values[i])
			} else if value.Valid {
				s.TimeLimit = int(value.Int64)
			}
		case settings.FieldAutoStart:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field autoStart", values[i])
			} else if value.Valid {
				s.AutoStart = value.Bool
			}
		case settings.FieldStartAfterFirstGuess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field startAfterFirstGuess", values[i])
			} else if value.Valid {
				s.StartAfterFirstGuess = value.Bool
			}
		case settings.FieldHints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hints", values[i])
			} else if value.Valid {
				s.Hints = value.Float64
			}
		case settings.FieldMaxHints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field maxHints", values[i])
			} else if value.Valid {
				s.MaxHints = value.Float64
			}
		case settings.FieldHintsUsed:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hintsUsed", values[i])
			} else if value.Valid {
				s.HintsUsed = value.Float64
			}
		case settings.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case settings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Settings.
// This includes values selected through modifiers, order, etc.
func (s *Settings) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Settings.
// Note that you need to call Settings.Unwrap() before calling this method if this Settings
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Settings) Update() *SettingsUpdateOne {
	return NewSettingsClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Settings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Settings) Unwrap() *Settings {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Settings is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Settings) String() string {
	var builder strings.Builder
	builder.WriteString("Settings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("guildID=")
	builder.WriteString(s.GuildID)
	builder.WriteString(", ")
	if v := s.ChannelID; v != nil {
		builder.WriteString("channelID=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := s.PingRoleID; v != nil {
		builder.WriteString("pingRoleID=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("pingOnlyNew=")
	builder.WriteString(fmt.Sprintf("%v", s.PingOnlyNew))
	builder.WriteString(", ")
	builder.WriteString("membersCanStart=")
	builder.WriteString(fmt.Sprintf("%v", s.MembersCanStart))
	builder.WriteString(", ")
	builder.WriteString("cooldown=")
	builder.WriteString(fmt.Sprintf("%v", s.Cooldown))
	builder.WriteString(", ")
	builder.WriteString("enableBackToBackCooldown=")
	builder.WriteString(fmt.Sprintf("%v", s.EnableBackToBackCooldown))
	builder.WriteString(", ")
	builder.WriteString("backToBackCooldown=")
	builder.WriteString(fmt.Sprintf("%v", s.BackToBackCooldown))
	builder.WriteString(", ")
	builder.WriteString("informCooldownAfterGuess=")
	builder.WriteString(fmt.Sprintf("%v", s.InformCooldownAfterGuess))
	builder.WriteString(", ")
	builder.WriteString("frequency=")
	builder.WriteString(fmt.Sprintf("%v", s.Frequency))
	builder.WriteString(", ")
	builder.WriteString("timeLimit=")
	builder.WriteString(fmt.Sprintf("%v", s.TimeLimit))
	builder.WriteString(", ")
	builder.WriteString("autoStart=")
	builder.WriteString(fmt.Sprintf("%v", s.AutoStart))
	builder.WriteString(", ")
	builder.WriteString("startAfterFirstGuess=")
	builder.WriteString(fmt.Sprintf("%v", s.StartAfterFirstGuess))
	builder.WriteString(", ")
	builder.WriteString("hints=")
	builder.WriteString(fmt.Sprintf("%v", s.Hints))
	builder.WriteString(", ")
	builder.WriteString("maxHints=")
	builder.WriteString(fmt.Sprintf("%v", s.MaxHints))
	builder.WriteString(", ")
	builder.WriteString("hintsUsed=")
	builder.WriteString(fmt.Sprintf("%v", s.HintsUsed))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SettingsSlice is a parsable slice of Settings.
type SettingsSlice []*Settings
