// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/hachimitsu/internal/ent/honeypot"
	"jurien.dev/yugen/hachimitsu/internal/ent/predicate"
)

// HoneypotUpdate is the builder for updating Honeypot entities.
type HoneypotUpdate struct {
	config
	hooks    []Hook
	mutation *HoneypotMutation
}

// Where appends a list predicates to the HoneypotUpdate builder.
func (hu *HoneypotUpdate) Where(ps ...predicate.Honeypot) *HoneypotUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetGuildID sets the "guildID" field.
func (hu *HoneypotUpdate) SetGuildID(s string) *HoneypotUpdate {
	hu.mutation.SetGuildID(s)
	return hu
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (hu *HoneypotUpdate) SetNillableGuildID(s *string) *HoneypotUpdate {
	if s != nil {
		hu.SetGuildID(*s)
	}
	return hu
}

// SetChannelID sets the "channelID" field.
func (hu *HoneypotUpdate) SetChannelID(s string) *HoneypotUpdate {
	hu.mutation.SetChannelID(s)
	return hu
}

// SetNillableChannelID sets the "channelID" field if the given value is not nil.
func (hu *HoneypotUpdate) SetNillableChannelID(s *string) *HoneypotUpdate {
	if s != nil {
		hu.SetChannelID(*s)
	}
	return hu
}

// SetIgnoredRoleIDs sets the "ignoredRoleIDs" field.
func (hu *HoneypotUpdate) SetIgnoredRoleIDs(s []string) *HoneypotUpdate {
	hu.mutation.SetIgnoredRoleIDs(s)
	return hu
}

// AppendIgnoredRoleIDs appends s to the "ignoredRoleIDs" field.
func (hu *HoneypotUpdate) AppendIgnoredRoleIDs(s []string) *HoneypotUpdate {
	hu.mutation.AppendIgnoredRoleIDs(s)
	return hu
}

// SetDeleteMessageDays sets the "deleteMessageDays" field.
func (hu *HoneypotUpdate) SetDeleteMessageDays(i int) *HoneypotUpdate {
	hu.mutation.ResetDeleteMessageDays()
	hu.mutation.SetDeleteMessageDays(i)
	return hu
}

// SetNillableDeleteMessageDays sets the "deleteMessageDays" field if the given value is not nil.
func (hu *HoneypotUpdate) SetNillableDeleteMessageDays(i *int) *HoneypotUpdate {
	if i != nil {
		hu.SetDeleteMessageDays(*i)
	}
	return hu
}

// AddDeleteMessageDays adds i to the "deleteMessageDays" field.
func (hu *HoneypotUpdate) AddDeleteMessageDays(i int) *HoneypotUpdate {
	hu.mutation.AddDeleteMessageDays(i)
	return hu
}

// SetUpdatedAt sets the "updatedAt" field.
func (hu *HoneypotUpdate) SetUpdatedAt(t time.Time) *HoneypotUpdate {
	hu.mutation.SetUpdatedAt(t)
	return hu
}

// Mutation returns the HoneypotMutation object of the builder.
func (hu *HoneypotUpdate) Mutation() *HoneypotMutation {
	return hu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HoneypotUpdate) Save(ctx context.Context) (int, error) {
	hu.defaults()
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HoneypotUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HoneypotUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HoneypotUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hu *HoneypotUpdate) defaults() {
	if _, ok := hu.mutation.UpdatedAt(); !ok {
		v := honeypot.UpdateDefaultUpdatedAt()
		hu.mutation.SetUpdatedAt(v)
	}
}

func (hu *HoneypotUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(honeypot.Table, honeypot.Columns, sqlgraph.NewFieldSpec(honeypot.FieldID, field.TypeInt))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.GuildID(); ok {
		_spec.SetField(honeypot.FieldGuildID, field.TypeString, value)
	}
	if value, ok := hu.mutation.ChannelID(); ok {
		_spec.SetField(honeypot.FieldChannelID, field.TypeString, value)
	}
	if value, ok := hu.mutation.IgnoredRoleIDs(); ok {
		_spec.SetField(honeypot.FieldIgnoredRoleIDs, field.TypeJSON, value)
	}
	if value, ok := hu.mutation.AppendedIgnoredRoleIDs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, honeypot.FieldIgnoredRoleIDs, value)
		})
	}
	if value, ok := hu.mutation.DeleteMessageDays(); ok {
		_spec.SetField(honeypot.FieldDeleteMessageDays, field.TypeInt, value)
	}
	if value, ok := hu.mutation.AddedDeleteMessageDays(); ok {
		_spec.AddField(honeypot.FieldDeleteMessageDays, field.TypeInt, value)
	}
	if value, ok := hu.mutation.UpdatedAt(); ok {
		_spec.SetField(honeypot.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{honeypot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HoneypotUpdateOne is the builder for updating a single Honeypot entity.
type HoneypotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HoneypotMutation
}

// SetGuildID sets the "guildID" field.
func (huo *HoneypotUpdateOne) SetGuildID(s string) *HoneypotUpdateOne {
	huo.mutation.SetGuildID(s)
	return huo
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (huo *HoneypotUpdateOne) SetNillableGuildID(s *string) *HoneypotUpdateOne {
	if s != nil {
		huo.SetGuildID(*s)
	}
	return huo
}

// SetChannelID sets the "channelID" field.
func (huo *HoneypotUpdateOne) SetChannelID(s string) *HoneypotUpdateOne {
	huo.mutation.SetChannelID(s)
	return huo
}

// SetNillableChannelID sets the "channelID" field if the given value is not nil.
func (huo *HoneypotUpdateOne) SetNillableChannelID(s *string) *HoneypotUpdateOne {
	if s != nil {
		huo.SetChannelID(*s)
	}
	return huo
}

// SetIgnoredRoleIDs sets the "ignoredRoleIDs" field.
func (huo *HoneypotUpdateOne) SetIgnoredRoleIDs(s []string) *HoneypotUpdateOne {
	huo.mutation.SetIgnoredRoleIDs(s)
	return huo
}

// AppendIgnoredRoleIDs appends s to the "ignoredRoleIDs" field.
func (huo *HoneypotUpdateOne) AppendIgnoredRoleIDs(s []string) *HoneypotUpdateOne {
	huo.mutation.AppendIgnoredRoleIDs(s)
	return huo
}

// SetDeleteMessageDays sets the "deleteMessageDays" field.
func (huo *HoneypotUpdateOne) SetDeleteMessageDays(i int) *HoneypotUpdateOne {
	huo.mutation.ResetDeleteMessageDays()
	huo.mutation.SetDeleteMessageDays(i)
	return huo
}

// SetNillableDeleteMessageDays sets the "deleteMessageDays" field if the given value is not nil.
func (huo *HoneypotUpdateOne) SetNillableDeleteMessageDays(i *int) *HoneypotUpdateOne {
	if i != nil {
		huo.SetDeleteMessageDays(*i)
	}
	return huo
}

// AddDeleteMessageDays adds i to the "deleteMessageDays" field.
func (huo *HoneypotUpdateOne) AddDeleteMessageDays(i int) *HoneypotUpdateOne {
	huo.mutation.AddDeleteMessageDays(i)
	return huo
}

// SetUpdatedAt sets the "updatedAt" field.
func (huo *HoneypotUpdateOne) SetUpdatedAt(t time.Time) *HoneypotUpdateOne {
	huo.mutation.SetUpdatedAt(t)
	return huo
}

// Mutation returns the HoneypotMutation object of the builder.
func (huo *HoneypotUpdateOne) Mutation() *HoneypotMutation {
	return huo.mutation
}

// Where appends a list predicates to the HoneypotUpdate builder.
func (huo *HoneypotUpdateOne) Where(ps ...predicate.Honeypot) *HoneypotUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HoneypotUpdateOne) Select(field string, fields ...string) *HoneypotUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Honeypot entity.
func (huo *HoneypotUpdateOne) Save(ctx context.Context) (*Honeypot, error) {
	huo.defaults()
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HoneypotUpdateOne) SaveX(ctx context.Context) *Honeypot {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HoneypotUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HoneypotUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (huo *HoneypotUpdateOne) defaults() {
	if _, ok := huo.mutation.UpdatedAt(); !ok {
		v := honeypot.UpdateDefaultUpdatedAt()
		huo.mutation.SetUpdatedAt(v)
	}
}

func (huo *HoneypotUpdateOne) sqlSave(ctx context.Context) (_node *Honeypot, err error) {
	_spec := sqlgraph.NewUpdateSpec(honeypot.Table, honeypot.Columns, sqlgraph.NewFieldSpec(honeypot.FieldID, field.TypeInt))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Honeypot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, honeypot.FieldID)
		for _, f := range fields {
			if !honeypot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != honeypot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.GuildID(); ok {
		_spec.SetField(honeypot.FieldGuildID, field.TypeString, value)
	}
	if value, ok := huo.mutation.ChannelID(); ok {
		_spec.SetField(honeypot.FieldChannelID, field.TypeString, value)
	}
	if value, ok := huo.mutation.IgnoredRoleIDs(); ok {
		_spec.SetField(honeypot.FieldIgnoredRoleIDs, field.TypeJSON, value)
	}
	if value, ok := huo.mutation.AppendedIgnoredRoleIDs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, honeypot.FieldIgnoredRoleIDs, value)
		})
	}
	if value, ok := huo.mutation.DeleteMessageDays(); ok {
		_spec.SetField(honeypot.FieldDeleteMessageDays, field.TypeInt, value)
	}
	if value, ok := huo.mutation.AddedDeleteMessageDays(); ok {
		_spec.AddField(honeypot.FieldDeleteMessageDays, field.TypeInt, value)
	}
	if value, ok := huo.mutation.UpdatedAt(); ok {
		_spec.SetField(honeypot.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Honeypot{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{honeypot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
