// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"jurien.dev/yugen/hachimitsu/internal/ent/honeypot"
	"jurien.dev/yugen/hachimitsu/internal/ent/predicate"
	"jurien.dev/yugen/hachimitsu/internal/ent/settings"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeHoneypot = "Honeypot"
	TypeSettings = "Settings"
)

// HoneypotMutation represents an operation that mutates the Honeypot nodes in the graph.
type HoneypotMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int
	guildID              *string
	channelID            *string
	ignoredRoleIDs       *[]string
	appendignoredRoleIDs []string
	deleteMessageDays    *int
	adddeleteMessageDays *int
	createdAt            *time.Time
	updatedAt            *time.Time
	clearedFields        map[string]struct{}
	done                 bool
	oldValue             func(context.Context) (*Honeypot, error)
	predicates           []predicate.Honeypot
}

var _ ent.Mutation = (*HoneypotMutation)(nil)

// honeypotOption allows management of the mutation configuration using functional options.
type honeypotOption func(*HoneypotMutation)

// newHoneypotMutation creates new mutation for the Honeypot entity.
func newHoneypotMutation(c config, op Op, opts ...honeypotOption) *HoneypotMutation {
	m := &HoneypotMutation{
		config:        c,
		op:            op,
		typ:           TypeHoneypot,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHoneypotID sets the ID field of the mutation.
func withHoneypotID(id int) honeypotOption {
	return func(m *HoneypotMutation) {
		var (
			err   error
			once  sync.Once
			value *Honeypot
		)
		m.oldValue = func(ctx context.Context) (*Honeypot, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Honeypot.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHoneypot sets the old Honeypot of the mutation.
func withHoneypot(node *Honeypot) honeypotOption {
	return func(m *HoneypotMutation) {
		m.oldValue = func(context.Context) (*Honeypot, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HoneypotMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HoneypotMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HoneypotMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HoneypotMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Honeypot.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetGuildID sets the "guildID" field.
func (m *HoneypotMutation) SetGuildID(s string) {
	m.guildID = &s
}

// GuildID returns the value of the "guildID" field in the mutation.
func (m *HoneypotMutation) GuildID() (r string, exists bool) {
	v := m.guildID
	if v == nil {
		return
	}
	return *v, true
}

// OldGuildID returns the old "guildID" field's value of the Honeypot entity.
// If the Honeypot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HoneypotMutation) OldGuildID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGuildID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGuildID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGuildID: %w", err)
	}
	return oldValue.GuildID, nil
}

// ResetGuildID resets all changes to the "guildID" field.
func (m *HoneypotMutation) ResetGuildID() {
	m.guildID = nil
}

// SetChannelID sets the "channelID" field.
func (m *HoneypotMutation) SetChannelID(s string) {
	m.channelID = &s
}

// ChannelID returns the value of the "channelID" field in the mutation.
func (m *HoneypotMutation) ChannelID() (r string, exists bool) {
	v := m.channelID
	if v == nil {
		return
	}
	return *v, true
}

// OldChannelID returns the old "channelID" field's value of the Honeypot entity.
// If the Honeypot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HoneypotMutation) OldChannelID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChannelID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChannelID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChannelID: %w", err)
	}
	return oldValue.ChannelID, nil
}

// ResetChannelID resets all changes to the "channelID" field.
func (m *HoneypotMutation) ResetChannelID() {
	m.channelID = nil
}

// SetIgnoredRoleIDs sets the "ignoredRoleIDs" field.
func (m *HoneypotMutation) SetIgnoredRoleIDs(s []string) {
	m.ignoredRoleIDs = &s
	m.appendignoredRoleIDs = nil
}

// IgnoredRoleIDs returns the value of the "ignoredRoleIDs" field in the mutation.
func (m *HoneypotMutation) IgnoredRoleIDs() (r []string, exists bool) {
	v := m.ignoredRoleIDs
	if v == nil {
		return
	}
	return *v, true
}

// OldIgnoredRoleIDs returns the old "ignoredRoleIDs" field's value of the Honeypot entity.
// If the Honeypot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HoneypotMutation) OldIgnoredRoleIDs(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIgnoredRoleIDs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIgnoredRoleIDs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIgnoredRoleIDs: %w", err)
	}
	return oldValue.IgnoredRoleIDs, nil
}

// AppendIgnoredRoleIDs adds s to the "ignoredRoleIDs" field.
func (m *HoneypotMutation) AppendIgnoredRoleIDs(s []string) {
	m.appendignoredRoleIDs = append(m.appendignoredRoleIDs, s...)
}

// AppendedIgnoredRoleIDs returns the list of values that were appended to the "ignoredRoleIDs" field in this mutation.
func (m *HoneypotMutation) AppendedIgnoredRoleIDs() ([]string, bool) {
	if len(m.appendignoredRoleIDs) == 0 {
		return nil, false
	}
	return m.appendignoredRoleIDs, true
}

// ResetIgnoredRoleIDs resets all changes to the "ignoredRoleIDs" field.
func (m *HoneypotMutation) ResetIgnoredRoleIDs() {
	m.ignoredRoleIDs = nil
	m.appendignoredRoleIDs = nil
}

// SetDeleteMessageDays sets the "deleteMessageDays" field.
func (m *HoneypotMutation) SetDeleteMessageDays(i int) {
	m.deleteMessageDays = &i
	m.adddeleteMessageDays = nil
}

// DeleteMessageDays returns the value of the "deleteMessageDays" field in the mutation.
func (m *HoneypotMutation) DeleteMessageDays() (r int, exists bool) {
	v := m.deleteMessageDays
	if v == nil {
		return
	}
	return *v, true
}

// OldDeleteMessageDays returns the old "deleteMessageDays" field's value of the Honeypot entity.
// If the Honeypot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HoneypotMutation) OldDeleteMessageDays(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeleteMessageDays is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeleteMessageDays requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeleteMessageDays: %w", err)
	}
	return oldValue.DeleteMessageDays, nil
}

// AddDeleteMessageDays adds i to the "deleteMessageDays" field.
func (m *HoneypotMutation) AddDeleteMessageDays(i int) {
	if m.adddeleteMessageDays != nil {
		*m.adddeleteMessageDays += i
	} else {
		m.adddeleteMessageDays = &i
	}
}

// AddedDeleteMessageDays returns the value that was added to the "deleteMessageDays" field in this mutation.
func (m *HoneypotMutation) AddedDeleteMessageDays() (r int, exists bool) {
	v := m.adddeleteMessageDays
	if v == nil {
		return
	}
	return *v, true
}

// ResetDeleteMessageDays resets all changes to the "deleteMessageDays" field.
func (m *HoneypotMutation) ResetDeleteMessageDays() {
	m.deleteMessageDays = nil
	m.adddeleteMessageDays = nil
}

// SetCreatedAt sets the "createdAt" field.
func (m *HoneypotMutation) SetCreatedAt(t time.Time) {
	m.createdAt = &t
}

// CreatedAt returns the value of the "createdAt" field in the mutation.
func (m *HoneypotMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.createdAt
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "createdAt" field's value of the Honeypot entity.
// If the Honeypot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HoneypotMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "createdAt" field.
func (m *HoneypotMutation) ResetCreatedAt() {
	m.createdAt = nil
}

// SetUpdatedAt sets the "updatedAt" field.
func (m *HoneypotMutation) SetUpdatedAt(t time.Time) {
	m.updatedAt = &t
}

// UpdatedAt returns the value of the "updatedAt" field in the mutation.
func (m *HoneypotMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updatedAt
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updatedAt" field's value of the Honeypot entity.
// If the Honeypot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HoneypotMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updatedAt" field.
func (m *HoneypotMutation) ResetUpdatedAt() {
	m.updatedAt = nil
}

// Where appends a list predicates to the HoneypotMutation builder.
func (m *HoneypotMutation) Where(ps ...predicate.Honeypot) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HoneypotMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HoneypotMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Honeypot, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HoneypotMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HoneypotMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Honeypot).
func (m *HoneypotMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HoneypotMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.guildID != nil {
		fields = append(fields, honeypot.FieldGuildID)
	}
	if m.channelID != nil {
		fields = append(fields, honeypot.FieldChannelID)
	}
	if m.ignoredRoleIDs != nil {
		fields = append(fields, honeypot.FieldIgnoredRoleIDs)
	}
	if m.deleteMessageDays != nil {
		fields = append(fields, honeypot.FieldDeleteMessageDays)
	}
	if m.createdAt != nil {
		fields = append(fields, honeypot.FieldCreatedAt)
	}
	if m.updatedAt != nil {
		fields = append(fields, honeypot.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HoneypotMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case honeypot.FieldGuildID:
		return m.GuildID()
	case honeypot.FieldChannelID:
		return m.ChannelID()
	case honeypot.FieldIgnoredRoleIDs:
		return m.IgnoredRoleIDs()
	case honeypot.FieldDeleteMessageDays:
		return m.DeleteMessageDays()
	case honeypot.FieldCreatedAt:
		return m.CreatedAt()
	case honeypot.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HoneypotMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case honeypot.FieldGuildID:
		return m.OldGuildID(ctx)
	case honeypot.FieldChannelID:
		return m.OldChannelID(ctx)
	case honeypot.FieldIgnoredRoleIDs:
		return m.OldIgnoredRoleIDs(ctx)
	case honeypot.FieldDeleteMessageDays:
		return m.OldDeleteMessageDays(ctx)
	case honeypot.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case honeypot.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Honeypot field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HoneypotMutation) SetField(name string, value ent.Value) error {
	switch name {
	case honeypot.FieldGuildID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGuildID(v)
		return nil
	case honeypot.FieldChannelID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChannelID(v)
		return nil
	case honeypot.FieldIgnoredRoleIDs:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIgnoredRoleIDs(v)
		return nil
	case honeypot.FieldDeleteMessageDays:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeleteMessageDays(v)
		return nil
	case honeypot.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case honeypot.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Honeypot field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HoneypotMutation) AddedFields() []string {
	var fields []string
	if m.adddeleteMessageDays != nil {
		fields = append(fields, honeypot.FieldDeleteMessageDays)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HoneypotMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case honeypot.FieldDeleteMessageDays:
		return m.AddedDeleteMessageDays()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HoneypotMutation) AddField(name string, value ent.Value) error {
	switch name {
	case honeypot.FieldDeleteMessageDays:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDeleteMessageDays(v)
		return nil
	}
	return fmt.Errorf("unknown Honeypot numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HoneypotMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HoneypotMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HoneypotMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Honeypot nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HoneypotMutation) ResetField(name string) error {
	switch name {
	case honeypot.FieldGuildID:
		m.ResetGuildID()
		return nil
	case honeypot.FieldChannelID:
		m.ResetChannelID()
		return nil
	case honeypot.FieldIgnoredRoleIDs:
		m.ResetIgnoredRoleIDs()
		return nil
	case honeypot.FieldDeleteMessageDays:
		m.ResetDeleteMessageDays()
		return nil
	case honeypot.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case honeypot.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Honeypot field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HoneypotMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HoneypotMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HoneypotMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HoneypotMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HoneypotMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HoneypotMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HoneypotMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Honeypot unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HoneypotMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Honeypot edge %s", name)
}

// SettingsMutation represents an operation that mutates the Settings nodes in the graph.
type SettingsMutation struct {
	config
	op            Op
	typ           string
	id            *int
	guildID       *string
	logChannelID  *string
	logPingRoleID *string
	createdAt     *time.Time
	updatedAt     *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Settings, error)
	predicates    []predicate.Settings
}

var _ ent.Mutation = (*SettingsMutation)(nil)

// settingsOption allows management of the mutation configuration using functional options.
type settingsOption func(*SettingsMutation)

// newSettingsMutation creates new mutation for the Settings entity.
func newSettingsMutation(c config, op Op, opts ...settingsOption) *SettingsMutation {
	m := &SettingsMutation{
		config:        c,
		op:            op,
		typ:           TypeSettings,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSettingsID sets the ID field of the mutation.
func withSettingsID(id int) settingsOption {
	return func(m *SettingsMutation) {
		var (
			err   error
			once  sync.Once
			value *Settings
		)
		m.oldValue = func(ctx context.Context) (*Settings, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Settings.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSettings sets the old Settings of the mutation.
func withSettings(node *Settings) settingsOption {
	return func(m *SettingsMutation) {
		m.oldValue = func(context.Context) (*Settings, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SettingsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SettingsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SettingsMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SettingsMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Settings.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetGuildID sets the "guildID" field.
func (m *SettingsMutation) SetGuildID(s string) {
	m.guildID = &s
}

// GuildID returns the value of the "guildID" field in the mutation.
func (m *SettingsMutation) GuildID() (r string, exists bool) {
	v := m.guildID
	if v == nil {
		return
	}
	return *v, true
}

// OldGuildID returns the old "guildID" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldGuildID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGuildID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGuildID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGuildID: %w", err)
	}
	return oldValue.GuildID, nil
}

// ResetGuildID resets all changes to the "guildID" field.
func (m *SettingsMutation) ResetGuildID() {
	m.guildID = nil
}

// SetLogChannelID sets the "logChannelID" field.
func (m *SettingsMutation) SetLogChannelID(s string) {
	m.logChannelID = &s
}

// LogChannelID returns the value of the "logChannelID" field in the mutation.
func (m *SettingsMutation) LogChannelID() (r string, exists bool) {
	v := m.logChannelID
	if v == nil {
		return
	}
	return *v, true
}

// OldLogChannelID returns the old "logChannelID" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldLogChannelID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLogChannelID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLogChannelID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLogChannelID: %w", err)
	}
	return oldValue.LogChannelID, nil
}

// ClearLogChannelID clears the value of the "logChannelID" field.
func (m *SettingsMutation) ClearLogChannelID() {
	m.logChannelID = nil
	m.clearedFields[settings.FieldLogChannelID] = struct{}{}
}

// LogChannelIDCleared returns if the "logChannelID" field was cleared in this mutation.
func (m *SettingsMutation) LogChannelIDCleared() bool {
	_, ok := m.clearedFields[settings.FieldLogChannelID]
	return ok
}

// ResetLogChannelID resets all changes to the "logChannelID" field.
func (m *SettingsMutation) ResetLogChannelID() {
	m.logChannelID = nil
	delete(m.clearedFields, settings.FieldLogChannelID)
}

// SetLogPingRoleID sets the "logPingRoleID" field.
func (m *SettingsMutation) SetLogPingRoleID(s string) {
	m.logPingRoleID = &s
}

// LogPingRoleID returns the value of the "logPingRoleID" field in the mutation.
func (m *SettingsMutation) LogPingRoleID() (r string, exists bool) {
	v := m.logPingRoleID
	if v == nil {
		return
	}
	return *v, true
}

// OldLogPingRoleID returns the old "logPingRoleID" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldLogPingRoleID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLogPingRoleID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLogPingRoleID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLogPingRoleID: %w", err)
	}
	return oldValue.LogPingRoleID, nil
}

// ClearLogPingRoleID clears the value of the "logPingRoleID" field.
func (m *SettingsMutation) ClearLogPingRoleID() {
	m.logPingRoleID = nil
	m.clearedFields[settings.FieldLogPingRoleID] = struct{}{}
}

// LogPingRoleIDCleared returns if the "logPingRoleID" field was cleared in this mutation.
func (m *SettingsMutation) LogPingRoleIDCleared() bool {
	_, ok := m.clearedFields[settings.FieldLogPingRoleID]
	return ok
}

// ResetLogPingRoleID resets all changes to the "logPingRoleID" field.
func (m *SettingsMutation) ResetLogPingRoleID() {
	m.logPingRoleID = nil
	delete(m.clearedFields, settings.FieldLogPingRoleID)
}

// SetCreatedAt sets the "createdAt" field.
func (m *SettingsMutation) SetCreatedAt(t time.Time) {
	m.createdAt = &t
}

// CreatedAt returns the value of the "createdAt" field in the mutation.
func (m *SettingsMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.createdAt
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "createdAt" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "createdAt" field.
func (m *SettingsMutation) ResetCreatedAt() {
	m.createdAt = nil
}

// SetUpdatedAt sets the "updatedAt" field.
func (m *SettingsMutation) SetUpdatedAt(t time.Time) {
	m.updatedAt = &t
}

// UpdatedAt returns the value of the "updatedAt" field in the mutation.
func (m *SettingsMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updatedAt
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updatedAt" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updatedAt" field.
func (m *SettingsMutation) ResetUpdatedAt() {
	m.updatedAt = nil
}

// Where appends a list predicates to the SettingsMutation builder.
func (m *SettingsMutation) Where(ps ...predicate.Settings) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SettingsMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SettingsMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Settings, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SettingsMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SettingsMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Settings).
func (m *SettingsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SettingsMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.guildID != nil {
		fields = append(fields, settings.FieldGuildID)
	}
	if m.logChannelID != nil {
		fields = append(fields, settings.FieldLogChannelID)
	}
	if m.logPingRoleID != nil {
		fields = append(fields, settings.FieldLogPingRoleID)
	}
	if m.createdAt != nil {
		fields = append(fields, settings.FieldCreatedAt)
	}
	if m.updatedAt != nil {
		fields = append(fields, settings.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SettingsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case settings.FieldGuildID:
		return m.GuildID()
	case settings.FieldLogChannelID:
		return m.LogChannelID()
	case settings.FieldLogPingRoleID:
		return m.LogPingRoleID()
	case settings.FieldCreatedAt:
		return m.CreatedAt()
	case settings.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SettingsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case settings.FieldGuildID:
		return m.OldGuildID(ctx)
	case settings.FieldLogChannelID:
		return m.OldLogChannelID(ctx)
	case settings.FieldLogPingRoleID:
		return m.OldLogPingRoleID(ctx)
	case settings.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case settings.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Settings field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SettingsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case settings.FieldGuildID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGuildID(v)
		return nil
	case settings.FieldLogChannelID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLogChannelID(v)
		return nil
	case settings.FieldLogPingRoleID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLogPingRoleID(v)
		return nil
	case settings.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case settings.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Settings field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SettingsMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SettingsMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SettingsMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Settings numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SettingsMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(settings.FieldLogChannelID) {
		fields = append(fields, settings.FieldLogChannelID)
	}
	if m.FieldCleared(settings.FieldLogPingRoleID) {
		fields = append(fields, settings.FieldLogPingRoleID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SettingsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SettingsMutation) ClearField(name string) error {
	switch name {
	case settings.FieldLogChannelID:
		m.ClearLogChannelID()
		return nil
	case settings.FieldLogPingRoleID:
		m.ClearLogPingRoleID()
		return nil
	}
	return fmt.Errorf("unknown Settings nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SettingsMutation) ResetField(name string) error {
	switch name {
	case settings.FieldGuildID:
		m.ResetGuildID()
		return nil
	case settings.FieldLogChannelID:
		m.ResetLogChannelID()
		return nil
	case settings.FieldLogPingRoleID:
		m.ResetLogPingRoleID()
		return nil
	case settings.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case settings.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Settings field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SettingsMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SettingsMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SettingsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SettingsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SettingsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SettingsMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SettingsMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Settings unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SettingsMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Settings edge %s", name)
}
