// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"jurien.dev/yugen/hachimitsu/internal/ent/honeypot"
	"jurien.dev/yugen/hachimitsu/internal/ent/schema"
	"jurien.dev/yugen/hachimitsu/internal/ent/settings"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	honeypotFields := schema.Honeypot{}.Fields()
	_ = honeypotFields
	// honeypotDescIgnoredRoleIDs is the schema descriptor for ignoredRoleIDs field.
	honeypotDescIgnoredRoleIDs := honeypotFields[2].Descriptor()
	// honeypot.DefaultIgnoredRoleIDs holds the default value on creation for the ignoredRoleIDs field.
	honeypot.DefaultIgnoredRoleIDs = honeypotDescIgnoredRoleIDs.Default.([]string)
	// honeypotDescDeleteMessageDays is the schema descriptor for deleteMessageDays field.
	honeypotDescDeleteMessageDays := honeypotFields[3].Descriptor()
	// honeypot.DefaultDeleteMessageDays holds the default value on creation for the deleteMessageDays field.
	honeypot.DefaultDeleteMessageDays = honeypotDescDeleteMessageDays.Default.(int)
	// honeypotDescCreatedAt is the schema descriptor for createdAt field.
	honeypotDescCreatedAt := honeypotFields[4].Descriptor()
	// honeypot.DefaultCreatedAt holds the default value on creation for the createdAt field.
	honeypot.DefaultCreatedAt = honeypotDescCreatedAt.Default.(func() time.Time)
	// honeypotDescUpdatedAt is the schema descriptor for updatedAt field.
	honeypotDescUpdatedAt := honeypotFields[5].Descriptor()
	// honeypot.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	honeypot.DefaultUpdatedAt = honeypotDescUpdatedAt.Default.(func() time.Time)
	// honeypot.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	honeypot.UpdateDefaultUpdatedAt = honeypotDescUpdatedAt.UpdateDefault.(func() time.Time)
	settingsFields := schema.Settings{}.Fields()
	_ = settingsFields
	// settingsDescCreatedAt is the schema descriptor for createdAt field.
	settingsDescCreatedAt := settingsFields[3].Descriptor()
	// settings.DefaultCreatedAt holds the default value on creation for the createdAt field.
	settings.DefaultCreatedAt = settingsDescCreatedAt.Default.(func() time.Time)
	// settingsDescUpdatedAt is the schema descriptor for updatedAt field.
	settingsDescUpdatedAt := settingsFields[4].Descriptor()
	// settings.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	settings.DefaultUpdatedAt = settingsDescUpdatedAt.Default.(func() time.Time)
	// settings.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	settings.UpdateDefaultUpdatedAt = settingsDescUpdatedAt.UpdateDefault.(func() time.Time)
}
