// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"jurien.dev/yugen/hachimitsu/internal/ent/predicate"
	"jurien.dev/yugen/hachimitsu/internal/ent/settings"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (su *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetGuildID sets the "guildID" field.
func (su *SettingsUpdate) SetGuildID(s string) *SettingsUpdate {
	su.mutation.SetGuildID(s)
	return su
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableGuildID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetGuildID(*s)
	}
	return su
}

// SetLogChannelID sets the "logChannelID" field.
func (su *SettingsUpdate) SetLogChannelID(s string) *SettingsUpdate {
	su.mutation.SetLogChannelID(s)
	return su
}

// SetNillableLogChannelID sets the "logChannelID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableLogChannelID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetLogChannelID(*s)
	}
	return su
}

// ClearLogChannelID clears the value of the "logChannelID" field.
func (su *SettingsUpdate) ClearLogChannelID() *SettingsUpdate {
	su.mutation.ClearLogChannelID()
	return su
}

// SetLogPingRoleID sets the "logPingRoleID" field.
func (su *SettingsUpdate) SetLogPingRoleID(s string) *SettingsUpdate {
	su.mutation.SetLogPingRoleID(s)
	return su
}

// SetNillableLogPingRoleID sets the "logPingRoleID" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableLogPingRoleID(s *string) *SettingsUpdate {
	if s != nil {
		su.SetLogPingRoleID(*s)
	}
	return su
}

// ClearLogPingRoleID clears the value of the "logPingRoleID" field.
func (su *SettingsUpdate) ClearLogPingRoleID() *SettingsUpdate {
	su.mutation.ClearLogPingRoleID()
	return su
}

// SetUpdatedAt sets the "updatedAt" field.
func (su *SettingsUpdate) SetUpdatedAt(t time.Time) *SettingsUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// Mutation returns the SettingsMutation object of the builder.
func (su *SettingsUpdate) Mutation() *SettingsMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SettingsUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SettingsUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SettingsUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

func (su *SettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.GuildID(); ok {
		_spec.SetField(settings.FieldGuildID, field.TypeString, value)
	}
	if value, ok := su.mutation.LogChannelID(); ok {
		_spec.SetField(settings.FieldLogChannelID, field.TypeString, value)
	}
	if su.mutation.LogChannelIDCleared() {
		_spec.ClearField(settings.FieldLogChannelID, field.TypeString)
	}
	if value, ok := su.mutation.LogPingRoleID(); ok {
		_spec.SetField(settings.FieldLogPingRoleID, field.TypeString, value)
	}
	if su.mutation.LogPingRoleIDCleared() {
		_spec.ClearField(settings.FieldLogPingRoleID, field.TypeString)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetGuildID sets the "guildID" field.
func (suo *SettingsUpdateOne) SetGuildID(s string) *SettingsUpdateOne {
	suo.mutation.SetGuildID(s)
	return suo
}

// SetNillableGuildID sets the "guildID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableGuildID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetGuildID(*s)
	}
	return suo
}

// SetLogChannelID sets the "logChannelID" field.
func (suo *SettingsUpdateOne) SetLogChannelID(s string) *SettingsUpdateOne {
	suo.mutation.SetLogChannelID(s)
	return suo
}

// SetNillableLogChannelID sets the "logChannelID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableLogChannelID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetLogChannelID(*s)
	}
	return suo
}

// ClearLogChannelID clears the value of the "logChannelID" field.
func (suo *SettingsUpdateOne) ClearLogChannelID() *SettingsUpdateOne {
	suo.mutation.ClearLogChannelID()
	return suo
}

// SetLogPingRoleID sets the "logPingRoleID" field.
func (suo *SettingsUpdateOne) SetLogPingRoleID(s string) *SettingsUpdateOne {
	suo.mutation.SetLogPingRoleID(s)
	return suo
}

// SetNillableLogPingRoleID sets the "logPingRoleID" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableLogPingRoleID(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetLogPingRoleID(*s)
	}
	return suo
}

// ClearLogPingRoleID clears the value of the "logPingRoleID" field.
func (suo *SettingsUpdateOne) ClearLogPingRoleID() *SettingsUpdateOne {
	suo.mutation.ClearLogPingRoleID()
	return suo
}

// SetUpdatedAt sets the "updatedAt" field.
func (suo *SettingsUpdateOne) SetUpdatedAt(t time.Time) *SettingsUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// Mutation returns the SettingsMutation object of the builder.
func (suo *SettingsUpdateOne) Mutation() *SettingsMutation {
	return suo.mutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (suo *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Settings entity.
func (suo *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SettingsUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

func (suo *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.GuildID(); ok {
		_spec.SetField(settings.FieldGuildID, field.TypeString, value)
	}
	if value, ok := suo.mutation.LogChannelID(); ok {
		_spec.SetField(settings.FieldLogChannelID, field.TypeString, value)
	}
	if suo.mutation.LogChannelIDCleared() {
		_spec.ClearField(settings.FieldLogChannelID, field.TypeString)
	}
	if value, ok := suo.mutation.LogPingRoleID(); ok {
		_spec.SetField(settings.FieldLogPingRoleID, field.TypeString, value)
	}
	if suo.mutation.LogPingRoleIDCleared() {
		_spec.ClearField(settings.FieldLogPingRoleID, field.TypeString)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Settings{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
