// Code generated by ent, DO NOT EDIT.

package game

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"jurien.dev/yugen/koto/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldID, id))
}

// GuildID applies equality check predicate on the "guildID" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldGuildID, v))
}

// LastMessageID applies equality check predicate on the "lastMessageID" field. It's identical to LastMessageIDEQ.
func LastMessageID(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldLastMessageID, v))
}

// Word applies equality check predicate on the "word" field. It's identical to WordEQ.
func Word(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldWord, v))
}

// EndingAt applies equality check predicate on the "endingAt" field. It's identical to EndingAtEQ.
func EndingAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldEndingAt, v))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldNumber, v))
}

// ScheduleStarted applies equality check predicate on the "scheduleStarted" field. It's identical to ScheduleStartedEQ.
func ScheduleStarted(v bool) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldScheduleStarted, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// GuildIDEQ applies the EQ predicate on the "guildID" field.
func GuildIDEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guildID" field.
func GuildIDNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guildID" field.
func GuildIDIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guildID" field.
func GuildIDNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guildID" field.
func GuildIDGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guildID" field.
func GuildIDGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guildID" field.
func GuildIDLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guildID" field.
func GuildIDLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guildID" field.
func GuildIDContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guildID" field.
func GuildIDHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guildID" field.
func GuildIDHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guildID" field.
func GuildIDEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guildID" field.
func GuildIDContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldGuildID, v))
}

// LastMessageIDEQ applies the EQ predicate on the "lastMessageID" field.
func LastMessageIDEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldLastMessageID, v))
}

// LastMessageIDNEQ applies the NEQ predicate on the "lastMessageID" field.
func LastMessageIDNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldLastMessageID, v))
}

// LastMessageIDIn applies the In predicate on the "lastMessageID" field.
func LastMessageIDIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldLastMessageID, vs...))
}

// LastMessageIDNotIn applies the NotIn predicate on the "lastMessageID" field.
func LastMessageIDNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldLastMessageID, vs...))
}

// LastMessageIDGT applies the GT predicate on the "lastMessageID" field.
func LastMessageIDGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldLastMessageID, v))
}

// LastMessageIDGTE applies the GTE predicate on the "lastMessageID" field.
func LastMessageIDGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldLastMessageID, v))
}

// LastMessageIDLT applies the LT predicate on the "lastMessageID" field.
func LastMessageIDLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldLastMessageID, v))
}

// LastMessageIDLTE applies the LTE predicate on the "lastMessageID" field.
func LastMessageIDLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldLastMessageID, v))
}

// LastMessageIDContains applies the Contains predicate on the "lastMessageID" field.
func LastMessageIDContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldLastMessageID, v))
}

// LastMessageIDHasPrefix applies the HasPrefix predicate on the "lastMessageID" field.
func LastMessageIDHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldLastMessageID, v))
}

// LastMessageIDHasSuffix applies the HasSuffix predicate on the "lastMessageID" field.
func LastMessageIDHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldLastMessageID, v))
}

// LastMessageIDIsNil applies the IsNil predicate on the "lastMessageID" field.
func LastMessageIDIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldLastMessageID))
}

// LastMessageIDNotNil applies the NotNil predicate on the "lastMessageID" field.
func LastMessageIDNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldLastMessageID))
}

// LastMessageIDEqualFold applies the EqualFold predicate on the "lastMessageID" field.
func LastMessageIDEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldLastMessageID, v))
}

// LastMessageIDContainsFold applies the ContainsFold predicate on the "lastMessageID" field.
func LastMessageIDContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldLastMessageID, v))
}

// WordEQ applies the EQ predicate on the "word" field.
func WordEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldWord, v))
}

// WordNEQ applies the NEQ predicate on the "word" field.
func WordNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldWord, v))
}

// WordIn applies the In predicate on the "word" field.
func WordIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldWord, vs...))
}

// WordNotIn applies the NotIn predicate on the "word" field.
func WordNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldWord, vs...))
}

// WordGT applies the GT predicate on the "word" field.
func WordGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldWord, v))
}

// WordGTE applies the GTE predicate on the "word" field.
func WordGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldWord, v))
}

// WordLT applies the LT predicate on the "word" field.
func WordLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldWord, v))
}

// WordLTE applies the LTE predicate on the "word" field.
func WordLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldWord, v))
}

// WordContains applies the Contains predicate on the "word" field.
func WordContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldWord, v))
}

// WordHasPrefix applies the HasPrefix predicate on the "word" field.
func WordHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldWord, v))
}

// WordHasSuffix applies the HasSuffix predicate on the "word" field.
func WordHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldWord, v))
}

// WordEqualFold applies the EqualFold predicate on the "word" field.
func WordEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldWord, v))
}

// WordContainsFold applies the ContainsFold predicate on the "word" field.
func WordContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldWord, v))
}

// EndingAtEQ applies the EQ predicate on the "endingAt" field.
func EndingAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldEndingAt, v))
}

// EndingAtNEQ applies the NEQ predicate on the "endingAt" field.
func EndingAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldEndingAt, v))
}

// EndingAtIn applies the In predicate on the "endingAt" field.
func EndingAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldEndingAt, vs...))
}

// EndingAtNotIn applies the NotIn predicate on the "endingAt" field.
func EndingAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldEndingAt, vs...))
}

// EndingAtGT applies the GT predicate on the "endingAt" field.
func EndingAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldEndingAt, v))
}

// EndingAtGTE applies the GTE predicate on the "endingAt" field.
func EndingAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldEndingAt, v))
}

// EndingAtLT applies the LT predicate on the "endingAt" field.
func EndingAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldEndingAt, v))
}

// EndingAtLTE applies the LTE predicate on the "endingAt" field.
func EndingAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldEndingAt, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldNumber, v))
}

// ScheduleStartedEQ applies the EQ predicate on the "scheduleStarted" field.
func ScheduleStartedEQ(v bool) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldScheduleStarted, v))
}

// ScheduleStartedNEQ applies the NEQ predicate on the "scheduleStarted" field.
func ScheduleStartedNEQ(v bool) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldScheduleStarted, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGuesses applies the HasEdge predicate on the "guesses" edge.
func HasGuesses() predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GuessesTable, GuessesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGuessesWith applies the HasEdge predicate on the "guesses" edge with a given conditions (other predicates).
func HasGuessesWith(preds ...predicate.Guess) predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := newGuessesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Game) predicate.Game {
	return predicate.Game(sql.NotPredicates(p))
}
